### ISSUE TITLE
Font color parsing

### ISSUE THREAD

**Issue by dpeek** [haxenme/nme#119]
Firstly I was pleasantly surprised to see that basic html styling works on TextFields in OpenFL, either I'd missed that or it's new :+1: 

Small issue on Android, however, where the parsed values seem to be misaligned (if that's the right word for it.. probably not)

I suspect it's either a TinyXML issue in TIXML_SSCANF, or something in ColorToWide. Here's a screenshot in iOS simulator vs Android device:

https://dl.dropboxusercontent.com/u/6286350/text-color-ios.png
https://dl.dropboxusercontent.com/u/6286350/text-color-android.jpg

```
class Test
{
	public static function main()
	{
		var field = new flash.text.TextField();
		var format = new flash.text.TextFormat();
		format.size = 40;
		field.defaultTextFormat = format;
		field.autoSize = flash.text.TextFieldAutoSize.LEFT;
		field.htmlText = '<font color="#FF0000">red</font>, <font color="#00FF00">green</font>, and <font color="#0000FF">blue</font>';
		flash.Lib.current.addChild(field);
	}
}
```

Probably not high on the priority list, but recording here for posterity :)

**Comment by hughsando** [comment]
This should be sorted now.  Some strange stuff with android.
