### ISSUE TITLE
iOS keyboard - fix @" " hack

### ISSUE THREAD

**Issue by dyarosla** [haxenme/nme#138]
Instead of using @" " as the default input, we should be passing in a String from the display call for the textfield (on a request_soft_keyboard). This way, backspace (on the keyboard) works correctly, and we can also allow for AutoCapitalization options (instead of None).

When doing so, also need to add an additional parameter to backspace when it deletes a whole word, so when [string length] == 0, must trigger the mTextfield's length worth of backspace stroke events.

**Comment by thomasuster** [comment]
Would you do a Pull Request with this and some instructions on how to test it when the PR is submitted?

**Comment by thomasuster** [comment]
I'll reopen if you need.
