### ISSUE TITLE
CURL URLLoader does not support SNI, requests fail with IOError.

### ISSUE THREAD

**Issue by bazzisoft** [haxenme/nme#147]
When making a URLLoader request to any https:// address that does not use a dedicated IP, the underlying CURL request fails with: "subjectAltName(s) do not match my.domain.com"

The same request works correctly via any modern browser and in Flash, via the SNI mechanism. (http://en.wikipedia.org/wiki/Server_Name_Indication)

Reading up a bit it seems there are 2 ways around this:

1) Turn off host verfication in curl:
/nme/project/src/common/CURL.cpp:102
curl_easy_setopt(mHandle, CURLOPT_SSL_VERIFYPEER, false);
+++ curl_easy_setopt(mHandle, CURLOPT_SSL_VERIFYHOST, false);

2) Upgrade curl/openssl as described here (not tested):
http://stackoverflow.com/questions/12941703/use-curl-with-sni-server-name-indication

From my limited understanding of SSL I think option (1) may create a security flaw, as it won't check the certificate against the domain name either. That being said, it would be nice to have the option of turning this on if option (2) is not feasible in the shorter term.

**Comment by thomasuster** [comment]
@bazzisoft Do you still need help with this issue?

**Comment by bazzisoft** [comment]
@thomasuster Not for my project, I used a static IP as a workaround. Still seems worthwhile getting it fixed at some point but it's not urgent for my use case. Thanks for following up!

**Comment by thomasuster** [comment]
Cool, yea I'd rather close for now until someone has the urge to help this along. Aloha
