### ISSUE TITLE
iOS random crash

### ISSUE THREAD

**Issue by shoebox** [haxenme/nme#148]
Hi guys,
I'm currently stuck on a annoying random crash who happens really oftenly in release mode, and is very very rare in debug mode.

The stack is the following:

`#0	0x00d7e552 in val_field at /Users/johann.martinache/Desktop/massive/hxcpp/src/hx/CFFI.cpp:689`

`#1	0x00310514 in external_handler(nme::Event&, void*) at /Users/johann.martinache/Desktop/haxelib2/nme/5,1,8/project/src/common/ExternalInterface.cpp:1285`

`#2	0x002fb5aa in nme::Stage::HandleEvent(nme::Event&) at /Users/johann.martinache/Desktop/haxelib2/nme/5,1,8/project/src/common/Display.cpp:1879`

`#3	0x002a9548 in IOSStage::OnPoll() at /Users/johann.martinache/Desktop/haxelib2/nme/5,1,8/project/src/iPhone/UIStageView.mm:2887`

`#4	0x002a88b2 in -[NMEAppDelegate mainLoop] at /Users/johann.martinache/Desktop/haxelib2/nme/5,1,8/project/src/iPhone/UIStageView.mm:3621`

`#5	0x304c7c22 in __NSThreadPerformPerform ()`

`#6	0x2faa9fe6 in __CFRUNLOOP_IS_CALLING_OUT_TO_A_SOURCE0_PERFORM_FUNCTION__ ()`

`#7	0x2faa9534 in __CFRunLoopDoSources0 ()`

`#8	0x2faa7c9e in __CFRunLoopRun ()`

`#9	0x2fa127a8 in CFRunLoopRunSpecific ()`

`#10	0x2fa1258a in CFRunLoopRunInMode ()`

`#11	0x002a888e in -[NMEAppDelegate mainLoop] at /Users/johann.martinache/Desktop/haxelib2/nme/5,1,8/project/src/iPhone/UIStageView.mm:3619`

`#12	0x304c7c22 in __NSThreadPerformPerform ()`

`#13	0x2faa9fe6 in __CFRUNLOOP_IS_CALLING_OUT_TO_A_SOURCE0_PERFORM_FUNCTION__ ()`

`#14	0x2faa9534 in __CFRunLoopDoSources0 ()`

`#15	0x2faa7c9e in __CFRunLoopRun ()`

`#16	0x2fa127a8 in CFRunLoopRunSpecific ()`

`#17	0x2fa1258a in CFRunLoopRunInMode ()`

`#18	0x002a888e in -[NMEAppDelegate mainLoop] at /Users/johann.martinache/Desktop/haxelib2/nme/5,1,8/project/src/iPhone/UIStageView.mm:3619`

`#19	0x304c7c22 in __NSThreadPerformPerform ()`

`#20	0x2faa9fe6 in __CFRUNLOOP_IS_CALLING_OUT_TO_A_SOURCE0_PERFORM_FUNCTION__ ()`

`#21	0x2faa9534 in __CFRunLoopDoSources0 ()`

`#22	0x2faa7c9e in __CFRunLoopRun ()`

`#23	0x2fa127a8 in CFRunLoopRunSpecific ()`

`#24	0x2fa1258a in CFRunLoopRunInMode ()`

`#25	0x3496f6d2 in GSEventRunModal ()`

`#26	0x32371890 in UIApplicationMain ()`

`#27	0x002a916e in nme::CreateMainFrame(void (*)(nme::Frame*), int, int, unsigned int, char const*, nme::Surface*) at /Users/johann.martinache/Desktop/haxelib2/nme/5,1,8/project/src/iPhone/UIStageView.mm:3808`

`#28	0x0030ffd4 in nme_create_main_frame(_value**, int) at /Users/johann.martinache/Desktop/haxelib2/nme/5,1,8/project/src/common/ExternalInterface.cpp:1186`

`#29	0x00d96978 in ExternalPrimitive::__Run(Array<Dynamic> const&) at /Users/johann.martinache/Desktop/massive/hxcpp/src/hx/Lib.cpp:152`

`#30	0x00db0dc4 in Dynamic::operator()(Dynamic const&, Dynamic const&, Dynamic const&, Dynamic const&, Dynamic const&, Dynamic const&) at /Users/johann.martinache/Desktop/massive/hxcpp/include/hx/DynamicImpl.h:542`

`#31	0x00c39728 in openfl::Lib_obj::create(Dynamic, int, int, hx::Null<double>, hx::Null<int>, hx::Null<int>, String, hx::ObjectPtr<openfl::display::BitmapData_obj>, hx::ObjectPtr<Class_obj>) at /Users/johann.martinache/Desktop/massive/storefront-companion/bin/release/ios/bin/ios/Massivision Native Player/haxe/build/Debug-iphoneos/./src/openfl/Lib.cpp:318`

`#32	0x00d77bca in ApplicationMain_obj::main() at /Users/johann.martinache/Desktop/massive/storefront-companion/bin/release/ios/bin/ios/Massivision Native Player/haxe/build/Debug-iphoneos/./src/ApplicationMain.cpp:172`

`#33	0x00d7ba8e in __hxcpp_lib_main at /Users/johann.martinache/Desktop/massive/storefront-companion/bin/release/ios/bin/ios/Massivision Native Player/haxe/build/Debug-iphoneos/./src/__lib__.cpp:12`

`#34	0x00da461a in hxRunLibrary at /Users/johann.martinache/Desktop/massive/hxcpp/src/hx/RunLibs.cpp:29`

`#35	0x0028ee7e in main at /Users/johann.martinache/Desktop/massive/storefront-companion/bin/release/ios/bin/ios/Massivision Native Player/Classes/Main.mm:129``

If you could help on that one, it would be awesome !!

Thanks

**Comment by thomasuster** [comment]
Do you still need help on this @shoebox ?

**Comment by shoebox** [comment]
Nah can close it. It's very outdated.
