### ISSUE TITLE
chaining framebuffer creation/deletion

### ISSUE THREAD

**Issue by delahee** [haxenme/nme#149]
hi,

On my current version, if i chain texture creation/deletion, at one point the gl driver serves texture but at one point they are pink/black....

if i chain framebuffercreation/deletion, at one point the gl driver simply crashes.

I don't know if there are tests on the nme/lime codebase but I think there should be some and these issue should be addressed
... or maybe it is already fixed and my codebase is too old :)

If you could put up some validation test (or point me to it) it would be so cool :)

Thanks !

**Comment by thomasuster** [comment]
Hey @delahee , are you still having this issue?

**Comment by delahee** [comment]
I don't know :) I just pooled framebuffers so we don t get any error.

**Comment by thomasuster** [comment]
If you make a sample project I wouldn't mind taking a look at it. What platform?

**Comment by delahee** [comment]
I am sorry I cannot dedicate time to this in a near future...:(
