### ISSUE TITLE
antialiasing at runtime

### ISSUE THREAD

**Issue by delahee** [haxenme/nme#159]
@hughsando @jgranick 
Hi folks,

For the scope of my next project, I need to be able to select antialiasing setup at the startup of my application after having scanned the gpu setup and the platform (this i do already).

How can I do that nowaday without setuping my very own framebuffer ? 

Thanks !

**Comment by thomasuster** [comment]
Hey @delahee were you able to solve this? We had some bad artifacts on edges in Pakka Pets for TileSheets. This was only happening when the game had to upscale. We made our own templates/ios/PROJ/Images.xcassets/LaunchImage.launchimage/Contents.json and removed the iPhone6 blocks. Doing that allows your app to run at the max resolution you anticipated and iOS will scale it up smoothly and it will be faster.

**Comment by delahee** [comment]
Issue was about getting multisamples without anti-aliasing and yes
multisamples can cause small artifacts on some situations since it groups
shader samples.

It was not an issue in itself but what you say is interesting.
