### ISSUE TITLE
flash.ui.Mouse.cursor

### ISSUE THREAD

**Issue by ncannasse** [haxenme/nme#163]
Could it be possible to support (on platforms where it makes sense, mainly Desktop) the flash.ui.Mouse.cursor property so we can at least enable different system cursors for UI (textfield, drag, etc.) ?

**Comment by thomasuster** [comment]
Hey @ncannasse , do you still have a use case for this?

**Comment by ncannasse** [comment]
not urgent at all, I'm closing for now.
