### ISSUE TITLE
60 FPS gives 50

### ISSUE THREAD

**Issue by ncannasse** [haxenme/nme#172]
I'm creating a window using this:
```
nme.Lib.create(function() {
            nme.Lib.current.stage.align = nme.display.StageAlign.TOP_LEFT;
            nme.Lib.current.stage.scaleMode = nme.display.StageScaleMode.NO_SCALE;
            nme.Lib.current.loaderInfo = nme.display.LoaderInfo.create(null);
            callb();
         },
         640, 480,
         60,
         0xFFFFFF,
         (true ? nme.Lib.HARDWARE : 0) |
         nme.Lib.ALLOW_SHADERS | nme.Lib.REQUIRE_SHADERS |
         (true ? nme.Lib.DEPTH_BUFFER : 0) |
         (false ? nme.Lib.STENCIL_BUFFER : 0) |
         (true ? nme.Lib.RESIZABLE : 0) |
         (false ? nme.Lib.BORDERLESS : 0) |
         (false ? nme.Lib.VSYNC : 0) |
         (false ? nme.Lib.FULLSCREEN : 0) |
         (0 == 4 ? nme.Lib.HW_AA_HIRES : 0) |
         (0 == 2 ? nme.Lib.HW_AA : 0),
         "Heaps Application"
);
```

However when I measure the FPS in my event loop it will give around 50. Setting the FPS to 120 will work, but I need to set it to 70 to reach 60 in practice (running in Debug, with no display at all).

Any idea ?

**Comment by thomasuster** [comment]
Hey @ncannasse 

I tried the DisplayingABitmap sample on my windows box with haxe 3.2.1, nme 5.5.11, and hxcpp 3.2.201 and the result is the FPS meter staying at 62. Do you have a sample project I could check out showing the problem? Or should we consider this fixed?

![nme-fps](https://cloud.githubusercontent.com/assets/220965/11310117/9a472a24-8f7c-11e5-990e-fb6e0d6a9d7c.png)

**Comment by ncannasse** [comment]
I don't have a sample project for it, I'll open again if I get another similar issue.
