### ISSUE TITLE
Destroy openGL textures. Release memory  problem

### ISSUE THREAD

**Issue by codeservice** [haxenme/nme#174]
OpenGL method  glDeleteTextures(1,&tid); not releasing memory instantly. Its only remove pointers  and mark texture as deleted for driver. Driver usually not delete it instantly because code may reuse texture's previously allocated memory. So in NME I cant destroy bitmap by request when I need it, only when driver ready to do so. Its easy to check by creating and destroying large size bitmap in long cycle. It will kill memory pretty soon. Any Ideas how to do this properly for NME? For now I am using garbage collector GC clean memory after each large bitmap destroy call. This is time cost operation and instant bitmap memory release really needed. Any ideas?

**Comment by thomasuster** [comment]
@codeservice Is your issue resolved using the Gc.run(true)?

**Comment by codeservice** [comment]
Problem that dispose doesn't work as it should. Gc.run(true) extra kick to make it work.
In action script dispose means: "Frees memory that is used to store the BitmapData object."
http://help.adobe.com/en_US/FlashPlatform/reference/actionscript/3/flash/display/BitmapData.html#dispose%28%29
nme doesn't guaranty bitmapdata object will be destroyed. Not sure if "extra kick" count as a solution, its what I am using now.

**Comment by thomasuster** [comment]
I think making a 3k by 3k texture on click is a atypical, but I'm surprised it crashes. Do you have to spam the 30-40 clicks? Or can you click one per second and it crashes.

**Comment by codeservice** [comment]
Yes 3k texture it's not normal, for stress testing only. I pressed space bar and hold it 20...30 seconds. Using windows 7. After crash even windows slowing down. In real app I am don't have 3k textures. I am using many bitmaps and from time to time have to run garbage collector to clean memory. In some cases I need to destroy and create bitmaps very fast and running memory clean up slowing down app significantly.

**Comment by thomasuster** [comment]
Another angle you could try is keeping 1 texture that you paste Bitmaps into using copyPixels. You'll be trading a memory hit for a CPU hit, so it'd be an experiment.

**Comment by codeservice** [comment]
Agree I can use different approach. Can give you idea what kind of
applications need fast create/destroy bitmaps functionality. When you have
endless scrolling of text, images, .... Something like google+, pinterest,
e-shop list, .... Scrolling process should be smooth without delays.
Visible images created, invisible destroyed. User can scroll relatively
fast. I can load images in thread but destroying bitmaps I need to do in
main application.
Would be great if dispose bitmap data release memory instantly as expected
for this case.

**Comment by hughsando** [comment]
I have added a function "gc_change_managed_memory" to the cffi api - the
idea here is that you can add or subtract the GC's idea of how much memory
is under management in the bitmap constructor/destructor  and therefore get
the collect to run automatically more often as needed.
I have not fully looked at the performance implications of this, but
theoretically it should be a solution to this problem.

**Comment by codeservice** [comment]
I did gc cleanup after each bitmapdata.despose in my code. It slowed down scrolling process and it was really choppy on screen. As soon as I remove gc, scrolling back to fast mode, only now trouble with memory. My solution was to create bitmap manager and count how much memory already used and call gc only when situation critical, or run gc when user stop scrolling. Works fine and from time to time I can see little bump on scrolling, now I know its gc "working".

**Comment by codeservice** [comment]
Would it be good idea provide in NME method resizeBitmapdata(w,h)?
In openGl it will reuse the same texture without calling again glGenTextures.
In flash it will destroy old and create new bitmapdata

**Comment by hughsando** [comment]
BitmapData.dispose was not really calling the correct code I think.  I have fixed this, so now the explicit dispose should would without the need for a Gc pass.
The resize method is still a possibility if you still need it.

**Comment by codeservice** [comment]
It works! Thanks!
