### ISSUE TITLE
GL.getShaderPrecisionFormat bug

### ISSUE THREAD

**Issue by mbalestrini** [haxenme/nme#177]
GL.getShaderPrecisionFormat is not working.
I get the following warning:
```Warning: provided object if not a resource in getShaderPrecisionFormat```

The error seems to be in the *nme_gl_get_shader_precision_format*: https://github.com/haxenme/nme/blob/master/project/src/opengl/OGLExport.cpp#L1372
The first parameter of glGetShaderPrecisionFormat is not a shader, but a shaderType enum.

I think this:
```
int id = getResource(inShader,resoShader);
glGetShaderPrecisionFormat(id, val_int(inPrec), range, &precision);
```

should be this:
```glGetShaderPrecisionFormat(val_int(inShader), val_int(inPrec), range, &precision);```

**Comment by thomasuster** [comment]
It looks like this was PR'd. Please close. https://github.com/haxenme/nme/commit/e31e516f951291183558b50911c50484c4320bec
