### ISSUE TITLE
Texfield Embed font issue with android-view

### ISSUE THREAD

**Issue by dmouton** [haxenme/nme#179]
Something working perfectly with Android target, doesn't work with AndroidView target.

I can't use embed font with AndroidView .
It's strange because var fontName = Assets.getFont('fonts/ChalkDust.ttf').fontName;
        trace('applyTextFormat : ' + fontName); give me a correct value.
It looks like my font is properly embedded but if I apply it on my textfield, I have a tiny textWidth, about 2.
And if I do not specify the form to be used, the text appears correctly.
The same thing works very well with Android Target.

**Comment by thomasuster** [comment]
Hey @dmouton are you still having this issue?

**Comment by dmouton** [comment]
I dont know, i transform my text into bitmap.

Le samedi 29 août 2015, Thomas Uster <notifications@github.com> a écrit :

> Hey @dmouton <https://github.com/dmouton> are you still having this issue?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/haxenme/nme/issues/179#issuecomment-135918606>.
>


-- 


*David Mouton--*
Directeur Technique @Happy-Technologies
Tél : 05.57.26.61.00
Mob. : 06.12.63.58.15

**Comment by thomasuster** [comment]
Okay, if you have a use-case in need of this in the future feel free to re-open.
