### ISSUE TITLE
Text on android not rendering.

### ISSUE THREAD

**Issue by codeservice** [haxenme/nme#180]
Can't see text on android. Simple code:

        var txt: TextField = new TextField();
        txt.text = "Test";
        var bd: BitmapData = new BitmapData(150, 300, false, 0x00FFFF);
        bd.draw(txt);
        var qqq: Bitmap = new Bitmap(bd);
        this.addChild(qqq);

Works with cpp/neko. 

I am using NME 5.2.7, NME-DEV 1.3.5, HXCPP 3.1.48, target android  
trace on Nexus 7 lollipop 5.0.1:
01-03 21:07:29.702  17067-17067/com.test.app.test I/art﹕ Late-enabling -Xcheck:jni
01-03 21:07:29.804  17067-17067/com.test.app.test D/GameActivity﹕ ==== onCreate ===== com.test.app.test.MainActivity@1e3d46cb
01-03 21:07:29.828  17067-17067/com.test.app.test I/haxe plugin﹕ Got Load Proc a38decfc
01-03 21:07:29.829  17067-17067/com.test.app.test I/haxe plugin﹕ Got Load Proc a38decfc
01-03 21:07:29.830  17067-17067/com.test.app.test I/haxe plugin﹕ Got Load Proc a38decfc
01-03 21:07:29.831  17067-17067/com.test.app.test I/CreateMainFrame!﹕ creating...
01-03 21:07:29.842  17067-17067/com.test.app.test I/Adreno-EGL﹕ <qeglDrvAPI_eglInitialize:410>: QUALCOMM Build: 10/28/14, c33033c, Ia6306ec328
01-03 21:07:29.843  17067-17067/com.test.app.test E/VIEW﹕ Using OpenglES 2.0
01-03 21:07:29.852  17067-17067/com.test.app.test D/GameActivity﹕ ====== doResume ======== org.haxe.nme.MainView{1cd88d54 VFE..... ......I. 0,0-0,0}
01-03 21:07:29.853  17067-17067/com.test.app.test D/GameActivity﹕ super resume
01-03 21:07:29.859  17067-17090/com.test.app.test D/OpenGLRenderer﹕ Render dirty regions requested: true
01-03 21:07:29.865  17067-17067/com.test.app.test D/Atlas﹕ Validating map...
01-03 21:07:29.902  17067-17090/com.test.app.test I/OpenGLRenderer﹕ Initialized EGL, version 1.4
01-03 21:07:29.926  17067-17090/com.test.app.test D/OpenGLRenderer﹕ Enabling debug mode 0
01-03 21:07:30.032  17067-17089/com.test.app.test V/EGL﹕ Choose config (2) false
01-03 21:07:30.033  17067-17089/com.test.app.test V/EGL﹕ Matched depth + stencil : 1(0)
01-03 21:07:30.053  17067-17089/com.test.app.test V/NME﹕ Send on lost

**Comment by hughsando** [comment]
There was a problem where the BitmapData colour was not coming though, but I have just fixed this.  It is strange that it is not working on android only - maybe some font is missing on lollipop?  Do you get any text if you add the TextField directly, rather than via BitmapData?

**Comment by codeservice** [comment]
Yes you are right. Default font not working on android lollipop. Font as application asset works well.

var result: Font = Assets.getFont("assets/fonts/Bangwool.ttf");
        var txt: TextField = new TextField();
        txt.defaultTextFormat = new TextFormat(result.fontName, 20);
        txt.text = "Test";
        this.addChild(txt);
