### ISSUE TITLE
AndroidView Build Error with NME 5.2.27

### ISSUE THREAD

**Issue by dmouton** [haxenme/nme#181]
C:/HaxeToolkit/haxe/lib/nme/5,2,7/lib/Android/libnme.a(46c795b9_OGLExport.obj): In function `nme::nme_gl_get_extension(_value*)':
OGLExport.cpp:(.text._ZN3nme20nme_gl_get_extensionEP6_value+0x8): undefined reference to `eglGetProcAddress'
collect2: ld returned 1 exit status
Error: Build failed

**Comment by hughsando** [comment]
This symbol should be coming from "-lEGL" on the link line.
Is there any other error like "lib EGL not found"?  A copy of the linking command would help here.

**Comment by damoebius** [comment]
I can't have a look on it before tomorow but you can get it quite easly.
Just try this :
nme create 00-Nmml
cd 00-Nmml
nme build build.nmml androidview

C:/HaxeToolkit/haxe/lib/nme/5,2,7/lib/Android/libnme.a(46c795b9_OGLExport.obj): In function `nme::nme_gl_get_extension(_value*)':
OGLExport.cpp:(.text._ZN3nme20nme_gl_get_extensionEP6_value+0x8): undefined reference to `eglGetProcAddress'
collect2: ld returned 1 exit status
Error: Build failed

**Comment by hughsando** [comment]
Thanks - I missed the android-view testing.
