### ISSUE TITLE
[5.2.13] Problem with isoview

### ISSUE THREAD

**Issue by fzzr-** [haxenme/nme#182]
Trying to build any sample (or empty) project:
````
$ nme build iosview
Error: export/ios-view/haxe/cpp/FrameworkInterface.mm does not appear to be under export/ios-view/NodexNative/
````

But if i downgrade nme:
````
$ haxelib set nme 5.1.8
Library nme current version is now 5.1.8
$ nme build iosview
````
- all compiled completely.

**Comment by thomasuster** [comment]
Hey Fzzr, I tried 
nme build iosview
on nme master. I don't know what this is, but it compiles just fine. The SHA I tested on is ef3656f54212a93b26e210c4768761eae099ae8b

**Comment by hughsando** [comment]
Yes, this should be fixed.

**Comment by fzzr-** [comment]
Thx!
