### ISSUE TITLE
bitmapdata.copyChannel/draw random crashes

### ISSUE THREAD

**Issue by grisevg** [haxenme/nme#184]
Hi,

I've managed to isolate crashes caused by `bitmapdata.copyChannel` though sometimes it crashes on `bitmapdata.draw`.
Here's the example: http://pastie.org/9840281
This application would cut hole in the image on stage on mouse click.
Crashes are very random, but they usually don't happen when you erase circle in top right corner, but then do almost always happen when you do it in the centre or bottom right.

Try clicking multiple times if it doesn't crash the first time.

**Comment by grisevg** [comment]
Wow that was fast. Thank you very much.

**Comment by hughsando** [comment]
You got me at a good time - while was up to my armpits in the code.  Don't get used to it :)

**Comment by thomasuster** [comment]
Oof, sample has bug in it.

http://pastie.org/9840281

var intbounds = new Rectangle(bounds.x.round(), bounds.x.round(), bounds.x.ceil(), bounds.height.ceil());

Should have bounds.y in 2nd param
