### ISSUE TITLE
 Class not found : flash.filesystem.File

### ISSUE THREAD

**Issue by alamboley** [haxenme/nme#186]
Hey, I'm trying to compile a project made several years ago... on the latest version of NME.

I get an error:
```/usr/lib/haxe/lib/nme/5,2,13/nme/filesystem/File.hx:96: characters 0-14 : Class not found : flash.filesystem.File```
The line is : `typedef File = flash.filesystem.File;`
If I comment it, the compilation process continues (I've other errors on my project to manage...).

What might be the issue?

**Comment by thomasuster** [comment]
Hi Alambooley, try nme.filesystem.File.

**Comment by alamboley** [comment]
Thanks!
