### ISSUE TITLE
IOS sqlite can't compile

### ISSUE THREAD

**Issue by codeservice** [haxenme/nme#188]
I have nmml file with &lt;ndll name="sqlite3" haxelib="sqlite"/> sqlite library version 1.09
Works ok with mac,win,neko. Can't compile on IOS
Error message:
ApplicationMain.hx
Error:(10, 7) Class not found : sqlite.StaticSqlite3

Generated code in ApplicationMain.hx
...
#if cpp
import nme.StaticNme;
import sqlite.StaticSqlite3;//not found
import hxcpp.StaticStd;
import hxcpp.StaticZlib;
import hxcpp.StaticRegexp;

#end
...

**Comment by codeservice** [comment]
Using &lt;haxelib name="sqlite"/> instead of &lt;ndll name="sqlite3" haxelib="sqlite"/> fixing problem. Not sure if its bug or &lt;ndll not supported

**Comment by hughsando** [comment]
If you use ```<haxelib name="sqlite"``` or ```<haxelib ndll="sqlite"``` then the nme tool will automatically remap it to the hxcpp library, which is where is it actually implemented.  However, if you do *both* then it assumes you have gone to the trouble of specifying an alternate library you want to use.
Is this how it is supposed to work in openfl?  I could simply always remap the hxcpp libraries.
The basic idea in nme is to use ```<haxelib name=""/>``` which will just work all the time.  If you really want to speficy that the haxelib should have the appropriate binary ndll, use ```<ndll name=""/>```, which is the same as haxelib, but with additional checks.

**Comment by codeservice** [comment]
In nme samples I can see some time Ndll some time haxelib tag. Ndll with haxelib was fine on Mac and windows but broken with iOS on current nme version. Old nme was fine with Ndll and haxelib on all platforms. Maybe would be great to use only one, haxelib for example and mark Ndll as deprecated with warning message at compiling time. Avoid confusion some how.
