### ISSUE TITLE
nmml haxelib sqlite ios target problem

### ISSUE THREAD

**Issue by codeservice** [haxenme/nme#191]
nmml haxelib not working for sqlite ios target
Project compiled but fail at run time with message:
Primitive not found : sqlite_connect__1
Primitive not found : sqlite_close__1
Primitive not found : sqlite_request__2
Primitive not found : sqlite_last_insert_id__1
Primitive not found : sqlite_result_next__1
Primitive not found : sqlite_result_get_length__1
Primitive not found : sqlite_result_get_nfields__1
Primitive not found : sqlite_result_get__2
Primitive not found : sqlite_result_get_int__2
Primitive not found : sqlite_result_get_float__2

I am using sqlite 1,0,9
/usr/lib/haxe/lib/sqlite/1,0,9/lib/iPhone/libsqlite3.iphoneos-64.a
/usr/lib/haxe/lib/sqlite/1,0,9/lib/iPhone/libsqlite3.iphoneos-v7.a
/usr/lib/haxe/lib/sqlite/1,0,9/lib/iPhone/libsqlite3.iphoneos-v7s.a
/usr/lib/haxe/lib/sqlite/1,0,9/lib/iPhone/libsqlite3.iphoneos.a
/usr/lib/haxe/lib/sqlite/1,0,9/lib/iPhone/libsqlite3.iphonesim-64.a
/usr/lib/haxe/lib/sqlite/1,0,9/lib/iPhone/libsqlite3.iphonesim.a

**Comment by codeservice** [comment]
addLib function from NMEProject.hx assuming if haxelibName empty then use hxcpp version of this library.
So to prevent this I need to use haxelib declaration like this: <haxelib name="sqlite" haxelib="sqlite" static="true"/> Correct? Its really confusing library including mechanism.

NMEProject.hx:
.....
   public function addLib(name:String,type:String,haxelibName:String="", version:String="",?inStatic:Null<Bool>)
.....
         if (haxelibName == "")
         {
            if ( (name == "std" || name == "regexp" || name == "zlib" ||
                 name=="sqlite" || name=="mysql5" )) 
               haxelibName = "hxcpp";
            else
               haxelibName = name;
         }

**Comment by codeservice** [comment]
To make it sqlite static I need StaticSqlite3.hx file for sqlite 1.09.  Works for me now. Issue related to sqlite library.

package sqlite;

@:cppFileCode( 'extern "C" void sqlite3_register_prims();')
@:buildXml("
&lt;target id='haxe'>
  &lt;lib name='${haxelib:sqlite}/lib/${BINDIR}/libsqlite3{MSVC_VER}${LIBEXTRA}${LIBEXT}'/>
&lt;/target>
")
@:keep class StaticSqlite3
{
   static function __init__()
   {
     untyped __cpp__("sqlite3_register_prims();");
   }
}

**Comment by hughsando** [comment]
I guess there could be some confusion with the sqlite that is built into hxcpp, but I'm glad you have a solution that works for you.
