### ISSUE TITLE
Android simulator (x86 on windows) not rendering Bitmaps

### ISSUE THREAD

**Issue by codeservice** [haxenme/nme#196]
Checking android simulator http://www.andyroid.net/ (android 4.4.3 on windows x86)
I can see texts and vector graphics but bitmaps not rendering on android simulator
Same code works on Nexus 7 device (android 5.0.2)

**Comment by thomasuster** [comment]
Hey @codeservice. What benefits would fixing this give you or other developers? Is it possible this is a bug on there side and something we should file with them?

**Comment by codeservice** [comment]
This bug also repeatable on another simulator http://www.bluestacks.com/ on Mac OS, didn't check on windows. Bluestacks claim they have 90 million users. I have suspicious this bug also can be reproduced on some non simulator android versions. Would be good idea to check what is going on.

**Comment by hughsando** [comment]
Sound s a bit like an opengl compatible thing - maybe non-power-of-2 textures are some supported with some windows graphics drivers.  But you say it happens on mac, which makes this less likely.
My next guess would be BGR vs RGB textures, which is more likely when you consider that text is working, but not images.  Text uses bitmap, just not BGR ones.  I have bluestack on my other pc, so I can check it out.

**Comment by codeservice** [comment]
Strangely I can't see text on bluestacks (Mac) and can on Andy simulator
(Windows). It could be problem of non-power of 2 or not just one problem.
http://stackoverflow.com/questions/8688980/android-opengl2-0-showing-black-textures
Maybe something else. On google search found many cases why it could
happend:
https://www.google.ca/webhp?sourceid=chrome-instant&ion=1&espv=2&ie=UTF-8#q=android+black+open+GL+textures
On some devices for example blending can be a problem, alpha can often cause
a headache as well:
http://stackoverflow.com/questions/20710027/android-opengl-es-2-0-black-textures-on-some-devices

**Comment by hughsando** [comment]
I think I have fixed this - I upgraded bluestack halfway though the fix, and I think they may have fixed the issue too.

**Comment by codeservice** [comment]
Tested BlueStacks on Windows. It works! Thanks!
