### ISSUE TITLE
bitmapdata.copyChannel creates artefacts

### ISSUE THREAD

**Issue by grisevg** [haxenme/nme#200]
Copy channel method creates artefacts when used on images with alpha.
NME version: 5.3.1
Haxe version: 3.1.3
Reproduced on windows and neko-windows targets.

![image](https://cloud.githubusercontent.com/assets/155348/6686159/bbbab5d4-cc97-11e4-8ca0-49e23270fcbe.png)

Here's the code to reproduce the problem. Just add image with good amount of alpha in it and start clicking on a boundaries of alpha.
Here's the image I used: http://i.imgur.com/Cni98ht.png
```
using Math;

class Main extends Sprite {

	var canvas:BitmapData;

	public function new()
	{
		super();

		//Add image to stage
		var tmp = new Bitmap(Assets.getBitmapData("assets/image_with_alpha.png"));
		addChild(tmp);
		canvas = tmp.bitmapData;

		addEventListener(MouseEvent.CLICK, cutCircle);
	}

	function cutCircle(e:MouseEvent):Void
	{
		//Pick mouse X and Y
		var targetX = mouseX;
		var targetY = mouseY;

		//Bounds around the mouse
		var bounds = new Rectangle(mouseX, mouseY);
		bounds.inflate(50, 50);

		//temporary holder
		var tmp = new BitmapData(Math.ceil(bounds.width), Math.ceil(bounds.height), false, 0xFFFFFF);

		//NOTE: Expected behaviour - nothign should change at all, as we just copy pixels forth and back.
		//Copy pixel data around mouse from canvas ALPHA to tmp RED
		tmp.copyChannel(canvas, bounds, new Point(), BitmapDataChannel.ALPHA, BitmapDataChannel.RED);
		//Copy back same pixels from tmp RED to canvas ALPHA
		canvas.copyChannel(tmp, tmp.rect, bounds.topLeft, BitmapDataChannel.RED, BitmapDataChannel.ALPHA);
		
		//Cleanup
		tmp.dispose();
	}
}
```

**Comment by thomasuster** [comment]
Does it do anything different if inTransparent:Bool=true for your new BitmapData?

**Comment by thomasuster** [comment]
Hey @grisevg . If you put this in a repo so I can git clone and build I'm happy to take a look. mouseX not defined when I just copy pasted. I could fill in the blank here, but this way there's no way we can't be on the same page.

**Comment by grisevg** [comment]
Hey Thomas,

Thank you for looking at this.
Here is the zip with the project: https://drive.google.com/file/d/0B26lv1Dw4KRHN1V6dTZ6ZERDcjg/view?usp=sharing
Build with `haxelib run nme test neko` or `haxelib run nme test windows`

**Comment by thomasuster** [comment]
Hey @grisevg . I think you forgot to change the destPoint to a value other than 0,0.
See your example working here.
https://github.com/thomasuster/nme_200
Does that solve your use-case? If so please close the issue. If you need a 2nd look at something in the future let me know. @thomasuster on twitter

**Comment by thomasuster** [comment]
Does this branch fix your issue?

https://github.com/thomasuster/NME/tree/copyChannel

**Comment by thomasuster** [comment]
@grisevg bump

**Comment by grisevg** [comment]
Yes, that fixed it! Thank you!

**Comment by thomasuster** [comment]
https://github.com/haxenme/nme/pull/220
