### ISSUE TITLE
Sound.length seems to always return 0 on OSX

### ISSUE THREAD

**Issue by jskuse** [haxenme/nme#224]
Inspired by your blog post, I thought I'd have a go at running our project using NME rather than OpenFL, and for the most part I'm happy to say it was straightforward to get building (beyond a couple of missing methods on Matrix which I quickly patched in). 

However at runtime I'm running into an issue on the OSX build where while our (OGG format) sounds play, their length property always seems to be 0, which in turn breaks a lot of our cutscenes / scripted events. 

I wondered if perhaps it was loading asynchronously or something, resulting in that info not being immediately available, however, I did try adding a Event.COMPLETE listener to the sound and that didn't seem to yield any results either.

**Comment by hughsando** [comment]
It looks like this code has been disabled for some reason - I'll see if it can be fixed.

**Comment by jskuse** [comment]
That would be great if you could Hugh, I'm very keen to give NME a go.

**Comment by hughsando** [comment]
I have put a fix in for ogg music length - still need a better solution for wav/midi, but hopefully this will do for now.  Try 5.4.6 from http://nmehost.com/nme/ and see if this fixes your problem.
The Complete event should be working, although I did tweak the code recently.

**Comment by jskuse** [comment]
Hi Hugh, I've just got around to downloading and trying this out and I can
confirm that it's working great - thanks so much for the fix. I can now
carry on with benchmarking and comparing the various options.

On 27 June 2015 at 03:45, Hugh Sanderson <notifications@github.com> wrote:

> I have put a fix in for ogg music length - still need a better solution
> for wav/midi, but hopefully this will do for now. Try 5.4.6 from
> http://nmehost.com/nme/ and see if this fixes your problem.
> The Complete event should be working, although I did tweak the code
> recently.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/haxenme/nme/issues/224#issuecomment-115942170>.
>



-- 
Jonathan Skuse
Co-founder, Popleaf

Popleaf Ltd is a company registered in England and Wales. Registered
number: 09069427. Registered office: 115C Milton Road, Cambridge, United
Kingdom, CB4 1XE
