### ISSUE TITLE
HaxeFlixel: NME isn't compatible with its dev branch

### ISSUE THREAD

**Issue by sruloart** [haxenme/nme#226]
I'm trying to use the completely magical Acadnme with HaxeFlixel, but NME currently doesn't support the HaxeFlixel dev branch. Here are some random errors with one of the new demos:

C:\Projects\DynamicShadows>nme test flash
C:\HaxeToolkit\haxe\lib\flixel\flixelsand\flixel/graphics/tile/FlxTilesheet.hx:5
: lines 5-11 : Type not found : Tilesheet
export/flash/haxe/ApplicationMain.hx:25: lines 25-230 : Defined in this class
export/flash/haxe/ApplicationMain.hx:79: characters 45-48 : Int should be Null<A
rray<String>>
export/flash/haxe/ApplicationMain.hx:79: characters 45-48 : Int should be Array<
String>
export/flash/haxe/ApplicationMain.hx:79: characters 45-48 : For optional functio
n argument 'AllowedURLs'
C:\HaxeToolkit\haxe\lib\flixel\flixelsand\flixel/system/FlxAssets.hx:169: charac
ters 6-19 : Class<nme.Assets> has no field exists
C:\HaxeToolkit\haxe\lib\flixel\flixelsand\flixel/graphics/frames/FlxAtlasFrames.
hx:369: characters 6-19 : Class<nme.Assets> has no field exists
C:\HaxeToolkit\haxe\lib\flixel\flixelsand\flixel/graphics/frames/FlxAtlasFrames.
hx:46: characters 6-19 : Class<nme.Assets> has no field exists
C:\HaxeToolkit\haxe\lib\flixel\flixelsand\flixel/graphics/frames/FlxAtlasFrames.
hx:124: characters 6-19 : Class<nme.Assets> has no field exists
C:\HaxeToolkit\haxe\lib\flixel\flixelsand\flixel/graphics/frames/FlxAtlasFrames.
hx:238: characters 6-19 : Class<nme.Assets> has no field exists
C:\HaxeToolkit\haxe\lib\flixel\flixelsand\flixel/graphics/frames/FlxAtlasFrames.
hx:309: characters 6-19 : Class<nme.Assets> has no field exists
C:\HaxeToolkit\haxe\lib\flixel\flixelsand\flixel/graphics/tile/FlxDrawBaseItem.h
x:18: characters 10-19 : Unknown identifier : Tilesheet
C:\HaxeToolkit\haxe\lib\flixel\flixelsand\flixel/graphics/tile/FlxDrawBaseItem.h
x:23: characters 4-13 : Unknown identifier : Tilesheet
C:\HaxeToolkit\haxe\lib\flixel\flixelsand\flixel/graphics/tile/FlxDrawBaseItem.h
x:33: characters 4-13 : Unknown identifier : Tilesheet
C:\HaxeToolkit\haxe\lib\flixel\flixelsand\flixel/system/FlxSound.hx:301: charact
ers 7-20 : Class<nme.Assets> has no field exists
C:\HaxeToolkit\haxe\lib\flixel\flixelsand\flixel/system/FlxSound.hx:302: charact
ers 4-17 : Class<nme.Assets> has no field exists
C:\HaxeToolkit\haxe\lib\flixel\flixelsand\flixel/system/frontEnds/SoundFrontEnd.
hx:139: characters 6-19 : Class<nme.Assets> has no field exists
C:\HaxeToolkit\haxe\lib\flixel\flixelsand\flixel/system/frontEnds/SoundFrontEnd.
hx:140: characters 3-16 : Class<nme.Assets> has no field exists
C:\HaxeToolkit\haxe\lib\flixel\flixelsand\flixel/system/frontEnds/BitmapFrontEnd
.hx:423: characters 14-16 : Unknown identifier : GL
C:\HaxeToolkit\haxe\lib\flixel\flixelsand\flixel/system/frontEnds/BitmapFrontEnd
.hx:423: characters 30-32 : Unknown identifier : GL
C:\HaxeToolkit\haxe\lib\flixel\flixelsand\flixel/tile/FlxBaseTilemap.hx:171: cha
racters 6-19 : Class<nme.Assets> has no field exists
C:\HaxeToolkit\haxe\lib\flixel\flixelsand\flixel/FlxGame.hx:339: characters 2-25
 : Class<nme.Assets> has no field addEventListener
C:\HaxeToolkit\haxe\lib\flixel\flixelsand\flixel/text/FlxText.hx:571: characters
 7-20 : Class<nme.Assets> has no field exists

C:\Projects\DynamicShadows>nme test windows
        1 file(s) copied.
        1 file(s) copied.
        1 file(s) copied.
        1 file(s) copied.
        1 file(s) copied.
        1 file(s) copied.
        1 file(s) copied.
        1 file(s) copied.
        1 file(s) copied.
        1 file(s) copied.
        1 file(s) copied.
        1 file(s) copied.
C:\HaxeToolkit\haxe\lib\flixel\flixelsand\flixel/system/FlxAssets.hx:169: charac
ters 6-19 : Class<nme.Assets> has no field exists
C:\HaxeToolkit\haxe\lib\flixel\flixelsand\flixel/input/gamepad/FlxGamepadManager
.hx:373: characters 30-58 : Class<nme.events.JoystickEvent> has no field DEVICE_
REMOVED
C:\HaxeToolkit\haxe\lib\flixel\flixelsand\flixel/input/gamepad/FlxGamepadManager
.hx:374: characters 30-56 : Class<nme.events.JoystickEvent> has no field DEVICE_
ADDED
C:\HaxeToolkit\haxe\lib\flixel\flixelsand\flixel/system/FlxSound.hx:301: charact
ers 7-20 : Class<nme.Assets> has no field exists
C:\HaxeToolkit\haxe\lib\flixel\flixelsand\flixel/system/FlxSound.hx:302: charact
ers 4-17 : Class<nme.Assets> has no field exists
C:\HaxeToolkit\haxe\lib\flixel\flixelsand\flixel/graphics/tile/FlxDrawBaseItem.h
x:30: characters 4-33 : Class<nme.display.Tilesheet> has no field TILE_BLEND_SUB
TRACT
C:\HaxeToolkit\haxe\lib\flixel\flixelsand\flixel/FlxGame.hx:339: characters 2-25
 : Class<nme.Assets> has no field addEventListener
C:\HaxeToolkit\haxe\lib\flixel\flixelsand\flixel/tile/FlxBaseTilemap.hx:171: cha
racters 6-19 : Class<nme.Assets> has no field exists
C:\HaxeToolkit\haxe\lib\flixel\flixelsand\flixel/math/FlxMatrix.hx:63: character
s 2-12 : flixel.math.FlxMatrix has no field setTo
C:\HaxeToolkit\haxe\lib\flixel\flixelsand\flixel/math/FlxMatrix.hx:73: character
s 2-12 : flixel.math.FlxMatrix has no field setTo
C:\HaxeToolkit\haxe\lib\flixel\flixelsand\flixel/text/FlxText.hx:571: characters
 7-20 : Class<nme.Assets> has no field exists
C:\HaxeToolkit\haxe\lib\flixel\flixelsand\flixel/text/FlxText.hx:652: characters
 33-53 : String should be flixel.text._FlxText.AlignType
C:\HaxeToolkit\haxe\lib\flixel\flixelsand\flixel/text/FlxText.hx:652: characters
 33-53 : String should be flash.text.TextFormatAlign
C:\HaxeToolkit\haxe\lib\flixel\flixelsand\flixel/text/FlxText.hx:652: characters
 33-53 : String should be nme.text.TextFormatAlign
C:\HaxeToolkit\haxe\lib\flixel\flixelsand\flixel/text/FlxText.hx:652: characters
 33-53 : For function argument 'align'
C:\HaxeToolkit\haxe\lib\flixel\flixelsand\flixel/text/FlxText.hx:650: lines 650-
653 : Missing return flixel.text.FlxTextAlign
C:\HaxeToolkit\haxe\lib\flixel\flixelsand\flixel/text/FlxText.hx:1104: character
s 3-7 : String should be flixel.text._FlxText.AlignType
C:\HaxeToolkit\haxe\lib\flixel\flixelsand\flixel/text/FlxText.hx:1104: character
s 3-7 : String should be flash.text.TextFormatAlign
C:\HaxeToolkit\haxe\lib\flixel\flixelsand\flixel/text/FlxText.hx:1104: character
s 3-7 : String should be nme.text.TextFormatAlign
C:\HaxeToolkit\haxe\lib\flixel\flixelsand\flixel/text/FlxText.hx:1105: character
s 3-7 : String should be flixel.text._FlxText.AlignType
C:\HaxeToolkit\haxe\lib\flixel\flixelsand\flixel/text/FlxText.hx:1105: character
s 3-7 : String should be flash.text.TextFormatAlign
C:\HaxeToolkit\haxe\lib\flixel\flixelsand\flixel/text/FlxText.hx:1105: character
s 3-7 : String should be nme.text.TextFormatAlign
C:\HaxeToolkit\haxe\lib\flixel\flixelsand\flixel/text/FlxText.hx:1106: character
s 3-7 : String should be flixel.text._FlxText.AlignType
C:\HaxeToolkit\haxe\lib\flixel\flixelsand\flixel/text/FlxText.hx:1106: character
s 3-7 : String should be flash.text.TextFormatAlign
C:\HaxeToolkit\haxe\lib\flixel\flixelsand\flixel/text/FlxText.hx:1106: character
s 3-7 : String should be nme.text.TextFormatAlign
C:\HaxeToolkit\haxe\lib\flixel\flixelsand\flixel/text/FlxText.hx:1107: character
s 3-7 : String should be flixel.text._FlxText.AlignType
C:\HaxeToolkit\haxe\lib\flixel\flixelsand\flixel/text/FlxText.hx:1107: character
s 3-7 : String should be flash.text.TextFormatAlign
C:\HaxeToolkit\haxe\lib\flixel\flixelsand\flixel/text/FlxText.hx:1107: character
s 3-7 : String should be nme.text.TextFormatAlign
C:\HaxeToolkit\haxe\lib\flixel\flixelsand\flixel/text/FlxText.hx:1108: character
s 3-10 : String should be flixel.text._FlxText.AlignType
C:\HaxeToolkit\haxe\lib\flixel\flixelsand\flixel/text/FlxText.hx:1108: character
s 3-10 : String should be flash.text.TextFormatAlign
C:\HaxeToolkit\haxe\lib\flixel\flixelsand\flixel/text/FlxText.hx:1108: character
s 3-10 : String should be nme.text.TextFormatAlign
C:\HaxeToolkit\haxe\lib\flixel\flixelsand\flixel/text/FlxText.hx:657: characters
 2-57 : flixel.text._FlxText.AlignType should be String
C:\HaxeToolkit\haxe\lib\flixel\flixelsand\flixel/text/FlxText.hx:657: characters
 2-57 : flash.text.TextFormatAlign should be String
C:\HaxeToolkit\haxe\lib\flixel\flixelsand\flixel/text/FlxText.hx:657: characters
 2-57 : nme.text.TextFormatAlign should be String
C:\HaxeToolkit\haxe\lib\flixel\flixelsand\flixel/math/FlxMatrix.hx:53: character
s 2-12 : flixel.math.FlxMatrix has no field setTo
C:\HaxeToolkit\haxe\lib\flixel\flixelsand\flixel/graphics/frames/FlxAtlasFrames.
hx:369: characters 6-19 : Class<nme.Assets> has no field exists
C:\HaxeToolkit\haxe\lib\flixel\flixelsand\flixel/graphics/frames/FlxAtlasFrames.
hx:46: characters 6-19 : Class<nme.Assets> has no field exists
C:\HaxeToolkit\haxe\lib\flixel\flixelsand\flixel/graphics/frames/FlxAtlasFrames.
hx:124: characters 6-19 : Class<nme.Assets> has no field exists
C:\HaxeToolkit\haxe\lib\flixel\flixelsand\flixel/graphics/frames/FlxAtlasFrames.
hx:238: characters 6-19 : Class<nme.Assets> has no field exists
C:\HaxeToolkit\haxe\lib\flixel\flixelsand\flixel/graphics/frames/FlxAtlasFrames.
hx:309: characters 6-19 : Class<nme.Assets> has no field exists
C:\HaxeToolkit\haxe\lib\flixel\flixelsand\flixel/system/frontEnds/SoundFrontEnd.
hx:139: characters 6-19 : Class<nme.Assets> has no field exists
C:\HaxeToolkit\haxe\lib\flixel\flixelsand\flixel/system/frontEnds/SoundFrontEnd.
hx:140: characters 3-16 : Class<nme.Assets> has no field exists

C:\Projects\DynamicShadows>nme test neko
        1 file(s) copied.
        1 file(s) copied.
        1 file(s) copied.
        1 file(s) copied.
        1 file(s) copied.
        1 file(s) copied.
        1 file(s) copied.
        1 file(s) copied.
        1 file(s) copied.
        1 file(s) copied.
        1 file(s) copied.
        1 file(s) copied.
C:\HaxeToolkit\haxe\lib\flixel\flixelsand\flixel/system/FlxAssets.hx:169: charac
ters 6-19 : Class<nme.Assets> has no field exists
C:\HaxeToolkit\haxe\lib\flixel\flixelsand\flixel/input/gamepad/FlxGamepadManager
.hx:373: characters 30-58 : Class<nme.events.JoystickEvent> has no field DEVICE_
REMOVED
C:\HaxeToolkit\haxe\lib\flixel\flixelsand\flixel/input/gamepad/FlxGamepadManager
.hx:374: characters 30-56 : Class<nme.events.JoystickEvent> has no field DEVICE_
ADDED
C:\HaxeToolkit\haxe\lib\flixel\flixelsand\flixel/system/FlxSound.hx:301: charact
ers 7-20 : Class<nme.Assets> has no field exists
C:\HaxeToolkit\haxe\lib\flixel\flixelsand\flixel/system/FlxSound.hx:302: charact
ers 4-17 : Class<nme.Assets> has no field exists
C:\HaxeToolkit\haxe\lib\flixel\flixelsand\flixel/graphics/tile/FlxDrawBaseItem.h
x:30: characters 4-33 : Class<nme.display.Tilesheet> has no field TILE_BLEND_SUB
TRACT
C:\HaxeToolkit\haxe\lib\flixel\flixelsand\flixel/FlxGame.hx:339: characters 2-25
 : Class<nme.Assets> has no field addEventListener
C:\HaxeToolkit\haxe\lib\flixel\flixelsand\flixel/tile/FlxBaseTilemap.hx:171: cha
racters 6-19 : Class<nme.Assets> has no field exists
C:\HaxeToolkit\haxe\lib\flixel\flixelsand\flixel/math/FlxMatrix.hx:63: character
s 2-12 : flixel.math.FlxMatrix has no field setTo
C:\HaxeToolkit\haxe\lib\flixel\flixelsand\flixel/math/FlxMatrix.hx:73: character
s 2-12 : flixel.math.FlxMatrix has no field setTo
C:\HaxeToolkit\haxe\lib\flixel\flixelsand\flixel/text/FlxText.hx:571: characters
 7-20 : Class<nme.Assets> has no field exists
C:\HaxeToolkit\haxe\lib\flixel\flixelsand\flixel/text/FlxText.hx:652: characters
 33-53 : String should be flixel.text._FlxText.AlignType
C:\HaxeToolkit\haxe\lib\flixel\flixelsand\flixel/text/FlxText.hx:652: characters
 33-53 : String should be flash.text.TextFormatAlign
C:\HaxeToolkit\haxe\lib\flixel\flixelsand\flixel/text/FlxText.hx:652: characters
 33-53 : String should be nme.text.TextFormatAlign
C:\HaxeToolkit\haxe\lib\flixel\flixelsand\flixel/text/FlxText.hx:652: characters
 33-53 : For function argument 'align'
C:\HaxeToolkit\haxe\lib\flixel\flixelsand\flixel/text/FlxText.hx:650: lines 650-
653 : Missing return flixel.text.FlxTextAlign
C:\HaxeToolkit\haxe\lib\flixel\flixelsand\flixel/text/FlxText.hx:1104: character
s 3-7 : String should be flixel.text._FlxText.AlignType
C:\HaxeToolkit\haxe\lib\flixel\flixelsand\flixel/text/FlxText.hx:1104: character
s 3-7 : String should be flash.text.TextFormatAlign
C:\HaxeToolkit\haxe\lib\flixel\flixelsand\flixel/text/FlxText.hx:1104: character
s 3-7 : String should be nme.text.TextFormatAlign
C:\HaxeToolkit\haxe\lib\flixel\flixelsand\flixel/text/FlxText.hx:1105: character
s 3-7 : String should be flixel.text._FlxText.AlignType
C:\HaxeToolkit\haxe\lib\flixel\flixelsand\flixel/text/FlxText.hx:1105: character
s 3-7 : String should be flash.text.TextFormatAlign
C:\HaxeToolkit\haxe\lib\flixel\flixelsand\flixel/text/FlxText.hx:1105: character
s 3-7 : String should be nme.text.TextFormatAlign
C:\HaxeToolkit\haxe\lib\flixel\flixelsand\flixel/text/FlxText.hx:1106: character
s 3-7 : String should be flixel.text._FlxText.AlignType
C:\HaxeToolkit\haxe\lib\flixel\flixelsand\flixel/text/FlxText.hx:1106: character
s 3-7 : String should be flash.text.TextFormatAlign
C:\HaxeToolkit\haxe\lib\flixel\flixelsand\flixel/text/FlxText.hx:1106: character
s 3-7 : String should be nme.text.TextFormatAlign
C:\HaxeToolkit\haxe\lib\flixel\flixelsand\flixel/text/FlxText.hx:1107: character
s 3-7 : String should be flixel.text._FlxText.AlignType
C:\HaxeToolkit\haxe\lib\flixel\flixelsand\flixel/text/FlxText.hx:1107: character
s 3-7 : String should be flash.text.TextFormatAlign
C:\HaxeToolkit\haxe\lib\flixel\flixelsand\flixel/text/FlxText.hx:1107: character
s 3-7 : String should be nme.text.TextFormatAlign
C:\HaxeToolkit\haxe\lib\flixel\flixelsand\flixel/text/FlxText.hx:1108: character
s 3-10 : String should be flixel.text._FlxText.AlignType
C:\HaxeToolkit\haxe\lib\flixel\flixelsand\flixel/text/FlxText.hx:1108: character
s 3-10 : String should be flash.text.TextFormatAlign
C:\HaxeToolkit\haxe\lib\flixel\flixelsand\flixel/text/FlxText.hx:1108: character
s 3-10 : String should be nme.text.TextFormatAlign
C:\HaxeToolkit\haxe\lib\flixel\flixelsand\flixel/text/FlxText.hx:657: characters
 2-57 : flixel.text._FlxText.AlignType should be String
C:\HaxeToolkit\haxe\lib\flixel\flixelsand\flixel/text/FlxText.hx:657: characters
 2-57 : flash.text.TextFormatAlign should be String
C:\HaxeToolkit\haxe\lib\flixel\flixelsand\flixel/text/FlxText.hx:657: characters
 2-57 : nme.text.TextFormatAlign should be String
C:\HaxeToolkit\haxe\lib\flixel\flixelsand\flixel/math/FlxMatrix.hx:53: character
s 2-12 : flixel.math.FlxMatrix has no field setTo
C:\HaxeToolkit\haxe\lib\flixel\flixelsand\flixel/graphics/frames/FlxAtlasFrames.
hx:369: characters 6-19 : Class<nme.Assets> has no field exists
C:\HaxeToolkit\haxe\lib\flixel\flixelsand\flixel/graphics/frames/FlxAtlasFrames.
hx:46: characters 6-19 : Class<nme.Assets> has no field exists
C:\HaxeToolkit\haxe\lib\flixel\flixelsand\flixel/graphics/frames/FlxAtlasFrames.
hx:124: characters 6-19 : Class<nme.Assets> has no field exists
C:\HaxeToolkit\haxe\lib\flixel\flixelsand\flixel/graphics/frames/FlxAtlasFrames.
hx:238: characters 6-19 : Class<nme.Assets> has no field exists
C:\HaxeToolkit\haxe\lib\flixel\flixelsand\flixel/graphics/frames/FlxAtlasFrames.
hx:309: characters 6-19 : Class<nme.Assets> has no field exists
C:\HaxeToolkit\haxe\lib\flixel\flixelsand\flixel/system/frontEnds/SoundFrontEnd.
hx:139: characters 6-19 : Class<nme.Assets> has no field exists
C:\HaxeToolkit\haxe\lib\flixel\flixelsand\flixel/system/frontEnds/SoundFrontEnd.
hx:140: characters 3-16 : Class<nme.Assets> has no field exists

C:\Projects\DynamicShadows>nme test android
        1 file(s) copied.
        1 file(s) copied.
        1 file(s) copied.
        1 file(s) copied.
        1 file(s) copied.
        1 file(s) copied.
        1 file(s) copied.
        1 file(s) copied.
        1 file(s) copied.
        1 file(s) copied.
        1 file(s) copied.
        1 file(s) copied.
        1 file(s) copied.
C:\HaxeToolkit\haxe\lib\flixel\flixelsand\flixel/system/FlxAssets.hx:169: charac
ters 6-19 : Class<nme.Assets> has no field exists
C:\HaxeToolkit\haxe\lib\flixel\flixelsand\flixel/input/gamepad/FlxGamepadManager
.hx:373: characters 30-58 : Class<nme.events.JoystickEvent> has no field DEVICE_
REMOVED
C:\HaxeToolkit\haxe\lib\flixel\flixelsand\flixel/input/gamepad/FlxGamepadManager
.hx:374: characters 30-56 : Class<nme.events.JoystickEvent> has no field DEVICE_
ADDED
C:\HaxeToolkit\haxe\lib\flixel\flixelsand\flixel/system/FlxSound.hx:301: charact
ers 7-20 : Class<nme.Assets> has no field exists
C:\HaxeToolkit\haxe\lib\flixel\flixelsand\flixel/system/FlxSound.hx:302: charact
ers 4-17 : Class<nme.Assets> has no field exists
C:\HaxeToolkit\haxe\lib\flixel\flixelsand\flixel/graphics/tile/FlxDrawBaseItem.h
x:30: characters 4-33 : Class<nme.display.Tilesheet> has no field TILE_BLEND_SUB
TRACT
C:\HaxeToolkit\haxe\lib\flixel\flixelsand\flixel/FlxGame.hx:339: characters 2-25
 : Class<nme.Assets> has no field addEventListener
C:\HaxeToolkit\haxe\lib\flixel\flixelsand\flixel/tile/FlxBaseTilemap.hx:171: cha
racters 6-19 : Class<nme.Assets> has no field exists
C:\HaxeToolkit\haxe\lib\flixel\flixelsand\flixel/math/FlxMatrix.hx:63: character
s 2-12 : flixel.math.FlxMatrix has no field setTo
C:\HaxeToolkit\haxe\lib\flixel\flixelsand\flixel/math/FlxMatrix.hx:73: character
s 2-12 : flixel.math.FlxMatrix has no field setTo
C:\HaxeToolkit\haxe\lib\flixel\flixelsand\flixel/text/FlxText.hx:571: characters
 7-20 : Class<nme.Assets> has no field exists
C:\HaxeToolkit\haxe\lib\flixel\flixelsand\flixel/text/FlxText.hx:652: characters
 33-53 : String should be flixel.text._FlxText.AlignType
C:\HaxeToolkit\haxe\lib\flixel\flixelsand\flixel/text/FlxText.hx:652: characters
 33-53 : String should be flash.text.TextFormatAlign
C:\HaxeToolkit\haxe\lib\flixel\flixelsand\flixel/text/FlxText.hx:652: characters
 33-53 : String should be nme.text.TextFormatAlign
C:\HaxeToolkit\haxe\lib\flixel\flixelsand\flixel/text/FlxText.hx:652: characters
 33-53 : For function argument 'align'
C:\HaxeToolkit\haxe\lib\flixel\flixelsand\flixel/text/FlxText.hx:650: lines 650-
653 : Missing return flixel.text.FlxTextAlign
C:\HaxeToolkit\haxe\lib\flixel\flixelsand\flixel/text/FlxText.hx:1104: character
s 3-7 : String should be flixel.text._FlxText.AlignType
C:\HaxeToolkit\haxe\lib\flixel\flixelsand\flixel/text/FlxText.hx:1104: character
s 3-7 : String should be flash.text.TextFormatAlign
C:\HaxeToolkit\haxe\lib\flixel\flixelsand\flixel/text/FlxText.hx:1104: character
s 3-7 : String should be nme.text.TextFormatAlign
C:\HaxeToolkit\haxe\lib\flixel\flixelsand\flixel/text/FlxText.hx:1105: character
s 3-7 : String should be flixel.text._FlxText.AlignType
C:\HaxeToolkit\haxe\lib\flixel\flixelsand\flixel/text/FlxText.hx:1105: character
s 3-7 : String should be flash.text.TextFormatAlign
C:\HaxeToolkit\haxe\lib\flixel\flixelsand\flixel/text/FlxText.hx:1105: character
s 3-7 : String should be nme.text.TextFormatAlign
C:\HaxeToolkit\haxe\lib\flixel\flixelsand\flixel/text/FlxText.hx:1106: character
s 3-7 : String should be flixel.text._FlxText.AlignType
C:\HaxeToolkit\haxe\lib\flixel\flixelsand\flixel/text/FlxText.hx:1106: character
s 3-7 : String should be flash.text.TextFormatAlign
C:\HaxeToolkit\haxe\lib\flixel\flixelsand\flixel/text/FlxText.hx:1106: character
s 3-7 : String should be nme.text.TextFormatAlign
C:\HaxeToolkit\haxe\lib\flixel\flixelsand\flixel/text/FlxText.hx:1107: character
s 3-7 : String should be flixel.text._FlxText.AlignType
C:\HaxeToolkit\haxe\lib\flixel\flixelsand\flixel/text/FlxText.hx:1107: character
s 3-7 : String should be flash.text.TextFormatAlign
C:\HaxeToolkit\haxe\lib\flixel\flixelsand\flixel/text/FlxText.hx:1107: character
s 3-7 : String should be nme.text.TextFormatAlign
C:\HaxeToolkit\haxe\lib\flixel\flixelsand\flixel/text/FlxText.hx:1108: character
s 3-10 : String should be flixel.text._FlxText.AlignType
C:\HaxeToolkit\haxe\lib\flixel\flixelsand\flixel/text/FlxText.hx:1108: character
s 3-10 : String should be flash.text.TextFormatAlign
C:\HaxeToolkit\haxe\lib\flixel\flixelsand\flixel/text/FlxText.hx:1108: character
s 3-10 : String should be nme.text.TextFormatAlign
C:\HaxeToolkit\haxe\lib\flixel\flixelsand\flixel/text/FlxText.hx:657: characters
 2-57 : flixel.text._FlxText.AlignType should be String
C:\HaxeToolkit\haxe\lib\flixel\flixelsand\flixel/text/FlxText.hx:657: characters
 2-57 : flash.text.TextFormatAlign should be String
C:\HaxeToolkit\haxe\lib\flixel\flixelsand\flixel/text/FlxText.hx:657: characters
 2-57 : nme.text.TextFormatAlign should be String
C:\HaxeToolkit\haxe\lib\flixel\flixelsand\flixel/math/FlxMatrix.hx:53: character
s 2-12 : flixel.math.FlxMatrix has no field setTo
C:\HaxeToolkit\haxe\lib\flixel\flixelsand\flixel/graphics/frames/FlxAtlasFrames.
hx:369: characters 6-19 : Class<nme.Assets> has no field exists
C:\HaxeToolkit\haxe\lib\flixel\flixelsand\flixel/graphics/frames/FlxAtlasFrames.
hx:46: characters 6-19 : Class<nme.Assets> has no field exists
C:\HaxeToolkit\haxe\lib\flixel\flixelsand\flixel/graphics/frames/FlxAtlasFrames.
hx:124: characters 6-19 : Class<nme.Assets> has no field exists
C:\HaxeToolkit\haxe\lib\flixel\flixelsand\flixel/graphics/frames/FlxAtlasFrames.
hx:238: characters 6-19 : Class<nme.Assets> has no field exists
C:\HaxeToolkit\haxe\lib\flixel\flixelsand\flixel/graphics/frames/FlxAtlasFrames.
hx:309: characters 6-19 : Class<nme.Assets> has no field exists
C:\HaxeToolkit\haxe\lib\flixel\flixelsand\flixel/system/frontEnds/SoundFrontEnd.
hx:139: characters 6-19 : Class<nme.Assets> has no field exists
C:\HaxeToolkit\haxe\lib\flixel\flixelsand\flixel/system/frontEnds/SoundFrontEnd.
hx:140: characters 3-16 : Class<nme.Assets> has no field exists

**Comment by hughsando** [comment]
I've added some compatibility functions.  Not sure about the GL call in the flash target though - and there were a few issues with Enum vs String on flash that might need a bit of work.
Acadnme will need to be recompiled since it contains precompiled versions of the nme code, so I will need to get this done too.

**Comment by sruloart** [comment]
Thanks! the GL thingy is a HaxeFlixel bug of course :)

**Comment by hughsando** [comment]
Seems to be mostly working now.  You can reopen the issue if you are still having problems.

**Comment by sruloart** [comment]
It does work! :+1:
