### ISSUE TITLE
High CPU usage when using SampleDataEvent for Windows/Neko target?

### ISSUE THREAD

**Issue by gen111** [haxenme/nme#228]
Hi people. 

It seems like it uses a bit too much CPU when using SampleDataEvent for Windows/Neko target especially compared to flash target ( tested on 06-Sound and the following project and the former one used 16~20% and the latter one used 30% on Windows/Neko while both of them used almost 0% on Flash). And I don't think Flash is supposed to be more CPU friendly. My CPU is intel core i3-4130 3.40GHz. Please excuse my poor English :o

This is the project I tested with. 
http://www.tanjent.se/labs/tanjentxm.html

**Comment by thomasuster** [comment]
Hey @gen111 , Hugh has done a lot of work on the sounds lately. Is this still an issue for you?

**Comment by thomasuster** [comment]
stale
