### ISSUE TITLE
IOS - Project file cannot be parsed

### ISSUE THREAD

**Issue by hoseyjoe** [haxenme/nme#229]
I was able to compile my application in windows, neko, mac, android but it would not compile to IOS. It appears that the xcode project could not be parsed because there was a space in the file name

From project.xml
```<app main="blah.blah.com" file="My File" path="bin" />```

needs to be 

```<app main="blah.blah.com" file="MyFile" path="bin" />```

**Comment by hughsando** [comment]
Looks like you have hit on the answer - if only I could see it!
Looks like github has markeddown your example.  You can use tripple-back-tick (`) to quote code.

**Comment by hoseyjoe** [comment]
Sorry about that. FYI:  I am not 100% this is the issue.  I tried changing a number of things in the project.xml and one of them worked.  I believe this was the one.  I have to VNC into a mac mini at my brothers house so things are bit painful to test ios.

**Comment by thomasuster** [comment]
@hoseyjoe Why not just do...
```
mv "My File" MyFile
```
And be done with it? I've been avoiding spaces in file names for years.

**Comment by hoseyjoe** [comment]
I was using nme test project.xml ios
the project.xml defiines the name in an attribute.  Something like <app
name="My Name"/>  The space in the attribute was causing the issue.

**Comment by thomasuster** [comment]
This works for me.
```
<meta title="Pakka Pets"
```

**Comment by hoseyjoe** [comment]
It was only an issue when going to IOS, I believe.

**Comment by thomasuster** [comment]
fixed
