### ISSUE TITLE
IOS embedded font issue

### ISSUE THREAD

**Issue by hoseyjoe** [haxenme/nme#230]
Using a openfl project I am not getting embedded fonts when compiling to IOS device.

I get the fonts when compiling to Android, Windows, Mac, IOS Simulator.

I am using the openfl(?) Assets utility and I am applying the font with the textformat like
var textformat = new TextFormat ("ARIAL", 14, 0x000000);

**Comment by hoseyjoe** [comment]
Changing
var textformat = new TextFormat ("ARIAL", 14, 0x000000);
to
var textformat = new TextFormat (Assets.getFont ("ARIAL.TTF").fontName, 12, 0x7A0026);
fixed issue in IOS but breaks flash (for some reason, may be unrelated, reason)

**Comment by thomasuster** [comment]
@hoseyjoe Hey are you still having this issue?

**Comment by hoseyjoe** [comment]
No, I switched the way I was embedding.  I was using a more openfl way, now
I am using a more nme way (which works in both)

**Comment by thomasuster** [comment]
Awesome!
