### ISSUE TITLE
ios default font folder problem

### ISSUE THREAD

**Issue by codeservice** [haxenme/nme#239]
Can't find any default fonts sans or serif in 
/System/Library/Fonts/Cache/
for ios8.4

all listed below fonts not opening with cpp fopen function:
   const char *serifFonts[] = { "Georgia.ttf", "Times.ttf", "Times New Roman.ttf", 0 };
   const char *sansFonts[] = { "Arial Black.ttf", "Arial.ttf", "Helvetica.ttf", 0 };
   const char *fixedFonts[] = { "Courier New.ttf", "Courier.ttf", 0 };

**Comment by hughsando** [comment]
I see unity does something like:
```
"/System/Library/Fonts/Cache", // before iOS 8.2
 "/System/Library/Fonts/AppFonts", // iOS 8.2
 "/System/Library/Fonts/Core", // iOS 8.2
 "/System/Library/Fonts/Extra", // iOS 8.2
```
So don't think it will be too hard to fix

**Comment by codeservice** [comment]
Found it too: http://forum.unity3d.com/threads/missing-font-characters-on-ios-8-2.310028/
Ok, I'll check this
