### ISSUE TITLE
Drawtile in flash isn't available

### ISSUE THREAD

**Issue by hoseyjoe** [haxenme/nme#251]
Drawtile in flash isn't available.  It would be nice if there was a fallback.  Not the end of the world

**Comment by thomasuster** [comment]
@hoseyjoe Do you have a project that needs this? I can help out if so. The first step would be to figure out how to route it to an NME haxe class, as right now I think it will try to called drawTiles on the flash.display.Graphics.

**Comment by hoseyjoe** [comment]
No, not exactly. I have dabbled in a game for the last 2 years.  Sometimes in nme, sometimes in openfl.  I was capturing the issue more than anything else. I am tryng to be a little helpful, if not annoying :)

**Comment by thomasuster** [comment]
Ahh okay, because resources are thin let's push for issues people have active use cases on. Thanks hoseyjoe!
