### ISSUE TITLE
Default haxelib for ndll breaking change

### ISSUE THREAD

**Issue by thomasuster** [haxenme/nme#255]
This commit cab868a53b803659c386adf4b5ac83b19b71050b causes a break with an extension that I use.
https://github.com/sergey-miryanov/linden-flurry

Should we revert the default haxelib name? Otherwise I could submit a PR to linde-flurry to use dash for ndll name.

**Comment by thomasuster** [comment]
@sergey-miryanov Hey Sergey, would you mind if I sent a PR to just make the ndll use the same name as the lib? Then I can close this and it should work on latest NME.

**Comment by sergey-miryanov** [comment]
@thomasuster Feel free to send a PR :)

**Comment by thomasuster** [comment]
This can be closed if https://github.com/haxenme/nme/pull/268 is merged.
