### ISSUE TITLE
ByteArray.hx do not have writeObject and readObject method?

### ISSUE THREAD

**Issue by sonygod** [haxenme/nme#26]
ByteArray.hx do not have writeObject and readObject method?

because I want to sent bytearray from flash  to neko ,
I want to implement nme  ByteArray to  convert  bytes to Bytearray .
but nme  missing that method ...readObject ,writeObject
any help ?

**Comment by thomasuster** [comment]
Hey sonygod, does using haxe.io.Bytes handle your use case? I use that for a front-end to back-end communication.

**Comment by thomasuster** [comment]
stale
