### ISSUE TITLE
El Capitan depcrates Carbon Component Manager

### ISSUE THREAD

**Issue by thomasuster** [haxenme/nme#269]
WARNING:  140: This application, or a library it uses, is using the deprecated Carbon Component Manager for hosting Audio Units. Support for this will be removed in a future release. Also, this makes the host incompatible with version 3 audio units. Please transition to the API's in AudioComponent.h.

**Comment by thomasuster** [comment]
Looks like the best thing to do would be to wait for patch in regular rollout of SDL. Maybe 2.0.4.
https://bugzilla.libsdl.org/show_bug.cgi?id=3127

**Comment by hughsando** [comment]
Yes, It would be nice is someone else fixed it!

**Comment by thomasuster** [comment]
Looks like latest xcode actually removes this instead of just deprecation, so causes failure to build.

**Comment by thomasuster** [comment]
Tried giving this a go, not clear how SDL should be updated. SDL1? SDL2? And if so, how to apply the update. @hughsando I'm around tonight if you have time to give some guidance on this.

**Comment by hughsando** [comment]
We take the code from the nme branch on https://github.com/native-toolkit/sdl/tree/nme
and nme-toolkit uses submodules to take a version:
https://github.com/haxenme/nme-toolkit

To update, we could first update the native-toolkit repo, then point nme-toolkit at the new version, then rebuild nme-toolkit via  as script I have and haxelib submit it.

You can test your sdl changes by setting NATIVE_TOOLKIT_PATH to a directory containing your own git checkouts of the various libraries, including sdl.
