### ISSUE TITLE
--no-traces compile flag and android

### ISSUE THREAD

**Issue by polygonal** [haxenme/nme#27]
when adding <compilerflag name="--no-traces" /> to an .nmml file, compilation for android fails with error: ./src/neash/display/Stage.cpp:1060: error: 'haxe::Log_obj' has not been declared

see neash.display.Stage.hx line 352

**Comment by thomasuster** [comment]
Hey @polygonal Is this still an issue?

**Comment by thomasuster** [comment]
stale
