### ISSUE TITLE
IOS9 default fonts

### ISSUE THREAD

**Issue by codeservice** [haxenme/nme#270]
Looks like on IOS9 Apple again move fonts to different folder.
In IOS 8.2 it was /System/Library/Fonts/Core/
In IOS 9.1 its /System/Library/Fonts//CoreAddition

New fonts list on IOS 9 + AppleWatch found here:
http://www.9miao.com/thread-72013-1-1.html

Didnt check new folders yet, but I dont see _serif, _sans, _typewriter working with my test app.

New fonts list:
"/System/Library/Fonts/CoreAddition/", "/System/Library/Fonts/Core/", "/System/Library/Fonts/CoreUI/",
"/System/Library/Fonts/AppFonts/", "/System/Library/Fonts/LanguageSupport/", "/System/Library/Fonts/Watch/",
"/System/Library/Fonts/Extra/", "/System/Library/Fonts/Cache/"

and in addition need to add CourierNew.ttf, cant find "Courier New.ttf" or "Courier.ttf" on IOS
const char *fixedFonts[] = { "Courier New.ttf", "CourierNew.ttf", "Courier.ttf", 0 };

**Comment by thomasuster** [comment]
closed since PR was taken
