### ISSUE TITLE
Memory leak on graphics

### ISSUE THREAD

**Issue by codeservice** [haxenme/nme#272]
This kind of code works well on flash. NME version tested on android and app crashed with out of memory error.
graphics.clear() should clear all bitmaps associated only with this graphics. 

import flash.display.BitmapData;

var _w = 600;
var _h = 600;

addEventListener(Event.ENTER_FRAME, function(e) {
	graphics.clear();
	var bd: BitmapData = new BitmapData(_w, _h, true, 0x000000FF);
	
	graphics.beginBitmapFill(bd, null, false, false);
    graphics.drawRect(0, 0, _w, _h);
	graphics.endFill();
});

**Comment by thomasuster** [comment]
Is this for sure a leak or is GC just not running fast enough to free up memory?

**Comment by codeservice** [comment]
Flash clears bitmaps instantly inside graphics.clear(); When you run it, you can see how stable memory usage is. I don't know if nme should work the same way, but I think its preferable.
On android, app dead after only few seconds of running. How fast GC should run to clean it? Because its hard to predict GC timing strategy, and actually release memory instantly

**Comment by thomasuster** [comment]
Have you tried calling bd.dispose() after the fill?

**Comment by codeservice** [comment]
if bitmap filled on graphics I cant use dispose. shared memory issue.
I can use dispose only after graphics.clear(). Which means I need to
implement some kind of bitmap manger if I have many bitmaps for example.
And I have code already for this. I don't think its good idea increase
complexity of your code because system not work as it should. Fixing root
of the problem always better then work a round.

**Comment by hughsando** [comment]
Have you tried the version I released yesterday?
I fixed an issue like this.

**Comment by codeservice** [comment]
I have nme version from github. few small updates were missing.  hxcpp was little bit old 3,2,189. I updated it to 3,2,193. recompile everything and now I dont see leaking issue on mac and android. Didn't check windows yet. On android I can see strange behaviour for this code, FPS goes up and down periodically for equal time intervals. I'll check this later, most important app didn't crash.  Thanks Hugh!
