### ISSUE TITLE
nme-bunnymark on android drawTiles issue

### ISSUE THREAD

**Issue by codeservice** [haxenme/nme#273]
I tested https://github.com/elsassph/nme-bunnymark on android. I can see drawTiles issue (screenshot)
mac,windows,ios no problem.

![screenshot_20151107-210746](https://cloud.githubusercontent.com/assets/1771547/11018704/3852a01e-85a4-11e5-8e1f-e8909dd93b11.png)

**Comment by codeservice** [comment]
On iOS actually it's not working too, but effect appears from one time run then can work fine with another.

**Comment by hughsando** [comment]
I think this commit fixes it:
https://github.com/haxenme/nme/commit/eb6cc4ed9b662e4b7458927ee19fa3a013885082
But little hard to be sure because of intermittent behaviour.

**Comment by codeservice** [comment]
Problem fixed. I tested on android, dont see this issue any more. Thanks!
