### ISSUE TITLE
showKeyboard bug still active

### ISSUE THREAD

**Issue by thomasuster** [haxenme/nme#275]
This is a bug report from reported by on Android in latest Pakka Pet build which includes most recent NME. Any ideas @codeservice ?

java.lang.NullPointerException
org.haxe.nme.GameActivity.showKeyboard(GameActivity.java:1104)
org.haxe.nme.NME.onTouch(Native Method)
org.haxe.nme.MainView$8.run(MainView.java:488)
android.opengl.GLSurfaceView$GLThread.guardedRun(GLSurfaceView.java:1462)
android.opengl.GLSurfaceView$GLThread.run(GLSurfaceView.java:1239)

**Comment by codeservice** [comment]
hard to say what it is because I dont have problems with showKeyboard. This method restored to original version and has code as it was before modification. Check generated GameActivity.java file in your project output folder for android, especially line 1104. Maybe your code still based on modified showKeboard method and you need simply update template to latest version.

**Comment by thomasuster** [comment]
![screen shot 2015-11-20 at 10 42 18 am](https://cloud.githubusercontent.com/assets/220965/11308491/77178dc2-8f73-11e5-8682-20557753775c.png)

**Comment by thomasuster** [comment]
https://github.com/haxenme/nme/pull/282

**Comment by codeservice** [comment]
Check this:
http://stackoverflow.com/questions/19069448/null-pointer-error-with-hidesoftinputfromwindow

Looks like this bug related to view when it lost focus. Try check focus
like this:

if(mContext.getCurrentFocus() != null)
mgr.hideSoftInputFromWindow(mContext.getCurrentFocus().getWindowToken(), 0);

**Comment by thomasuster** [comment]
1) Oh, so the mContext.getApplicationContext().getSystemService won't fix it? I was hoping it would magically always be focussed.
2) If we do the null check you posted, which I'm confident will avoid the runtime error, will that have some sort of weird side effect now that we're not 'hideSoftInputFromWindow'?

**Comment by thomasuster** [comment]
I have no idea how to trigger this in my app. As there are 0 textfields.

**Comment by codeservice** [comment]
Keyboard opened on something what have focus. If we don't have focus keyboard more likely already closed and we don't need close it again. Don't think checking focus on null will be problem.

**Comment by codeservice** [comment]
We have one text field. You can try set focus to this object, didn't work for me well on some cases.

**Comment by thomasuster** [comment]
I have a fix that I'm going to try, otherwise I'll keep narrowing down the problem until I have a PR that I'm sure of.
