### ISSUE TITLE
openfl plugin 

### ISSUE THREAD

**Issue by hoseyjoe** [haxenme/nme#276]
I was messing around with openfl plugin for Flash IDE.  https://github.com/openfl/openfl-flash-plugin

I don't know if you have seen it but it might be nice to incorporate into NME.

**Comment by hughsando** [comment]
Yes, something like that would be nice.  I do not really have access to the
flash IDE, so it is difficult for me to get too involved.

**Comment by thomasuster** [comment]
Going to close then
