### ISSUE TITLE
[Android target] No input symbols whyle typing on keyboard in landscape oriented app

### ISSUE THREAD

**Issue by djaonourside** [haxenme/nme#299]
nme 5.5.13. I just added an input textfield on the stage.  

``` javascript
var input = new nme.text.TextField();
input.x = 10;
input.y = 10;
input.type = nme.text.TextFieldType.INPUT;
Lib.current.addChild(input);
```

When I start to input a text  I can see only asterisk symbol in keyboard input field. My app has  landscape orientation. After hidding the keyboard I can see my text in the stage text field. Everything is ok when the orientation is portrait.  I tried uncomment onKeyDown, onKeyUp methods in MainView.java but no changes:(

**Comment by thomasuster** [comment]
Seems to work fine in latest NME.

![temp](https://user-images.githubusercontent.com/220965/45932985-05232d80-bf3a-11e8-88a9-12da80b70c1b.jpg)
