### ISSUE TITLE
Full screen Android PR(?) GameActivity.java

### ISSUE THREAD

**Issue by hoseyjoe** [haxenme/nme#304]
Changing the below lines will allow fullscreen (no navigation buttons).

@Override protected void onStart()
   {
      super.onStart();

      ::if WIN_FULLSCREEN::::if (ANDROID_TARGET_SDK_VERSION >= 16)::
      if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.JELLY_BEAN)
      {
         getWindow().getDecorView().setSystemUiVisibility(View.SYSTEM_UI_FLAG_LAYOUT_FULLSCREEN | View.SYSTEM_UI_FLAG_LAYOUT_STABLE | View.SYSTEM_UI_FLAG_LOW_PROFILE | View.SYSTEM_UI_FLAG_FULLSCREEN);
      }
      ::end::::end::

      for(Extension extension : extensions)
         extension.onStart();
   }

to

@Override protected void onStart()
   {
      super.onStart();

    ::if WIN_FULLSCREEN::
    ::if (ANDROID_TARGET_SDK_VERSION >= 19)::
    if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.KITKAT) {
        getWindow().getDecorView().setSystemUiVisibility(
            View.SYSTEM_UI_FLAG_LAYOUT_STABLE |
            View.SYSTEM_UI_FLAG_LAYOUT_HIDE_NAVIGATION |
            View.SYSTEM_UI_FLAG_LAYOUT_FULLSCREEN |
            View.SYSTEM_UI_FLAG_HIDE_NAVIGATION |
            View.SYSTEM_UI_FLAG_FULLSCREEN |
            View.SYSTEM_UI_FLAG_IMMERSIVE_STICKY
        );
    }
    ::elseif (ANDROID_TARGET_SDK_VERSION >= 16)::
    if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.JELLY_BEAN) {
        getWindow().getDecorView().setSystemUiVisibility(
            View.SYSTEM_UI_FLAG_LAYOUT_FULLSCREEN |
            View.SYSTEM_UI_FLAG_LAYOUT_STABLE |
            View.SYSTEM_UI_FLAG_LOW_PROFILE |
            View.SYSTEM_UI_FLAG_FULLSCREEN
        );
    }
    ::end::
    ::end::

      for(Extension extension : extensions)
         extension.onStart();
   }

**Comment by thomasuster** [comment]
I've also been able to do this by changing this in my NMML file. ```<android minApiLevel="15" targetApiLevel="15" />``` to like ```<android minApiLevel="21" targetApiLevel="21" />```

Although I decided to revert back to 15. So if this works I'd love to use it!

**Comment by hughsando** [comment]
A PR would be great.

**Comment by hoseyjoe** [comment]
I created a PR, I think.  307
