### ISSUE TITLE
nme test flash Bitmap issue

### ISSUE THREAD

**Issue by hoseyjoe** [haxenme/nme#305]
I cant compile to flash.  not sure that it is an NME issue as the code hasnt changed

nme/display/Bitmap.hx:67: characters 0-16 : Recursive typedef is not allowed

using nme 5.5.13 
haxe 3.2.1

**Comment by hoseyjoe** [comment]
ran a -clean and it fixed issue

**Comment by thomasuster** [comment]
Sweet!
