### ISSUE TITLE
Avoid Dynamic (GC) and use cpp.Pointer for C++ target and haxe_ver >= 3.2?

### ISSUE THREAD

**Issue by madrazo** [haxenme/nme#306]
Hi.
I have a question / request.
I have seen that when you set a property, say, the position X of a sprite it creates a Dynamic object and sometmes triggers GC collect

The stack is something like 

DisplayObject_obj::set_scaleX(Float value)
AbstractToObject?
Dynamic::Dynamic
...

A time ago I asked about something similar
http://gamehaxe.com/2014/05/28/wwx2014-talk-hxcpp-magic/#comments
and I was able to retrieve a cpp.Pointer in the constructor and just update it later. 

For example in DisplayObject.hx, you could replace the x getter and setter with:

```
    private var xPtr:Pointer< Float >;
```

IN CONSTRUCTOR: 

```
     xPtr = nme_display_object_get_x_ptr (__handle);
```

GETTER AND SETTER:

```
    private function get_x ():Float { return xPtr.value; }
    private function set_x (value:Float):Float {
        xPtr.ref = value;
        return value;
    }
    private static var nme_display_object_get_x_ptr = Loader.load("nme_display_object_get_x_ptr", 1);
```

Do you think that this would work for replacing the dynamic allocations? 
Thanks!

**Comment by hughsando** [comment]
Hi,
I have developed the "cffi prime" extension to the "cffi" code.  This code
still uses dynamic loading, so it will work on neko, but uses native c++
function pointers where possible and avoids to the Dynamic allocation.
This should give you what you want, I just need some time to switch over to
this.

**Comment by madrazo** [comment]
Great news. Thanks.

**Comment by thomasuster** [comment]
Awesome!
