### ISSUE TITLE
"Field conflict" error at the end of Android build

### ISSUE THREAD

**Issue by jskuse** [haxenme/nme#309]
I've been trying to build an Android version of our game using NME for the first time and, after a few tweaks, it appears to actually get through the compiling phase of the build process without any reported issues, however when it completes it throws out the following:
```
-post-build:

debug:

BUILD SUCCESSFUL
Total time: 59 seconds
Error: Error creating manifest others.c(442) : Field conflict between lavender and assets/tm3_assets_images_world_objects_eye_png
```
There doesn't seem to be anything further up the output to suggest problems and an APK is produced, but it won't run. Obviously the second element in that error is a graphics asset from the game whereas "lavender" doesn't ring any bells - I can only guess it to perhaps be a colour constant from some place or another. 

I'm not at all familiar with Android tooling, so I'm not even sure what component of the build process is failing here and Google doesn't seem to produce anything useful with regards to "Field conflict" errors, so I'm pretty much stumped. Do you have any hints as to what areas I could investigate as a possible culprit here?

**Comment by hughsando** [comment]
I have never hear of this before.  My first guess is that there is a hash-conflict on the name, and as you guess, maybe lavender is some kind of built-in one.
Does renaming the asset (even slightly) help?

**Comment by jskuse** [comment]
Thanks for the quick suggestion - renaming the asset (and doing a clean build, otherwise it froze building AssetData.cpp) does indeed fix it. So I guess you were most likely right about it being a hash collision - what utterly bad luck. Would I be right to assume that this error isn't emitted from the NME part of the build chain? 

The good news is that the NME build addresses the big issue that we were experiencing in OpenFL legacy. Of course it introduces a few (much) smaller ones - but one step at a time!

**Comment by thomasuster** [comment]
@jskuse Cool! I'm the guy that makes Pakka Pets. Please check out the game, and after understanding it's breadth if you have an issue you think I could help with don't hesitate to ask in https://gitter.im/haxenme/nme
