### ISSUE TITLE
Android BUILD FAILED with google play services lib

### ISSUE THREAD

**Issue by andrew-git** [haxenme/nme#310]
I try to build project, that use https://github.com/Tw1ddle/samcodes-admob library.
OpenFL build ok, but on NME I got

BUILD FAILED
D:\Android\android-sdk\tools\ant\build.xml:577: ../google-play-services_lib resolve to a path with no project.properties file for project D:\proj\bin\android\proj2\deps\samcodes-admob

Error: Error creating manifest [file_contents,bin/android/proj2/libs/armeabi/libnme.so]

**Comment by thomasuster** [comment]
Not sure if NME gradle will be compatible with OpenFL. We can test this after this merges or during code review. https://github.com/haxenme/nme/pull/535

**Comment by thomasuster** [comment]
Hey @andrew-git, https://github.com/haxenme/nme/pull/535 is merged, want to give the `nme test android -gradle` a try using NME from the repo source?

**Comment by thomasuster** [comment]
@andrew-git Going to mark this as fixed, feel free to reopen if you re-run into the issue.

**Comment by andrew-git** [comment]
@thomasuster Ok, sorry for silence, working on other projects now
