### ISSUE TITLE
hxcpp 3.3 can't compile NMEThread.h

### ISSUE THREAD

**Issue by madrazo** [haxenme/nme#314]
https://github.com/HaxeFoundation/hxcpp/pull/431
brokes compilation for  NMEThread.h
since MyMutex has to be changed to HxMutex

Does it need a #define in hx/Thread.h for backward compatibility?

e.g.
#ifdef HXCPP_HX_SUFFIX
typedef HxMutex NmeMutex;
#else
typedef MyMutex NmeMutex;
#endif

?
thanks

**Comment by hughsando** [comment]
Good idea.  I added a "HXCPP_HEADER_VERSION" define, which might be useful for other things later.
