### ISSUE TITLE
Compile issue with nightly 5.6.7

### ISSUE THREAD

**Issue by hoseyjoe** [haxenme/nme#323]
Desktop>nme
Called from Sys::$statics line 1
Called from RunMain::main line 107
Called from RunMain::executeNme line 93
Called from neko.Lib::rethrow line 60
Called from RunMain::executeNme line 84
Called from neko.vm.Loader::loadModule line 132
Called from nme.display.Tilesheet::$statics line 63
Called from nme.Loader::load line 71
Called from neko.Lib::load line 30
Uncaught exception - load.c(357) : Primitive not found : nme@nme_tilesheet_get_rect(3)

**Comment by hughsando** [comment]
Yes looks like, I need to bump the binary version to get the ndll to
recompile.
You could do this yourself if you need to use this version.

**Comment by hoseyjoe** [comment]
Thanks.  You fixed in later nightly. Cheers
