### ISSUE TITLE
Android - OpenSL ES - Too many objects

### ISSUE THREAD

**Issue by eliasku** [haxenme/nme#327]
After time new sounds stop playing and OpenSL errors start growing on each `Sound::play`.

```
06-19 01:24:02.700  3745  3793 W libOpenSLES: class OutputMix interface 0 requested but unavailable MPH=43
06-19 01:24:02.700  3745  3793 E libOpenSLES: Too many objects
06-19 01:24:02.700  3745  3793 W libOpenSLES: Leaving Engine::CreateOutputMix (SL_RESULT_MEMORY_FAILURE)
06-19 01:24:02.700  3745  3793 E NME     : Could not create outputMixObject
```

Repro:
- Just select `opensl` engine and try to play a sequence of short sounds more than 50.

I've tried listening `Event.SOUND_COMPLETE` event to call `stop()`, but it isn't dispatched after sound is completed. Only when application closes - all events are dispatched.

So, I've checked cpp code-base for `isComplete` routine
`(*bqPlayerPlay)->GetPlayState(bqPlayerPlay, &state);`
If I understand openSLES correctly - it's not switched to STOPPED state automatically after sound playing is complete, it's all for manual control. Should we check isComplete by SL callback or something else here?

Quick workaround will be appreciated...

**Comment by hughsando** [comment]
Are you playing the 1 sound 50 times, or 50 different sounds?
Sounds like the stop condition needs some work.

**Comment by thomasuster** [comment]
@eliasku Have you tried the latest NME? Is this still an issue?

**Comment by thomasuster** [comment]
Okay, feel free to reopen if you have a reproducible project we can use to recreate the problem.
