### ISSUE TITLE
IOS not launching blank project

### ISSUE THREAD

**Issue by hoseyjoe** [haxenme/nme#329]
I created a blank project with openfl
1. openfl create project blank
2. nme ios

I get error like issue #319

**Comment by hughsando** [comment]
What version of nme are you using?
You probably need to rebuild nme with
neko build.n ios
from the "projects" directory.

**Comment by hoseyjoe** [comment]
Generally I don't compile NME on my OSX machine since it is a  8 year old
mac mini. I was using the nightly 5.6.12, I just confirmed 5.6.13 has same
issue.  Should I use the GIT instead of nightly (nmehost.com/nme)?

I confirmed issue does not happen on GIT vesion

**Comment by hughsando** [comment]
Looks like the nmehost overnight needs some kind on rebuild - thanks for
reporting.

**Comment by hoseyjoe** [comment]
Maybe related: I could not get NME to compile with haxe RC1.  I had 3.2.1 when i confirmed GIT didn't have issue

**Comment by hoseyjoe** [comment]
No longer occurring
