### ISSUE TITLE
iPhone extension example?

### ISSUE THREAD

**Issue by dyarosla** [haxenme/nme#334]
I can't seem to find any information on how to make an iPhone extension. I'm looking into how to port something like https://github.com/bazzisoft-openfl-extensions/nativetext for openfl but to nme.

**Comment by hughsando** [comment]
There is a chance it will mostly work without modification - it should be pretty similar.
I'm looking to transition the ios & android extensions to directly and statically link in the extension code and use the new "-toolkit" libraries.  This will allow them to use, and be used by, the haxe gen code without any glue.  This can be done with a "normal" haxelib library, and does not need nme to do anything special (unless extra assets or something are needed).
But probably wait until 3.3 proper is out.

**Comment by dyarosla** [comment]
Thanks Hugh.

I took a look and was able to use it via the "normal" haxelib route;

Zipping the extensions, adding them via haxelib local extension.zip
Including them in the nmml files and then running it.

I still think a proper step-by-step sample for iphone would be useful for new developers, but for now this method should suffice, thanks!
