### ISSUE TITLE
Stage3D depth and stencil blend with stage (question)

### ISSUE THREAD

**Issue by codeservice** [haxenme/nme#336]
I am trying blend stage and stage3D content. It works well when stage3D in blendandstencil mode = false. I think because stage using the same mode. How can I synchronize stage and stage3D if I want mode = true? Any option for this for stage?

**Comment by codeservice** [comment]
I've tried stage with depth stencil mode. Added GL switch when render context begin. Looks like 2D stage doesn't support it at all.

**Comment by hughsando** [comment]
Not exactly sure what you  need here.  Are you looking for a "render stage to texture" call, so you can apply effects, or do you just want to enable depth/stencil for various parts of the render.
It should be possible to get opengl to create the correct depth/stencil buffer.  Setting the compare equations may require a bit of work, but should be possible.
Are you looking to do something like depth-tested tile rendering?

**Comment by codeservice** [comment]
I have nme sprites on top of 3D stage. If 3D stage created
with context3D.configureBackBuffer( stage.stageWidth, stage.stageHeight, 0,
false); where  depth/stencil FALSE, I can blend it
with context3D.setBlendFactors(0x0302, 0x0303); Sprites rendering well and
I can see em on top of 3D content.

If depth/stencil TRUE, sprites look damaged, for example I dont see border
lines for rectangles in this case.

I dont know well openGL, but maybe its possible turn off any custom 3D
rendering options when nme rendering sprites and turn em back ON when 3D
stage rendering.

For turning off I mean something like:
                nme.gl.GL.disable(nme.gl.GL.DEPTH_STENCIL);
                nme.gl.GL.disable(nme.gl.GL.DEPTH_TEST);

stage.context3D.setCulling(nme.display3D.Context3DTriangleFace.NONE);//disable
culling or it makes square sprite render like triangle, wrong vertex order

**Comment by codeservice** [comment]
In addition with few modifications I was able to run Away3D on nme and
Away3D using depth and stencil mode. For some reason sprites looks well
with Away. In this lib code I can see depth and stencil mode switching back
and force for rendering process. I am wandering is it possible make the
same at NME level? In this case sprites and tiles will be safe from stage
3D modifications. Not sure where best place in NME to do this switch logic.

On Tue, Jul 19, 2016 at 11:25 AM, Alexander Mokrushyn <codeservice@gmail.com

**Comment by hughsando** [comment]
Ok, so the stage3d is not returning the context to the "normal" state -
that should be easy enough to fix.
Actually, I have not had much to do with the stage3d, but I assume its easy.

**Comment by codeservice** [comment]
Yes doesn't look like big change, I don't know right place where make this fix and how properly restore stage 3D back when sprites finished rendering. For now I am using away3d as it works correctly with depth. Culling only was damaged here and I found how to restore it. On NME I can't find this spot as it partially on haxe files part in cpp.
