### ISSUE TITLE
Custom iOS Template PROJ-Info.plist not being used

### ISSUE THREAD

**Issue by jskuse** [haxenme/nme#337]
We're in the process of moving our iOS build over from OpenFL legacy to NME and have come across an odd behaviour with our custom PROJ-Info.plist not being copied over despite the other custom template elements (such as Images.xcassets) copying over fine.

I've had a bit of dig around in the code and I _think_ the issue is simply to do with inconsistent behaviour when copying files via `FileHelper.copyFileTemplate` and `FileHelper.recursiveCopyTemplate`. 

In our case, the `project.templatePaths` array seems to have our custom template directory as the first element and the NME template path as the second. `FileHelper.copyFileTemplate` uses `PathHelper.findTemplate` to select the "right" file to use, which in turn returns the _last_ match found, which will be NME's in built version of the file rather than the custom one. 

`FileHelper.recursiveCopyTemplate`, on the other hand, seems to use the _first_ version of any particular file it encounters when iterating through the template paths, resulting in our custom version being used.

It looks like `PathHelper.findTemplate` used to return the first file, since there is a commented out line, but was replaced with one returning the last file in commit 191fd772cd7c675dac4f29c06834170037b7c503.

I've temporarily patched this in my local version, but thought it worth flagging up since it was clearly an intentional change, but I'm unclear as to how to work around without changing back to the previous behaviour.

**Comment by hughsando** [comment]
My understanding was always it should be the first file found.
The change does seem a bit odd, given this.
I think this was to allow completely new files in the template path, but
take the "correct" one if multiple, although it seems wrong now.  The issue
may actually be the order I have built the template paths some some
dependency or the "view" code somewhere.
I am tempted to just include your change (reversion), but I first really
need some unit tests here to make sure I do not break anything else.  Maybe
I have only tried the directory overrides, not the single files.

**Comment by jskuse** [comment]
It's difficult when it comes to these sorts of widely used utility functions, because obviously side effects can be pretty subtle - it's certainly seemed a little odd behaviourally to me, but I don't have the overview of all the targets that you do. For what it's worth, I've not had any problems since making the change. But for sure, even without wide coverage, tests could at the very least act as a spec for the various utility functions, which would be useful. 

If you'd like any help just say the word - if we can iron out the few remaining issues, we're probably going to be throwing our lot in with NME on http://www.teachyourmonstertoread.com since it seems to provide better vector graphics performance, so anything we can do to aid stability is very much in our interest.

**Comment by madrazo** [comment]
I just got this issue. templatePath didn't replace the PROJ-Info.plist

**Comment by madrazo** [comment]
I see that you can add "CUSTOM_BLOCKS" instead, bu needs documentation ;) https://github.com/haxenme/nme/issues/405

**Comment by thomasuster** [comment]
Closing, likely stale, I'm quite familiar with this area of code so feel free to reopen if you're having issues.
