### ISSUE TITLE
Can't rebuild NME for Android

### ISSUE THREAD

**Issue by jskuse** [haxenme/nme#354]
I'm a total novice with the Android toolchain and I am just trying to compile our branch of NME for Android for the first time with ```neko build.n android``` and having no luck. After getting over the usual "update SDK/NDK" and "make sure the path is set" type issues, I'm butting up against:

```
Error: While running :aarch64-linux-android-g++ -I../include -Iinclude -DNME_CURL_SSL -I/usr/local/lib/haxe/lib/nme-dev/5,5,1/include -D_7ZIP_ST -DNME_BUILDING_LIB --sysroot=/opt/android-ndk/platforms/android-21/arch-arm64 -I/opt/android-ndk/sources/cxx-stl/gnu-libstdc++//include -I/opt/android-ndk/sources/cxx-stl/gnu-libstdc++//libs/arm64-v8a/include -DHXCPP_M64 -I/usr/local/lib/haxe/lib/hxcpp/3,3,49/include -Iinclude -fpic -fvisibility=hidden -ffunction-sections -funwind-tables -fstack-protector -fno-short-enums "-D_LINUX_STDDEF_H " -Wno-psabi -DHXCPP_CPP11 -fomit-frame-pointer -fexceptions -fno-strict-aliasing -finline-limit=10000 -DANDROID=ANDROID -DHX_ANDROID -DHXCPP_ANDROID_PLATFORM=21 -Wa,--noexecstack -O2 -DNDEBUG -c -x c++ -Wno-invalid-offsetof -frtti -std=c++11 ./src/audio/AndroidSound.cpp -o/usr/local/lib/haxe/lib/nme/git/project/obj/android-stat-64/5f9c178d_AndroidSound.obj
In file included from ./src/audio/AndroidSound.cpp:1:0:
include/Sound.h:4:18: fatal error: string: No such file or directory
 #include <string>
```

So it looks like it can't find the standard headers and Google isn't being particularly helpful. I understand this isn't likely to be an NME specific issue, but do you have any pointers as potential causes of this sort of thing when rebuilding NME for Android?

**Comment by jskuse** [comment]
Ah, actually, now I look at it closely, that ```-I/opt/android-ndk/sources/cxx-stl/gnu-libstdc++//include``` isn't the right path for the NDK on my system. Where is it getting that path from?

**Comment by jskuse** [comment]
I moved the whole NDK to that the path and we're building. That path wasn't listed anywhere in my ```env``` so I'm guessing that it's convention for the NDK to live there?

It mostly seems to compile ok now, except the ARM64 version where it's unhappy about ```/usr/local/lib/haxe/lib/nme-dev/5,5,1/lib/Android/libfreetype-64.a``` being missing (which it is). A rebuild of nme-dev doesn't create it, so I'm guessing nme-dev isn't not set up to compile ARM64 versions of the various libraries? 

Please forgive my ignorance here, I'm fumbling around in the dark!

**Comment by madrazo** [comment]
Hi. 

Did you try 

`neko build android-m64`
in nme-dev\project?

Also, I needed 64-bit binaries for windows and I added

`override public function wantWindows64() { return true; }`

in nme-dev/tools/build/Build.hx and compile with compile.hxml
maybe there is something similar for Android?

**Comment by jskuse** [comment]
Thanks for the suggestion @madrazo. That wasn't quite it, but it did point me in the right direction - poking around various build files it looks like -DHXCPP_ARM64 would be the thing to use to build nme-dev for arm64 and it certainly got me a *lot* further along the build process than before, so good progress, but eventually bailed on:

```
 - Compile : adler32.c
Error: While running :aarch64-linux-android-g++ --sysroot=/opt/android-ndk/platforms/android-24/arch-arm64 -I/opt/android-ndk/sources/cxx-stl/gnu-libstdc++/4.9/include -I/opt/android-ndk/sources/cxx-stl/gnu-libstdc++/4.9/libs/arm64-v8a/include -DSTATIC_LINK -DHXCPP_M64 -DHXCPP_VISIT_ALLOCS -DHXCPP_API_LEVEL=0 -I/usr/local/lib/haxe/lib/hxcpp/3,3,49/include -Iinclude -fpic -fvisibility=hidden -ffunction-sections -funwind-tables -fstack-protector -fno-short-enums "-D_LINUX_STDDEF_H " -Wno-psabi -march=armv7-a -mfpu=vfpv3-d16 -mfloat-abi=softfp -fomit-frame-pointer -fexceptions -fno-strict-aliasing -finline-limit=10000 -DANDROID=ANDROID -DHX_ANDROID -DHXCPP_ANDROID_PLATFORM=24 -Wa,--noexecstack -O2 -DNDEBUG -c -x c ./crc32.c -o/usr/local/lib/haxe/lib/nme-dev/5,5,1/project/unpack/zlib-1.2.3/obj/android-stat-64/5c7d85d2_crc32.obj
aarch64-linux-android-g++: error: unrecognized command line option '-mfpu=vfpv3-d16'
aarch64-linux-android-g++: error: unrecognized command line option '-mfloat-abi=softfp'
```

**Comment by hughsando** [comment]
Looks like those flags are not needed for 64 bits, and now they are
generating errors, and should be removed.

I'm moving away from nme-dev, mainly because of the problems you are seeing
to do with requiring to build or distribute many different libraries.

The way I'm going is via the "nme-toolkit" library.  Here, you haxelib
install the nme-toolkit lib instead of the nme-dev haxelib, and compile
with "-toolkit" on the nme command line.
This way, the compiler flags will exactly match what you are building your
app with. I will probably make this default soon.

**Comment by jskuse** [comment]
Ok, that sounds like a plan. I've disabled the native code from the the hxcpp issue I opened just to see if I can get the haxe bit building.

Running ```nme build mac -toolkit``` is totally fine and I can see it building SDL etc. so I guess the toolkit flag is being respected.

However when I ```nme build mac -toolkit``` we get a fair way through before hitting:
```
Error: While running :arm-linux-androideabi-g++ -I/Users/jskuse/Documents/development/tm/tm3game/tmapp/bin/android/haxe/cpp/obj/android/__pch/haxe -Iinclude -I/usr/local/lib/haxe/lib/nme/5,6,4/include -DHX_UNDEFINE_H --sysroot=/opt/android-ndk/platforms/android-9/arch-arm -I/opt/android-ndk/sources/cxx-stl/gnu-libstdc++/4.9/include -I/opt/android-ndk/sources/cxx-stl/gnu-libstdc++/4.9/libs/armeabi/include -DHXCPP_VISIT_ALLOCS -DHXCPP_API_LEVEL=321 -I/usr/local/lib/haxe/lib/hxcpp/3,3,49/include -Iinclude -fpic -fvisibility=hidden -ffunction-sections -funwind-tables -fstack-protector -fno-short-enums "-D_LINUX_STDDEF_H " -Wno-psabi -DHXCPP_CPP11 -D__ARM_ARCH_5__ -D__ARM_ARCH_5T__ -D__ARM_ARCH_5E__ -D__ARM_ARCH_5TE__ -march=armv5te -mtune=xscale -msoft-float -fomit-frame-pointer -fexceptions -fno-strict-aliasing -finline-limit=10000 -DANDROID=ANDROID -DHX_ANDROID -DHXCPP_ANDROID_PLATFORM=9 -Wa,--noexecstack -O2 -DNDEBUG -c -x c++ -Wno-invalid-offsetof -frtti -std=c++11 ./src/tm3/world/missions/JumbleAndJangle.cpp -o/Users/jskuse/Documents/development/tm/tm3game/tmapp/bin/android/haxe/cpp/obj/android/9cfe955f_JumbleAndJangle.obj
In file included from /opt/android-ndk/sources/cxx-stl/gnu-libstdc++/4.9/include/cctype:42:0,
                 from /opt/android-ndk/sources/cxx-stl/gnu-libstdc++/4.9/include/bits/localefwd.h:42,
                 from /opt/android-ndk/sources/cxx-stl/gnu-libstdc++/4.9/include/string:43,
                 from /opt/android-ndk/sources/cxx-stl/gnu-libstdc++/4.9/include/random:40,
                 from /opt/android-ndk/sources/cxx-stl/gnu-libstdc++/4.9/include/bits/stl_algo.h:66,
                 from /opt/android-ndk/sources/cxx-stl/gnu-libstdc++/4.9/include/algorithm:62,
                 from /usr/local/lib/haxe/lib/hxcpp/3,3,49/include/Array.h:373,
                 from /usr/local/lib/haxe/lib/hxcpp/3,3,49/include/hxcpp.h:322:
include/tm3/world/missions/BaseMatchGame.h:61:45: error: expected unqualified-id before numeric constant
   ::tm3::world::critters::WordGameCharacter _B;
                                             ^
./src/tm3/world/missions/JumbleAndJangle.cpp: In member function 'virtual Void tm3::world::missions::JumbleAndJangle_obj::added()':
./src/tm3/world/missions/JumbleAndJangle.cpp:177:9: error: expected unqualified-id before numeric constant
   this->_B = tmp15;
         ^
./src/tm3/world/missions/JumbleAndJangle.cpp:181:59: error: expected unqualified-id before numeric constant
   ::tm3::world::critters::WordGameCharacter tmp17 = this->_B;  HX_STACK_VAR(tmp17,"tmp17");
                                                           ^
./src/tm3/world/missions/JumbleAndJangle.cpp:185:59: error: expected unqualified-id before numeric constant
   ::tm3::world::critters::WordGameCharacter tmp18 = this->_B;  HX_STACK_VAR(tmp18,"tmp18");
                                                           ^
./src/tm3/world/missions/JumbleAndJangle.cpp:203:59: error: expected unqualified-id before numeric constant
   ::tm3::world::critters::WordGameCharacter tmp26 = this->_B;  HX_STACK_VAR(tmp26,"tmp26");
                                                           ^
./src/tm3/world/missions/JumbleAndJangle.cpp: In member function 'Void tm3::world::missions::JumbleAndJangle_obj::added()::_Function_1_2::run()':
./src/tm3/world/missions/JumbleAndJangle.cpp:258:45: error: expected unqualified-id before numeric constant
     ::hpohx::display::HPOVisual tmp42 = _g->_B->visual;  HX_STACK_VAR(tmp42,"tmp42");
                                             ^
Error: Build failed
````

My assumption is this will be down to a difference between the compiler used between Mac and Android. From what I can see this particular file *does* compile with a toolkit-less ```nme build android``` though.

**Comment by hughsando** [comment]
I see the difference.  Nme ToolkitBuild is forcing the android ndk platform
to be 9 for maximum compatibility.
"Normal" nme did this too, but the flag did not overflow into the haxe
build.
It looks like the older ndk platform 9 did something like "#define _B 0x80"
somewhere in the standard header files, and this if breaking your code.
Google must have realized that this is a pretty obnoxious thing to do and
fixed it at some stage.

I could try just bumping the platform up in ToolkitBuild.xml, but I will
need to test a few devices because google un-inlined some stuff which means
the new ndks are basically unusable for old phones unless you restrict
which functions you call.

I could also look to do a per-file ndk, which would be effectively what a
static-link did before, but I so not really like this.

I could "#undefine _B", like I have to with a bunch of microsoft crap, it
looks like there is also u,l,n,s,p,c,x,b

You could also change the name of this variable, which might let you test
the new stuff.

I think I will bump the version to 21 and change hxcpp to make this work.

**Comment by jskuse** [comment]
Thanks Hugh, that makes sense (albeit terrifying, but I'm getting the feeling this is par for the course in Android land). For now I've just renamed the variable and finally it does build with ```-toolkit```. Well, after manually applying HaxeFoundation/hxcpp@25247b443474ef5323ae299e94bb7a2674a4fa0d to my local hxcpp, because (otherwise it couldn't find libgcc.a) and hacking NME to look elsewhere for ```android-support-v4.jar```, since it doesn't seem to be present anywhere in my SDK installation despite *seemingly* having the right packages installed. 

Unfortunately the ```-toolkit``` build of the game just launches to a black screen, but that's a whole other issue. So I'll close this, investigate and open a new issue if and when I can make any sense of what's going on. 

Thanks again for the help / support!
