### ISSUE TITLE
Destroy video on android not implemented

### ISSUE THREAD

**Issue by codeservice** [haxenme/nme#361]
I started making this implementation and stuck with problem when I destroyed VideoView and cant restore stage to original background colour. It always black after video gone.

Code in NMEVideoView.java:
<code>
   public static void nmeDestroy()
   {
      Log.d(TAG,"destroy");

       final GameActivity a = GameActivity.activity;
       a.queueRunnable( new Runnable() { @Override public void run() {
           if (a.mVideoView!=null) {
               a.mVideoView.stopPlayback();
               a.mContainer.removeView(a.mVideoView);
               a.mVideoView = null;
               a.setBackgroundSync(a.mBackground);
           }
       } });
   }
</code>

**Comment by codeservice** [comment]
Found reason why stage black when video load on android

AndroidFrame.cpp:
   uint32 getBackgroundMask()
   {
      return video ? 0x00ffffff :  (mBackground|0xffffff);
   }

destroy function need to include
delete video;

**Comment by hughsando** [comment]
Nme creates on opengl context with a transparent backgound so it can render over video.
There are performance reasons why you may also want to recreate the context without a transparent background once the video is gone.  But you would need to profile this to see if it makes a difference for you.
