### ISSUE TITLE
__s primitive not found

### ISSUE THREAD

**Issue by codeservice** [haxenme/nme#364]
I have this error in ApplicationMain.hx template (::foreach line) when I recompiled all *.n tools for hxcpp and nme on haxe 3.3.0. I was able compile application on old *.n tools compiled on haxe 3.2.1 for haxe 3.3.0

**Comment by hughsando** [comment]
What version of haxe are you using?  I have a feeling it may have been fixed.
If not, I wonder if I can work around this issue by setting some strings to empty instead of null.
Do you know when element it was failing on?

**Comment by codeservice** [comment]
I installed haxe 3.3.0 rc1 on Windows using installer. Recompile all Neko tools and when I run project nmml I saw this error. Somewhere system processing application template and crash on first ::foreach. Do I need to use haxe from Github or is it problem in tools code?

**Comment by kiroukou** [comment]
Hello.
Same problem here.   Haven't found a solution so far.

**Comment by hughsando** [comment]
The 3.3.0rc is getting pretty old now, so the issue may well have been
fixed.
You should have more luck with the nightly version of haxe.

**Comment by codeservice** [comment]
Works with haxe night builds
