### ISSUE TITLE
Icons not working?

### ISSUE THREAD

**Issue by Gama11** [haxenme/nme#384]
(Testing with the project from `nme create 00-Nmml`, which references a `nme.svg` in it's `.nmml` and NME 5.6.4)

The windows opened after `nme test neko` or `nme test cpp` don't seem to have any icon:

![](http://i.imgur.com/NVxB3wN.png)

**Comment by thomasuster** [comment]
![Uploading Screen Shot 2016-10-03 at 9.44.09 AM.png…]()
