### ISSUE TITLE
NME crash on Neko when using embedded font

### ISSUE THREAD

**Issue by bendmorris** [haxenme/nme#390]
```
Stage.hx:457: Exception: Bad ByteArray

Called from nme/text/TextField.hx line 134
Called from com/haxepunk/graphics/Text.hx line 137
Called from a C function
Called from com/haxepunk/graphics/Text.hx line 73
```

This happens when trying to access a new TextField's width when using an embedded font. When the font is not embedded or on targets other than neko, it works. Noticed this with HaxePunk's default font (https://github.com/HaxePunk/HaxePunk/blob/dev/assets/font/04B_03__.ttf) and only tested on Mac.

**Comment by hughsando** [comment]
I could not reproduce this with a simple example - on windows.  I can check mac later.
Is it possible this code is getting called very early (maybe before the stage and assets are set up)?
eg, from a static variable initializer.

**Comment by bendmorris** [comment]
This happens with every project in the HaxePunk-examples repo, but I haven't been able to isolate it to something simpler. It's happening from the ADDED_TO_STAGE listener, so not quite so early.

With -debug I get the following trace:

```
$ nme test neko -debug
Lib.hx:90: Error creating window: ({ icon => null, color => 15132390, width => 640, height => 480, flags => 8, title => cursors })
Bad ByteArray
Called from nme.display.DisplayObject::get_width line 542
Called from haxepunk.debug.Console::enable line 251
Called from Main::init line 9
Called from haxepunk.Engine::onStage line 265
Called from nme.events.Listener::dispatchEvent line 32
Called from nme.events.EventDispatcher::dispatchEvent line 140
...
```

**Comment by bendmorris** [comment]
That trace looks different and unrelated to text...but strangely enough removing `embed="true"` on the fonts makes it go away.

**Comment by hughsando** [comment]
The error is coming from the nme font system calling back into the haxe
code the get the font data. Without embed, it will load from a file. For
some reason, the data is in the wrong format on neko and nme throws this
error.
I can have a look at the samples.

**Comment by bendmorris** [comment]
For the record: https://github.com/haxepunk/haxepunk

Checking out the dev branch, syncing the `examples` submodule and building any of those projects with `nme test neko` should show the problem.
