### ISSUE TITLE
pixel perfect glyph textures

### ISSUE THREAD

**Issue by codeservice** [haxenme/nme#391]
At some moment nme font rendering method was replaced by tiles drawing on nme. Old method was hardware->BeginBitmapRender(tile.mSurface,tint,false,false); I didnt see random glyph texture distortion on ios (retina) using old way before and now this problem clearly visible on high resolution displays. I know half pixel shift approach can fix it and replacing this line to: mTile->tile(p.x+0.5/tile.mRect.w, p.y+0.5/tile.mRect.h, tile.mRect, trans_2x2, tint); gives result almost perfect. I think this should be done on texture data forming level and can't find it as my nme knowledge has limits. Any one can pointing me out where tile texture forming and this fix can be applied?

Issue description found here: http://drilian.com/2008/11/25/understanding-half-pixel-and-half-texel-offsets/

**Comment by hughsando** [comment]
There is code in TextField.cpp that is supposed to sort this out.
The 'screenGrid' variable says whether the tile locations should be snapped to the pixel locations.  This is based on not having a skew in the matrix, or different x and y scales.  Maybe this is not getting activated.  You could try forcing on 'grid' and see if this fixes the problem.

It is also possible something like x or y centering is messing up the pixel locations after they have been calculated.  Are you centering the text?

There might also be a non-integer scaling imposed by the retina display that nme can't see properly, and therefore can't work out the pixel grid.  Would have to have a deeper look at this.

**Comment by hughsando** [comment]
Looks like that article is for directx.
Opengl and nme software rendering coordinates are more sensible - the integer locations are on the "cracks", and the pixel is sampled at a (0.5,0.5) offset.  If you draw a 1x1 quad at 0,0 the texure will be sampled from the center, and is should not matter whether you are using nearest or linear interp.

**Comment by codeservice** [comment]
Text not centered, aligned to left. I tested the same app with old nme rendering way and new. For some reason tiles can be deformed depending on position on screen when I scroll text. This happens for the same characters on whole vertical or horizontal line on screen. For example "l" look twisted in glyph middle and when I scroll text this appears and disappears for whole vertical text line for all charters "l" on this line, same for horizontal for example if I have text "TELEVISON" middle line in all "E" twisted  on one horizontal line. Also could be case when whole text line top and bottom pixels flickering when I changing text field "y" coordinate. 

Then I start playing with tile coordinates calculation and was able to reduce or increase this effect depending on different ways of rounding. Most close case described by other developers who using a lot of tiles on screen was this pixel perfect texture issue when half pixel solution need to be used for texture U and V coordinates to fix it.

Looks like it require more research time still don't understand why old rendering way has no this issue.

**Comment by hughsando** [comment]
The old code did not allow arbitrary rotation of text, so if there is a
small rotation component this could be showing up now.
The font code is a bit different because it takes the scale from the view
matrix and transfers it to the font size.  It then should lay out the
generated font pixels 1:1 with the screen.

Does it show up in the sample/02-Text example?  Is it only on a ios/retina
display?  Or do you think there is some other way I can reproduce this.
Does it only happen when scrolling?  It could be that the scroll distance
it not properly snapped to the pixel grid.

**Comment by codeservice** [comment]
I dint apply any extra transformations to my text, didn't use rotation or
scale. I have big text field practically over whole screen and in some
"sweet" spots I see these deformations. Maybe its good way to recreate this
issue in simple app, create big text field, multi line, wrapped, left
alignment and insert large text.

I dint see this issue on windows or mac(not retina), only ios retina.
(didn't check android yet)

Also I have custom UI list based on static text field items. I scroll list
simply changing textfield y position, same issue. It could be like 50-60
items and one or two items with damaged text.
(same, no extra transformation in my code)

I didn't see this issue on small text fields sample, its really required a
lot of text over screen to capture issue on ios.


P.S.
Found more links for texture positioning
http://stackoverflow.com/questions/7272579/iphone-opengl-es-2-0-pixel-perfect-textures
http://stackoverflow.com/questions/33307779/opengl-4-4-texture-atlas-artifacts
http://stackoverflow.com/search?q=opengl+perfect+texture

**Comment by hughsando** [comment]
I'm thinking it might be ios specific - perhaps to do with the layer transform.
It does sound a bit like a precision problem.  as you scroll, does the issue move with the text, or stay fixed on a certain spot on the screen?  You could try changing 'mediump' to 'highp' in the OGLShaders.cpp file and see it that changes anything.  The code I just tried was:
`import nme.display.Sprite;
import nme.text.TextField;
import nme.text.TextFormat;

class Test extends Sprite
{
   var tf:TextField;
   var count:Int;

   public function new()
   {
      super();
      scaleX = scaleY = 2;
      tf = new TextField();
      var fmt = new TextFormat();
      fmt.size = 7;
      tf.defaultTextFormat = fmt;
      tf.x = 10;
      tf.y = 10;
      tf.width = 1000;
      tf.height = 800;
      tf.wordWrap = true;
      tf.multiline = true;
      addChild(tf);

      var bases = [ "adkjha", "mcv", "ppoipou", "iuyiy", "yeqerqy", "gasgas", "sgfsjdf", "jhlfg", "zxcbvz", "xmcnvbmx", ",nb,mn,", "12312", "e5634", "98978097", "!@#!", "O!*#&$@!", "_*&(*&" ];

      var words = [];
      for(i in 0...10000)
         words.push( bases[ Std.int(Math.random()*bases.length) ] );

      tf.text = words.join(" ");
   }
}`

**Comment by hughsando** [comment]
So I did find an issue with the offset calculation.  Not 100% sure if this will fix the problem for you.
One way of seeing this better is to chance the second param of 'mTiles->beginTiles' to true.
This will force texture smoothing and miscalculations will show up a blurry text, rather than the odd funky line.  If the calculation is correct then no funky likes should mean no blurred text either.

**Comment by codeservice** [comment]
If I change text field y coordinate I can see broken pixels changing position too. If I scroll text distortion can disappear and reappear in other place. It depends on coordinates. Spent some time trying round positions, it solving one problem, creates another broken glyphs. I'll try shaders, maybe this will increase calculation precision.

**Comment by codeservice** [comment]
I did try smooth text already, yes it makes damaged pixels blurry and less visible. I am using old rendering way without smoothing and all pixels position accurate and text looks sharp. I can't achieve the same with tiles. I have submitted app with this old rendering option and can show you link if you like, here you can check how bitmap rendering accurate compare to tiles. Problem only I can't rotate text like with tiles and rendering process slower and CPU costly, frame rates drops significantly. I want to use tiles only problem with accuracy.

**Comment by hughsando** [comment]
I was thinking the smooth text as a way to test if this was fixed, more than using it as a solution.
Did you try the nme patch?

**Comment by codeservice** [comment]
I will try today. Don't have access to my mac book now. Let you know if
this works well.
I know in open GL exists option glHint(GL_PERSPECTIVE_CORRECTION_HINT,
GL_NICEST);
I am going try this too.

**Comment by codeservice** [comment]
Tested it. It works! shader with "precision highp float;" and new grid rounding gives perfect result, can't find even single deformed tile. Text sharp and looks perfect. Thank you!

In addition increasing shader precision makes 3D content looks better and I dont see any significant fps drops. Thinking maybe it can be good idea bind stage.quality to this value. 

Didnt test on android yet, dont think this will brake anything here.

**Comment by hughsando** [comment]
Some android devices do not even support highp, and others perform worse.
I guess the apple devices should be easy enough to test up front, given a
certain set of shaders.
But some programmatic control seems like a good idea.

**Comment by codeservice** [comment]
Agree android special :( I'll exclude it for android and check if any other
issues with highp on different platforms.

**Comment by hughsando** [comment]
The precision is only for gels - so I guess that only leaves apple.
Unless you count 'angle', but I'm thinking that would ignore this
specification anyhow.

**Comment by codeservice** [comment]
Dont have mac retina display would be interesting check text here. Limit to
apple as you suggested for now.

**Comment by thomasuster** [comment]
Does this affect drawTiles? I've struggled with a lot of off by one problems in the past that I've mostly left alone.

**Comment by hughsando** [comment]
It is possible the highp will fix tile-offsets when the offsets get large -
maybe in a big scrolling map.

But the alignment code is only for fonts, which are a bit special because
the glyph textures are designed to be 1:1 match with the screen pixels so
perfect alignment is possible.

Tile locations with non-integer scales can be difficult to get right.

**Comment by thomasuster** [comment]
@hughsando Cool, thank you!
