### ISSUE TITLE
Glyph tile software rendering

### ISSUE THREAD

**Issue by codeservice** [haxenme/nme#393]
Is any way to improve software  glyph tile rendering?
Because of scale transformation tiles not perfect here.

I found one simple way to improve it in TileRenderer.cpp:
avoid transformation as mach as possible (solving many my problems), but I am not sure is it best way?

   bool Render(const RenderTarget &inTarget, const RenderState &inState)
   {
      Surface *s = mFill->bitmapData;
      double bmp_scale_x = 1.0/s->Width();
      double bmp_scale_y = 1.0/s->Height();
      // Todo:skew
      bool is_stretch = (inState.mTransform.mMatrix->m00!=1.0 ||
                         inState.mTransform.mMatrix->m11!=1.0) &&
                         ( inState.mTransform.mMatrix->m00 > 0 &&
                           inState.mTransform.mMatrix->m11 > 0  );

```
  for(int i=0;i<mTileData.size();i++)
  {
     TileData &data= mTileData[i];

     BlendMode blend = data.mHasColour ? ( mBlendMode==bmAdd ? bmTintedAdd : bmTinted ):
                                           mBlendMode;
     UserPoint corner(data.mPos);
     UserPoint pos = inState.mTransform.mMatrix->Apply(corner.x,corner.y);
     bool is_tile_stretch = is_stretch && (!data.mHasTrans ||
        (fabs(data.mTransX.x - 1.0f / inState.mTransform.mMatrix->m00) > 1e-6  ||
        fabs(data.mTransY.y - 1.0f / inState.mTransform.mMatrix->m11) > 1e-6));

     if (s->Format()==pfAlpha && !is_tile_stretch && mBlendMode==bmNormal && data.mHasColour /* integer co-ordinate?*/ )
     {
        unsigned int col = inState.mColourTransform->Transform(data.mColour|0xff000000);
        s->BlitTo(inTarget, data.mRect, (int)(pos.x), (int)(pos.y), blend, 0, col);
     }
     else if ( (is_tile_stretch || data.mHasTrans) )
     {
        // Can use stretch if there is no skew and no colour transform...
        if (!data.mHasColour && (!data.mHasTrans) &&  mBlendMode==bmNormal )
        {
           UserPoint p0 = pos;
           pos = inState.mTransform.mMatrix->Apply(corner.x+data.mRect.w,corner.y+data.mRect.h);
           s->StretchTo(inTarget, data.mRect, DRect(p0.x,p0.y,pos.x,pos.y,true));
        }
        else
        {
           int tile_alpha = 256;
           bool just_alpha = (data.mHasColour) &&
                             ((data.mColour&0x00ffffff ) == 0x00ffffff);
           if (data.mHasColour && mBlendMode==bmNormal)
           { 
              tile_alpha = data.mColour>>24;
              if (tile_alpha>0) tile_alpha++;
           }
           // Create alpha mask...
           UserPoint p[4];
           p[0] = inState.mTransform.mMatrix->Apply(corner.x,corner.y);
           if (data.mHasTrans)
           {
              p[1] = inState.mTransform.mMatrix->Apply(
                        corner.x + data.mRect.w*data.mTransX.x,
                        corner.y + data.mRect.w*data.mTransY.x);
              p[2] = inState.mTransform.mMatrix->Apply(
                        corner.x + data.mRect.w*data.mTransX.x + data.mRect.h*data.mTransX.y,
                        corner.y + data.mRect.w*data.mTransY.x + data.mRect.h*data.mTransY.y );
              p[3] = inState.mTransform.mMatrix->Apply(
                        corner.x + data.mRect.h*data.mTransX.y,
                        corner.y + data.mRect.h*data.mTransY.y );
           }
           else
           {
              p[1] = inState.mTransform.mMatrix->Apply(corner.x+data.mRect.w,corner.y);
              p[2] = inState.mTransform.mMatrix->Apply(corner.x+data.mRect.w,corner.y+data.mRect.h);
              p[3] = inState.mTransform.mMatrix->Apply(corner.x,corner.y+data.mRect.h);
           }

           Extent2DF extent;
           extent.Add(p[0]);
           extent.Add(p[1]);
           extent.Add(p[2]);
           extent.Add(p[3]);

           // Get bounding pixel rect
           Rect rect = inState.mTransform.GetTargetRect(extent);

           // Intersect with clip rect ...
           Rect visible_pixels = rect.Intersect(inState.mClipRect);
           if (!visible_pixels.HasPixels())
              continue;

           Rect alpha_rect(visible_pixels);
           bool offscreen_buffer = mBlendMode!=bmNormal;
           if (offscreen_buffer)
           {
              for(int i=0;i<4;i++)
              {
                 p[i].x -= visible_pixels.x;
                 p[i].y -= visible_pixels.y;
              }
              alpha_rect.x -= visible_pixels.x;
              alpha_rect.y -= visible_pixels.y;
           }

           int aa = 1;
           SpanRect *span = new SpanRect(alpha_rect,aa);
           for(int i=0;i<4;i++)
              span->Line00(
                   Fixed10( p[i].x, p[i].y  ),
                   Fixed10( p[(i+1)&3].x, p[(i+1)&3].y) );

           AlphaMask *alpha = span->CreateMask(inState.mTransform,tile_alpha);
           delete span;

           float uvt[6];
           uvt[0] = (data.mRect.x) * bmp_scale_x;
           uvt[1] = (data.mRect.y) * bmp_scale_y;
           uvt[2] = (data.mRect.x + data.mRect.w) * bmp_scale_x;
           uvt[3] = (data.mRect.y) * bmp_scale_y;
           uvt[4] = (data.mRect.x + data.mRect.w) * bmp_scale_x;
           uvt[5] = (data.mRect.y + data.mRect.h) * bmp_scale_y;
           mFiller->SetMapping(p,uvt,2);

           // Can render straight to surface ....
           if (!offscreen_buffer)
           {
              if (s->Format()==pfAlpha)
              {
                 if (data.mHasColour)
                 {
                    ARGB col = inState.mColourTransform->Transform(data.mColour|0xff000000);
                    mFiller->SetTint(col);
                 }
                 mFiller->Fill(*alpha,0,0,inTarget,inState);
              }
              else if (data.mHasTrans && !just_alpha)
              {
                 ColorTransform buf;
                 RenderState col_state(inState);
                 ColorTransform tint;
                 tint.redMultiplier =   ((data.mColour)   & 0xff) * one_on_255;
                 tint.greenMultiplier = ((data.mColour>>8) & 0xff) * one_on_255;
                 tint.blueMultiplier =  ((data.mColour>>16)  & 0xff) * one_on_255;
                 col_state.CombineColourTransform(inState, &tint, &buf);
                 mFiller->Fill(*alpha,0,0,inTarget,col_state);
              }
              else
                 mFiller->Fill(*alpha,0,0,inTarget,inState);
           }
           else
           {
              // Create temp surface
              SimpleSurface *tmp = new SimpleSurface(visible_pixels.w,visible_pixels.h, pfARGB);
              tmp->IncRef();
              tmp->Zero();
              {
              AutoSurfaceRender tmp_render(tmp);
              const RenderTarget &target = tmp_render.Target();

              if (s->Format()==pfAlpha && data.mHasColour)
              {
                 ARGB col = inState.mColourTransform->Transform(data.mColour|0xff000000);
                 mFiller->SetTint(col);
              }


              mFiller->Fill(*alpha,0,0,target,inState);
              }

              tmp->BlitTo(inTarget, Rect(0,0,visible_pixels.w,visible_pixels.h),
                      visible_pixels.x, visible_pixels.y,
                     just_alpha ? bmAdd : blend, 0, data.mColour | 0xff000000);

              tmp->DecRef();
           }

           alpha->Dispose();
        }
     }
     else
        s->BlitTo(inTarget, data.mRect, (int)(pos.x), (int)(pos.y), blend, 0, data.mColour);
  }

  return true;
```

   }

};

**Comment by hughsando** [comment]
Bit hard to pick your changes here.
The software front should generally align with the off-screen buffer so there should not be a transformation.  And if there is a tiny transformation, it should only look a tiny bit different.
So maybe you have found one to two bugs here.  I just tried a few things with cacheAsBitmap and they seemed ok.  Any hint on how to see this?

I am currently going over the software rendering, so I would like to make sure this works.

**Comment by codeservice** [comment]
New glyph tile rendering using scale matrix 2x2 and software rendering will involve transformation. Old way just draw pixels without transformation at all. After transformation some glyphs can be cut of from bottom or color of some glyphs shifted to more gray specter, text field can look like diagonal waves of dark and gray glyphs in multi line text.

To reproduce this issue draw multi line text text to bitmap. Trick don't make text to big as bigger text as less visible transformation defects. Smoothing makes this effect less visible, I disabled it. I don't use any extra transformation in my code. I think if you try scale small text many glyph will be cut of from bottom.

**Comment by codeservice** [comment]
One more related issue forget to mentioned. In software tile rendering if
final matrix looks like [1.0000000001, 0, 0, 1.000000001] no reason run
transformation code, I think its exactly what happen to tile glyph it will
make text rendering slower then older version.

And forget to include code:

var tfrm = new TextFormat("_sans", 8);
var tf = new TextField();
tf.defaultTextFormat = tfrm;
tf.autoSize = TextFieldAutoSize.LEFT;
tf.width = 70;
tf.text = " aa ii ll cc pp rr IIllFFEE test3 test4 \ntest5 test6 test7
test8 test9";
tf.multiline = true;

var mt: Matrix = new Matrix(1.5, 0, 0, 1.5);
var bmd: BitmapData = new BitmapData(Math.round(tf.width*mt.a),
Math.round(tf.height*mt.d));
bmd.draw(tf, mt);
var bm: Bitmap = new Bitmap(bmd);
addChild(bm);

**Comment by hughsando** [comment]
You are certainly right that the matrix compare should have some tolerance in it.
This should make it faster.  But if there is a rendering glitch, that needs to be solved too - maybe there is a half-pixels offset missing.
I also notice that the scale check in not quite correct.  In the case where data.mHasTrans, it might be the case that the coordinates may multiply out to 1.0, and therefore allow a blit.  Something to look at - maybe I can add a flag to the tiles to say they come from text, and therefore optimize this check.

**Comment by codeservice** [comment]
I found one more issue in software rendering I think grid coordinates adjustment should be disabled and only available for hardware, require check target isHardware then use grid.  Do you think this fix offset?

(Couple hours ago answered  on email, but for some reason I dont see it in conversation list, posted my response again)

**Comment by codeservice** [comment]
I found one more issue in software rendering I think grid coordinates adjustment should be disabled and only available for hardware, require check target isHardware then use grid.

**Comment by hughsando** [comment]
I think it should probably be there, and there is probably something I need
to do in the software tile renderer - maybe it made some assumptions about
the old transform code.

**Comment by codeservice** [comment]
I remember old code simply use blit to render on surface:
tile.mSurface->BlitTo(clipped, tile.mRect, p.x, p.y, bmTinted, 0, tint);
where p.x and p.y must be calculated with all required transformations
before this blit call..
It worked well except with rotations.

**Comment by hughsando** [comment]
I've just added https://github.com/haxenme/nme/commit/c0f83a9b2bd3106480765fe138a60eb98200b03e for this.
There were 2 problems - one was a bad geometry offset when using the 'aa' logic.  The other prevented blit from being used in scaled text fields.

**Comment by codeservice** [comment]
Checked this on one app where I am using softw. rendering and scaling a
lot. It works perfectly!
