### ISSUE TITLE
Documentation about stable versions

### ISSUE THREAD

**Issue by ex** [haxenme/nme#396]
I'm having trouble using latest versions of Haxe, hxcpp, and nme to compile on windows. Can we have documentation about the latest stable version tested on any platform? The wiki landing page also has a lot of 404 links.

**Comment by thomasuster** [comment]
@ex What troubles are you having?

**Comment by ex** [comment]
@thomasuster there was some C++ classes with errors on hxcpp, I maintain my own haxe and hxcpp versions though, so maybe some path issues were present. I'll try again on a fresh computer with latest versions of everything.

**Comment by ex** [comment]
Using latest Haxe from nightly builds: bc173ef
latest build from NME Host: 5.6.50
using github version of hxcpp: https://github.com/HaxeFoundation/hxcpp/commit/0b4d537f8b8c73943800705d997063116eb742bc
The sample is crashing on Windows 10:
````
Unhandled exception at 0x6BF0C0BB (neko.dll) in DisplayingABitmap.exe: 0xC0000005: Access violation reading location 0x00000140.

 	neko.dll!6bf0c0bb()	Unknown
 	[Frames below may be incorrect and/or missing, no symbols loaded for neko.dll]	
 	neko.dll!6bf0be15()	Unknown
 	std.ndll!6130227e()	Unknown
>	DisplayingABitmap.exe!__hxcpp_get_proc_address(String inLib, String full_name, bool inNdllProc, bool inQuietFail) Line 657	C++
 	DisplayingABitmap.exe!__loadprim(String inLib, String inPrim, int inArgCount) Line 717	C++
 	DisplayingABitmap.exe!cpp::Lib_obj::load(String lib, String prim, int nargs) Line 30	C++
 	DisplayingABitmap.exe!nme::Loader_obj::loaderTrace(String inStr) Line 143	C++
 	DisplayingABitmap.exe!nme::Loader_obj::tryLoad(String inName, String func, int args) Line 171	C++
 	DisplayingABitmap.exe!nme::Loader_obj::load(String func, int args) Line 109	C++
 	DisplayingABitmap.exe!nme::utils::ByteArray_obj::__init__() Line 257	C++
 	DisplayingABitmap.exe!__boot_all() Line 675	C++
 	DisplayingABitmap.exe!WinMain(void * hInstance, void * hPrevInstance, char * lpCmdLine, int nCmdShow) Line 86	C++
 	[External Code]	
````

**Comment by hughsando** [comment]
Looks like it is finding neko's std.ndll, rather than hxcpp's one.

Hxcpp has actually moved away from dlls/ndlls for the standard library, so
should not be seeing much more of this issue.

Might be that the hxcpp dlls need a rebuild via a "neko build.n" in
$HXCPP/project

You can set the environment variable "HXCPP_LOAD_DEBUG", and it should
print out where it is looking.

**Comment by ex** [comment]
@hughsando thanks! windows is working with these versions
````
Haxe from nightly builds: bc173ef
latest build from NME Host: 5.6.50
hxcpp SHA-1: 0357701a0c90109dfb73567517c311bbf0a0ca5f
and rebuilding with $HXCPP/project> neko build.nv
````
