### ISSUE TITLE
SimpleButton collision

### ISSUE THREAD

**Issue by madrazo** [haxenme/nme#397]
We have some buttons that used to work fine on legacy but not in nme, because the Events are not been triggered.

It is a similar issue as in
https://github.com/openfl/openfl/issues/1020

If we draw a rectangle on each state, it works ok
overState.graphics.beginFill(0xEEEEEE, 1);
overState.graphics.drawRect(0, 0, this.width, this.height);
overState.graphics.endFill(); 

so it seems like an issue with the hit test.
Thanks

**Comment by hughsando** [comment]
I think I need a bit more to go on.. The following code seems to work:
```
import nme.display.*;

class Test extends Sprite
{
   public function new()
   {
      super();

      var bmp = new BitmapData(50,50,true,0xff00ff00);
      var bitmap = new Bitmap(bmp);
      var but = new SimpleButton(bitmap,bitmap, bitmap, bitmap);
      but.x = but.y = 100;
      but.addEventListener( nme.events.MouseEvent.MOUSE_OVER, function(_) trace("MOUSE_OVER!") );
      but.addEventListener( nme.events.MouseEvent.CLICK, function(_) trace("CLICK!") );
      addChild(but);
   }
}
```

**Comment by madrazo** [comment]
I see. In SimpleButton constructor, we use objects that extend from "Sprite", instead of Bitmap. 
These sprites have other objects that also extend from Sprite as children and drawn by drawTiles in the graphics of the children..

Not sure why this was working on Legacy, Maybe the hit test is considered with drawTiles. I will give a check, but attaching the Bitmap as child or the drawRect method seems to be working enough so please consider this a very low priority issue.

**Comment by thomasuster** [comment]
@madrazo Would you push a test project to github some where to show the problem?

**Comment by madrazo** [comment]
@thomasuster yes. I will take some to isolate the issue.

**Comment by madrazo** [comment]
The workaround of beginFill has a problem. When recycling the sprites, the collision area behaves weird, like only the bottom of the area detects the hit. 

Adding the Bitmap, as in Hugh's code, seems to work much better (setting the bitmap visible but with alpha 0).

I still want to isolate this code to make it work with drawtiles as in legacy.

**Comment by madrazo** [comment]
Ok, got the code isolated. Thanks.

```

import nme.display.*;

class Main extends Sprite {
public function new () {
      super ();
      var bmp = new BitmapData(50,50,true,0xff00ff00);
#if false
      #if false
      //this one works
      var s = new Bitmap(bmp);
      #else
      //this also works
      var bitmap = new Bitmap(bmp);
      var s = new Sprite();
      s.addChild(bitmap);
      #end
#else
     //this one does not work
      var s = new Sprite();
      var tileData = new Array<Float>();
      var count:Int = 0;
      var tileSheet = new nme.display.Tilesheet( bmp );

      var px:Float = 0; 
      var py:Float = 0; 
      var id:Float = tileSheet.addTileRect(new nme.geom.Rectangle(0,0,50,50), new nme.geom.Point(0,0));
      tileData[count++] = px;
      tileData[count++] = py;
      tileData[count++] = id;
      var smooth:Bool = false;
      var flags:Int = 0; 
      tileSheet.drawTiles( s.graphics, tileData, smooth, flags, count );
#end
      var but = new SimpleButton(s, s, s, s);
      but.x = but.y = 100;
      but.addEventListener( nme.events.MouseEvent.MOUSE_OVER, function(_) trace("MOUSE_OVER!") );
      but.addEventListener( nme.events.MouseEvent.CLICK, function(_) trace("CLICK!") );
      addChild(but);
}


```

**Comment by madrazo** [comment]
Now that I think of it. The current behavior can be better to control the collision area, by adding the (alpha 0) Bitmap as child of s. I can use the same BitmapData for all the collision Bitmaps anyway.

**Comment by hughsando** [comment]
So the problem I think is the tile-data not hit-testing correctly, or maybe
not hit-testing in the button situation.
I think it is usual to draw a solid rect with alpha=0 in the button case.
I guess you want to use the minimum resources possible.
beginFill(0,0);
drawRect(0,0,w,h);

**Comment by madrazo** [comment]
Closing but maybe documennted as a difference with openfl legacy
