### ISSUE TITLE
DisplayObjects destructor

### ISSUE THREAD

**Issue by codeservice** [haxenme/nme#399]
I placed printf("*\n") in
DisplayObject::~DisplayObject() and DisplayObjectContainer::~DisplayObjectContainer() 

Next step in hx code I create child and container, add child to container, add container to stage.
Then remove everything in reverse order, set display objects and containers to null and call garbage collector.

I didn't see even single printf *
If destructor not calling it could be problem for applications where display objects creating and destroying actively.

**Comment by thomasuster** [comment]
@codeservice Wouldn't this not get called until GC runs? Maybe allocate 1000 new Rects each frame after that and see if printf shows up?

**Comment by codeservice** [comment]
I have tested this printf * on big project where I dynamically creating and
destroying sprites, didnt see even single star.
Also did forcibly run GC, same result, no stars.

P.S. I found way to have less damage because of this issue.  Always clean
sprite graphics before removing object from stage.

**Comment by thomasuster** [comment]
@codeservice I think most things subclass DisplayObject, did you try sticking a print inside Sprite::~Sprite()?

**Comment by codeservice** [comment]
I think subclass destructor should call base class destructor. I'll check any way. What I think is happening display object has one extra reference that is never incrementing to 0 value. When it 0 destructor will trigger.

**Comment by codeservice** [comment]
Hmm, I cant find Sprite class in cpp.
We have DisplayObjectContainer->DisplayObject->Object
All references logic declared in Object class.

**Comment by thomasuster** [comment]
`/** @private */ private var nmeChildren:Array<DisplayObject>;`
In removeChild  nmeChildren never seems to remove the child, am I wrong?

**Comment by codeservice** [comment]
I see child removing from array when you set it

public function removeChild(child:DisplayObject):DisplayObject
{
   var c = nmeGetChildIndex(child);

   if (c >= 0)
   {
      child.nmeSetParent(null);


...

function nmeSetParent(inParent:DisplayObjectContainer) {
   if (inParent == nmeParent)
      return inParent;

   if (nmeParent != null)
      nmeParent.nmeRemoveChildFromArray(this);

**Comment by codeservice** [comment]
Issue somewhere in number of incRef and decRef. Should be equal.

**Comment by hughsando** [comment]
Gc tests can be tricky, because some references still linger on the stack.
In the unit tests, I try to solve this by making sure the allocation
happens deeper down the stack, via:
https://github.com/HaxeFoundation/hxcpp/blob/master/test/haxe/gc/TestGC.hx#L22

This may help get the result.  I could also add an explicit "dispose" like
the BitmapData, which can clear the haxe reference to the object without
the need for a GC.

**Comment by hughsando** [comment]
I missed most of this thread before my last reply - sounds like a problem.

**Comment by codeservice** [comment]
Maybe option avoiding GC make sense. I directly call GC and nothing
happened. Which lead to unpredictable behaviour for app. I simply dont know
when GC clean it for me or maybe even never clean it.

**Comment by codeservice** [comment]
I did the same test on Mac and now I see printf *
Console display log * after 10-15 seconds of active app using. Don't underst why I didn't have it on Windows.

**Comment by codeservice** [comment]
I am closing this as it not clearly describing the issue.
