### ISSUE TITLE
ios toolchain: Display Name not from "title"

### ISSUE THREAD

**Issue by madrazo** [haxenme/nme#408]
The final app name seems to be taken from
`<app file="name"`
instead from
`<meta title="name"`
On Android, it uses the one from "title" correctly.

**Comment by madrazo** [comment]
I see some differences between legacy's and nme's PROJ-Info.plist that may fix this?

https://github.com/haxenme/nme/blob/master/templates/ios/PROJ/PROJ-Info.plist#L8

https://github.com/openfl/lime/blob/2.9.1/legacy/templates/iphone/PROJ/PROJ-Info.plist#L8

**Comment by hughsando** [comment]
Yes, I think the CFBundleName should be $(PRODUCT_NAME), but the CFBundleDisplayName should be the ::APP_TITLE::.
