### ISSUE TITLE
ColorTransform regression with BitmapData transparency

### ISSUE THREAD

**Issue by jskuse** [haxenme/nme#409]
I updated our project to the most recent NME today (having not done so for approximately 3 months) and found one of our bitmap text rendering paths was broken, appearing as solid blocks with no transparency. 

It looks to me like a change to ColorTransform behaviour is responsible. 

If you take the following example, we're creating a transparent BitmapData. Without the ColorTransform nothing is visible, but once you apply it you get a solid yellow block almost as if the alphaOffset is set to 255. I've tried explicitly setting alphaOffset to 0 with no luck. I had a quick look to try and trace what's going on through NME but I had no luck, so any hints as to what might of changed on this front in the last few months would be greatly appreciated.

```
import nme.display.BitmapData;
import nme.display.Bitmap;

class Main extends nme.display.Sprite {
	public function new () {
		super();
		stage.color = 0xFF0000;
		var bitmapData = new BitmapData(100, 100, true, 0x000000FF);
		var bitmap = new Bitmap (bitmapData);
		var c = new nme.geom.ColorTransform();
		c.greenOffset = 255;
		bitmap.transform.colorTransform = c;
		addChild (bitmap);
		bitmap.x = (flash.Lib.current.stage.stageWidth - bitmap.width) / 2;
		bitmap.y = (flash.Lib.current.stage.stageHeight - bitmap.height) / 2;
	}
}
```

**Comment by hughsando** [comment]
Hey - sorry about the late reply.
I'm pretty sure the change is the one to pre-multiplied alpha by default.
Colour transforms are complicated by this.
You can reverse this now with -DNME_NOPREMULTIPLIED_ALPHA.
I'm looking at fixing this properly.

**Comment by jskuse** [comment]
Thanks @hughsando - absolutely no problem, I'm always hugely grateful for your time. 

Today's my first day back at it and having sussed out that you meant to build *NME* (rather than the project) with that flag things seem to be rendering as expected (albeit I haven't done a full test yet). So that's excellent.

If you have time (and of course no problem if you don't), I wonder if you might be able to help me with a few semi-related queries:

1. Would you regard the current GIT version of NME stable enough to use in production? We've been using an outdated custom fork for a while, but I'd ideally like to update our NME (as well as Haxe and HXCPP) during this quiet period at the start of the year. 

2. Are you still advocating / moving towards doing toolkit builds by default rather than the static approach? I'm just wondering if as part of this update process it would be advisable to move our build chain over to doing toolkit builds.

**Comment by hughsando** [comment]
Yes, the git NME version is the best version at the moment I think.
Haxe 3.4 is due for release in about a week, so I highly recommend testing out the rc2 or overnight build a report any regressions.  Once this is out, this would be the logical haxe version to use for a while.

Toolkit build is the way to go.  This build is itself a static build, so it covers both these options.
I also recommend tying the HXCPP_COMPILER_CACHE if you have not done so.  This involves pointing this variable (say, by setting it in your .hxcpp_config.xml file) at a separate directory to store the object files.

**Comment by thomasuster** [comment]
@jskuse Is this still an issue for you?

**Comment by thomasuster** [comment]
Closing, stale.
