### ISSUE TITLE
iOS audio interruptions cut off one shot sounds

### ISSUE THREAD

**Issue by jskuse** [haxenme/nme#410]
This is a significant issue for us, so I'm adding an issue just so it doesn't get lost. 

The reversion in #406 causes a regression whereby whereby one shot sounds are cut off if audio is interrupted in iOS (the control panel is slid down / the alarm rings / a phone call is received). Looping sounds are still fine. Hugh has noted what he'd like to do to fix this in the thread under #406.

**Comment by thomasuster** [comment]
Looks like @hughsando merged something for this.
