### ISSUE TITLE
Windows Running Error Since 5.6.57 

### ISSUE THREAD

**Issue by hoseyjoe** [haxenme/nme#419]
When running windows compiled executable I started receiving a "Could not find primitive nme_time_stamp__prime" after installing 5.6.58 ->5.6.60 releases

5.6.57 was last known working version

**Comment by thomasuster** [comment]
Related to this? https://github.com/haxenme/nme/commit/0a4952b97a7975623555d04e261753e18227c149

**Comment by madrazo** [comment]
Maybe just rebuilding tools/nme solves the problem (`haxe compile.hxml`), but you could also try rebuilding the libs (`cd project`, `neko build.n clean` , `neko build.n`).

**Comment by hughsando** [comment]
I had been testing with a more recent version of haxe, so I missed this one.
I moved some extra code from haxe into nme, so I hope this fixes things.

**Comment by hoseyjoe** [comment]
This worked for me in 5.6.61
