### ISSUE TITLE
[Android] incorrect Capabilities.screenResolutionX and Y on target 19+ fullscreen

### ISSUE THREAD

**Issue by madrazo** [haxenme/nme#421]
The Navigation bar hides correctly (SYSTEM_UI_FLAG_IMMERSIVE_STICKY flags in GameActivity.java), but the screen resolution value is still the one with the Navigation Bar. 

This can be solved by using getRealMetrics instead of getMetrics (GameActivity.java).

**Comment by thomasuster** [comment]
I have an issue where if the the user watches an ad they will see the navigation bar and it won't go away until they minimize and maximize manually, is this that issue?

**Comment by madrazo** [comment]
No, it is just for retrieving the whole screen data dimensions. We use this in the resize event. 
In my testing device, the navigation bar looks transparent and hides when swiping. I have not tested with adds, maybe it needs to call a hide function.

**Comment by madrazo** [comment]
@thomasuster I have reproduced this issue when the facebook login window is closed.

**Comment by madrazo** [comment]
@thomasuster Should be OK now https://github.com/haxenme/nme/pull/422/files
