### ISSUE TITLE
TextField textHeight always returns 1 when parent is scaled other than 1

### ISSUE THREAD

**Issue by man2** [haxenme/nme#423]
tested on cpp target using nme: [5.6.4]

**Comment by man2** [comment]
apparently there is a bug with TextField's height and textHeight when parent's container is scaled. Trying to fix this now

**Comment by man2** [comment]
![textfield_bug](https://cloud.githubusercontent.com/assets/167375/21465634/40606df4-c9e6-11e6-9dcc-22464fdece5c.png)

**Comment by hughsando** [comment]
I'm having trouble reproducing this.  It would be great if you could post a simple sample.
For example, the following seems to work:
```
import nme.display.*;
import nme.text.*;
import nme.geom.*;

class Test extends Sprite
{
   public function new()
   {
      super();

      var t = new TextField();
      t.x = 100;
      t.y = 100;

      var fmt = new TextFormat();
      fmt.size = 10;
      t.defaultTextFormat = fmt;

      t.width = 400;
      t.multiline = true;
      t.wordWrap = true;
      t.autoSize = TextFieldAutoSize.LEFT;
      t.multiline = true;

      var words = ["a", "qeqwe", "qerqwrqw4rw", "iiiii", "......", "cccc" ];
      var textArray = new Array<String>();
      for(i in 0...100)
         textArray.push( words[ Std.int(Math.random() * words.length) ]);
      t.text = textArray.join(" ");
      addChild(t);

      scaleX = scaleY = 0.5;
      trace(t.textHeight);
      scaleX = scaleY = 2.5;
      trace(t.textHeight);
   }
}
```
I wonder if the font is a bitmap font, and does not like displaying at a high or low resolution, or something like that.

**Comment by man2** [comment]
hi Hugh, thanks for helping on this. 

I'm having difficulties reproducing this as well, it happens on TextField and ttf font i can assure you that

I'm working with stablexui. I think that's the source of problem. But my game which was compiled with older nme ( around year 2013 ) worked just fine with stablexui. It happens only on nme 5+, cause I need to recompile my game using newer google play services :(

I will keep trying to reproduce this kind of bug

**Comment by man2** [comment]
think it must be connected with scrollRect feature that I'm using on stablexui

**Comment by man2** [comment]
problem is with my font. closing this issue
