### ISSUE TITLE
Image Loader Get Unreconized File

### ISSUE THREAD

**Issue by madrazo** [haxenme/nme#425]
Got this issue on NME (tested on Android)
http://community.openfl.org/t/image-loader-get-unrecognized-file/1760/3

```
        m_loader = new Loader();
        m_request = new URLRequest( url );
        try {       
            m_loader.load( m_request );
        } 
        catch(error:String) { 
            trace(error); //Image Loader Get Unreconized File
            return;
        }
```

The URL needs to end on the file extension to succeed.
Josua's workaround works.

My url is something like
`https://www.example.com/dummy.jpg?param=foo&param2=bar`

**Comment by thomasuster** [comment]
Hey @madrazo , is this still an issue? Related... https://github.com/haxenme/nme/issues/464

**Comment by codeservice** [comment]
This maybe fixed by this : https://github.com/haxenme/nme/pull/542

**Comment by madrazo** [comment]
looks good
