### ISSUE TITLE
customizing android's application tag in AndroidManifest

### ISSUE THREAD

**Issue by man2** [haxenme/nme#427]
add support to customize android's application tag in AndroidManifest whether from NMML file or from extension

I have tried adding tag application android:name="MyApp" into extension's AndroidManifest without success. 

Can't find a way of customizing application tag from nmml either. So I have to edit my AndroidManifest.xml directly and recompile using ant.

**Comment by hughsando** [comment]
You can add data into the application tag with the 'appHeader' tag:
```
  <android>
     <appHeader value='android:someKey = "someValue"' />
     <appHeader value='android:someOtherKey ="someOtherValue"' />
  </android>
```
Will this work for you?

**Comment by thomasuster** [comment]
@man2 Feel fee to reopen if @hughsando 's solution did not work.
