### ISSUE TITLE
Feature request: integration with hxtelemetry

### ISSUE THREAD

**Issue by madrazo** [haxenme/nme#451]
Now that hxtelemetry seems to be working again with hxcpp, try it with NME.

**Comment by madrazo** [comment]
![nmetelemetry](https://cloud.githubusercontent.com/assets/5659074/26174836/4472a1c2-3b16-11e7-9743-ad4b52cea035.png)
@hughsando  @jcward 
hxtelemetry seems to be working. 
Sometimes "Allocations" are not shown.  
I see that the garbage collection memory goes up and up
TODO: add a configuration object to the hxtelemetry constructor

**Comment by jcward** [comment]
Is it a good sign or bad sign that I'm always delightfully surprised to see hxscout working! :D

**Comment by madrazo** [comment]
Now you can set configuration parameters from the xml using setenv
```
	<setenv name="TELEMETRY_HOST" value="localhost"/>
	<setenv name="TELEMETRY_ALLOCATIONS" value="true"/>
```

It can be improved to use the openfl `config:hxtelemetry` tag or a define with macros but I'm closing this for now.
