### ISSUE TITLE
Visual Studio Code Debug Integration

### ISSUE THREAD

**Issue by madrazo** [haxenme/nme#453]
We really need breakpoints in an IDE for C++ similar to FlashDevelop target with Flash target (we dont want to use the Flash target anymore to debug).

Support for VS Code seems to be experiental
https://github.com/jcward/vscode-hxcpp-debug
and
https://github.com/vshaxe/vshaxe-debugadapter
but we would appreciate it to discussion about this working or the alternatives. 

Also, on-screen debug information such as GC and Profiler haxe classes would be useful, and how to tune the GC. Thanks

**Comment by madrazo** [comment]
Tried https://github.com/jcward/vscode-hxcpp-debug
Instaled as in the README.
Modified the vscode-hxcpp-debug\test openfl\.vscode\launch.json to add the configurations
```
		{
			"name": "NME Windows: Build and Debug",
			"runtimeExecutable": "${execPath}",
			"args": [
				"compilePath=${workspaceRoot}",
				"compileCommand=nme -debug -DHXCPP_DEBUGGER -verbose",
				"runPath=${workspaceRoot}/Export/windows/DisplayingABitmap/",
				"runCommand=DisplayingABitmap.exe",
				"runInTerminal=false"
			],
			"type": "hxcpp",
			"request": "launch",
			"stopOnEntry": true
		},
		{
			"name": "NME Windows: Debug",
			"runtimeExecutable": "${execPath}",
			"args": [
				"runPath=${workspaceRoot}/Export/windows/DisplayingABitmap/",
				"runCommand=DisplayingABitmap.exe",
				"runInTerminal=false"
			],
			"type": "hxcpp",
			"request": "launch",
			"program": "",
			"stopOnEntry": true
		},
```

Opening "test openfl" directory and debuging with "NME Windows: Build and Debug" I get the error:
`Cannot read property 'toLowerCase' of undefined`

Compiling from outside with `nme -debug -DHXCPP_DEBUGGER` and debugging with
"NME Windows: Debug" seems to work.

I had tried to remove a "toLowerCase" that is inside of vscode-hxcpp-debug/src/Main.hx  (https://github.com/jcward/vscode-hxcpp-debug/blob/9d10f079f58bac5479279d40bf95cf4729938e9c/src/Main.hx#L312) but the error still happens, so it may be something about the NME tools. (It does not appear with openfl)

**Comment by jcward** [comment]
I'll try to test it with NME soon -- the `toLowerCase` error shouldn't be affected by target.

**Comment by madrazo** [comment]
@jcward  thanks

**Comment by jcward** [comment]
@madrazo - I've added a `test nme` to vscode-hxcpp-debug -- see it [here](https://github.com/jcward/vscode-hxcpp-debug/tree/master/test%20nme). It seemed to work fine with linux64, hxcpp 3.4.90, haxe 3.4.2, nme 5.7.1. Build and launch, breakpoints, step through. Let me know if it doesn't work on your end.

**Comment by madrazo** [comment]
Thanks. With VSCode 1.12.2 (Windows) and almost-latest NME I still get the error "Cannot read property 'toLowerCase' of undefined" as in the image. I will try with your configuration instead.

![image](https://cloud.githubusercontent.com/assets/5659074/26162631/e311d868-3aec-11e7-9ab4-ddff7d985657.png)

**Comment by madrazo** [comment]
Tried first with the VSCode "insider" version: 
The 'toLowerCase' error is gone.
The 'Debug adapter process has terminated...' error still appears when selecting "Build and Debug" configuration.
Building "nme test" from cmd and just selecting "Debug" configuration in VSCode seems to work as expected for some time and then process is terminated. 

mm, i'll give a try to VSCode 1.8.1

**Comment by jcward** [comment]
@madrazo -- hmm. I was testing with vscode 1.11.1 this morning. I should try 1.12.1. I'll try to test on windows soon, too.

**Comment by madrazo** [comment]
@jcward With 1.8.1 I also couldn't "Build and Debug" , but "Debug" seems more stable

**Comment by madrazo** [comment]
I can  "Build and Debug" openfl test, so it may be something in the nme tools for windows, for example when calling an external command like when attaching the windows icon @hughsando 

@jcward do you know if there a way to see more information about those pop-up errors?

**Comment by jcward** [comment]
@madrazo which errors, exactly? The "debug adapter terminated" errors -- perhaps look for the `adapter.log` file I mentioned above. Sometimes if the app under test crashes, it can crash the debug adapter. Sometimes the debug adapter itself has bugs. :)

**Comment by madrazo** [comment]
Thanks. Couldn't spot anything important on adapter.log :(

They both start identically like
```
1495040564.39: Reading 241 bytes...
1495040564.39: {"command":"initialize","arguments":{"adapterID":"hxcpp","pathFormat":"path","linesStartAt1":true,"columnsStartAt1":true,"supportsVariableType":true,"supportsVariablePaging":true,"supportsRunInTerminalRequest":true},"type":"request","seq":1}
1495040564.39: Got command: initialize
1495040564.39: Initializing... _run_process is: null
1495040564.39: ----> Sending 83 bytes:
1495040564.39: {"body":{},"command":"initialize","success":true,"request_seq":1,"type":"response"}
1495040564.441: Reading 463 bytes...
1495040564.441: {"command":"launch","arguments":{"name":"Windows: Build and Debug","runtimeExecutable":"C:\\Program Files (x86)\\Microsoft VS Code\\Code.exe","args":["compilePath=d:\\bamtang\\git\\test openfl","compileCommand=nme build windows -debug -DHXCPP_DEBUGGER -verbose","runPath=d:\\bamtang\\git\\test openfl/Export/windows/cpp/bin/","runCommand=DisplayingABitmap.exe","runInTerminal=false"],"type":"hxcpp","request":"launch","stopOnEntry":true},"type":"request","seq":2}
1495040564.444: Got command: launch
1495040564.444: Launching... proj_dir=null
1495040564.444: Arg compilePath is d:\bamtang\git\test openfl
1495040564.444: Arg compileCommand is nme build windows -debug -DHXCPP_DEBUGGER -verbose
1495040564.444: Arg runPath is d:\bamtang\git\test openfl/Export/windows/cpp/bin/
1495040564.444: Arg runCommand is DisplayingABitmap.exe
1495040564.444: Arg runInTerminal is false
1495040564.444: Compiling...
1495040564.444: ----> Sending 97 bytes:
1495040564.444: {"type":"event","seq":1,"body":{"category":"console","output":"Compiling...\n"},"event":"output"}
1495040564.444: cd d:\bamtang\git\test openfl
1495040564.444: ----> Sending 117 bytes:
1495040564.444: {"type":"event","seq":2,"body":{"category":"console","output":"cd d:\\bamtang\\git\\test openfl\n"},"event":"output"}
1495040564.444: nme build windows -debug -DHXCPP_DEBUGGER -verbose
1495040564.444: ----> Sending 135 bytes:
1495040564.444: {"type":"event","seq":3,"body":{"category":"console","output":"nme build windows -debug -DHXCPP_DEBUGGER -verbose\n"},"event":"output"}
1495040564.445: cmd: nme build windows -debug -DHXCPP_DEBUGGER -verbose
1495040564.445: args: nme|build|windows|-debug|-DHXCPP_DEBUGGER|-verbose
```
but openfl then writes 
`openfl does "Starting: openfl build windows -debug -DHXCPP_DEBUGGER, pid=21552"`
and begins compiling

**Comment by madrazo** [comment]
I got a little more on adapter.log
```
1495041420.026: Reading 241 bytes...
1495041420.026: {"command":"initialize","arguments":{"adapterID":"hxcpp","pathFormat":"path","linesStartAt1":true,"columnsStartAt1":true,"supportsVariableType":true,"supportsVariablePaging":true,"supportsRunInTerminalRequest":true},"type":"request","seq":1}
1495041420.026: Got command: initialize
1495041420.026: Initializing... _run_process is: null
1495041420.026: ----> Sending 83 bytes:
1495041420.026: {"body":{},"command":"initialize","success":true,"request_seq":1,"type":"response"}
1495041420.077: Reading 420 bytes...
1495041420.077: {"command":"launch","arguments":{"name":"Windows: Build and Debug","runtimeExecutable":"C:\\Program Files (x86)\\Microsoft VS Code\\Code.exe","args":["compilePath=d:\\test nme","compileCommand=nme build windows -debug -DHXCPP_DEBUGGER","runPath=d:\\test nme/Export/windows/cpp/bin/","runCommand=DisplayingABitmap.exe","runInTerminal=false"],"type":"hxcpp","request":"launch","stopOnEntry":true},"type":"request","seq":2}
1495041420.077: Got command: launch
1495041420.077: Launching... proj_dir=null
1495041420.077: Arg compilePath is d:\test nme
1495041420.077: Arg compileCommand is nme build windows -debug -DHXCPP_DEBUGGER
1495041420.077: Arg runPath is d:\test nme/Export/windows/cpp/bin/
1495041420.077: Arg runCommand is DisplayingABitmap.exe
1495041420.077: Arg runInTerminal is false
1495041420.077: Compiling...
1495041420.077: ----> Sending 97 bytes:
1495041420.077: {"type":"event","seq":1,"body":{"category":"console","output":"Compiling...\n"},"event":"output"}
1495041420.078: cd d:\test nme
1495041420.078: ----> Sending 100 bytes:
1495041420.078: {"type":"event","seq":2,"body":{"category":"console","output":"cd d:\\test nme\n"},"event":"output"}
1495041420.078: nme build windows -debug -DHXCPP_DEBUGGER
1495041420.078: ----> Sending 126 bytes:
1495041420.078: {"type":"event","seq":3,"body":{"category":"console","output":"nme build windows -debug -DHXCPP_DEBUGGER\n"},"event":"output"}
1495041420.078: cmd: nme build windows -debug -DHXCPP_DEBUGGER
1495041420.078: args: nme|build|windows|-debug|-DHXCPP_DEBUGGER
```

**Comment by madrazo** [comment]
I've tried on a different windows PC, VS Code 1.11.2, and still got the "toLowerCase" error

**Comment by madrazo** [comment]
I gave this another try with the latest git's vscode-hxcpp-debug, hxcpp, hxcpp-debugger, and VS Code 1.13.1, in Windows 10, and I still get the 'Debug adapter process has terminated...' error when trying "Windows: Build and Debug".  I built it from the command line, and only try "Windows: Debug", it started debugging but I could not see the value of the variables. The next time I started it, I saw the  'Debug adapter process has terminated...' message again.

**Comment by thomasuster** [comment]
@jcward @madrazo Any updates here?

**Comment by nulld** [comment]
Did you try this one https://github.com/vshaxe/hxcpp-debugger ? Let me know if you have any trouble with it.

**Comment by nulld** [comment]
@hughsando @thomasuster I think, it can be closed. It works perfectly with vscode:
![image](https://user-images.githubusercontent.com/2820168/101788885-abef4680-3b11-11eb-9083-728f5ec2585b.png)

**Comment by madrazo** [comment]
@nulld thanks for testing
