### ISSUE TITLE
java.lang.UnsatisfiedLinkError: dlopen failed: library "/opt/android-ndk/platforms/android-5/arch-arm/usr/lib/libc.so" not found

### ISSUE THREAD

**Issue by man2** [haxenme/nme#463]
Compile was successful but when running the game, it crashes, catlog error message
java.lang.UnsatisfiedLinkError: dlopen failed: library "/opt/android-ndk/platforms/android-5/arch-arm/usr/lib/libc.so" not found

haxe 3.4.2
hxcpp: [3.4.64]
nme: [5.7.1]

Tried with android ndk r14b and r10e
android sdk 24
tested on android marshmallow

**Comment by man2** [comment]
problem is with google analytics extension

**Comment by thomasuster** [comment]
👍
