### ISSUE TITLE
QUESTION: URLLoader based on old curl (not working on ios, android)

### ISSUE THREAD

**Issue by codeservice** [haxenme/nme#464]
I checked URLLoader its not working on mobile devices. I think because its based on old curl. 
Maybe make sense rebuild URLLoader completely on sockets? in this case no need to support both libs curl and socket.
From other side latest curl using polarssl which is part of hxcpp now and next logical step maybe include curl in hxcpp too? Any ideas?

**Comment by hughsando** [comment]
Yes, I'm leaning that way.  Maybe the raw haxe http(s) class can be use directly, or with suitable callbacks.
Using native versions on ios and android would be ideal too.
The objc externs work quite well now, so ios might be doable in raw haxe.

**Comment by codeservice** [comment]
Sockets work well for me on every platform: mac,win,ios,andr. (I am still
using old way lib, openssl. Its only require few patches for IOS). I like
idea using HTTP haxe class too, only problem it doesn't have some callbacks
now, for example for doing portion download in chunks. Maybe it will be be
added in future haxe versions.
