### ISSUE TITLE
JsPrime with HaxeUI unable to create window

### ISSUE THREAD

**Issue by hoseyjoe** [haxenme/nme#469]
Emscripten works but using attached project compile with "nme test project.xml html5".  Project compiles but throws JS error
hxcpp 3.4.90
nme 6.0.36
Haxeui-nme git
haxeui-core git

`Lib.hx:91: Error creating window: ({
	width : 800, 
	height : 600, 
	flags : 2060, 
	title : NME2, 
	color : 16777215, 
	icon : null
})
TypeError: Cannot convert "Float(30)" to double
Called from http://localhost:6931/Nme.js line 1
Called from http://localhost:6931/Nme.js line 1
Called from http://localhost:6931/Nme.js line 17
Called from http://localhost:6931/Nme.js line 17
Called from http://localhost:6931/Nme.js line 1
Called from http://localhost:6931/Nme.js line 11
Called from http://localhost:6931/Nme.js line 17
Called from http://localhost:6931/Nme.js line 1
Called from http://localhost:6931/Nme.js line 11
Called from http://localhost:6931/Nme.js line 17`

**Comment by hughsando** [comment]
I think this is actually a problem with the haxeui-nme backend.  And a problem with nme because I think I should type some things as `Null<Float>` rather than "Dynamic".
the haxe-ui TextDisplayBase.hx class assigns values from the haxeui style to the nme TextFormat, but the former is a "Variant" enum, not a float.
```haxe
 function getFloat(v:Variant) {
       switch(v) {
          case Float(f): return f;
          default: return 10;
       }
    }

   ...
    format.size = getFloat(style.fontSize);
```

**Comment by hoseyjoe** [comment]
I dont have project and apparently did not attach will remake ticket if it repeats
