### ISSUE TITLE
JS Prime - Accelerometer.hx

### ISSUE THREAD

**Issue by hoseyjoe** [haxenme/nme#470]
I dont have a project I can share hopefully this is easy enough.  Compiling with "nme test project.xml html5" I get the below error.  Emscripten works fine

C:\sdks\Haxe\haxe\lib\nme/6,0,36/nme/sensors/Accelerometer.hx:51: characters 27-35 : Float should be Int

C:\sdks\Haxe\haxe\lib\nme/6,0,36/nme/sensors/Accelerometer.hx:51: characters 27-35 : For function argument 'time_ms'

**Comment by hughsando** [comment]
I think this might have been fixed when I change the haxe.Timer override, which is now in src/haxe/Timer.hx
This used to be conditional on "js", but should not be anymore.
Although I have to tested the js window.setInterval specific code much.

**Comment by hoseyjoe** [comment]
this was resolved between 6.0.36 and 6.0.38
