### ISSUE TITLE
Compiling to Android

### ISSUE THREAD

**Issue by hoseyjoe** [haxenme/nme#480]
Compiling to Android using
hxcpp: [3.4.124] 
nme: [6.0.47] 
Using "Windows 10" I compile with "haxe test app.xml windows" and get:
haxelib run hxcpp Build.xml haxe -DHXCPP_ARMV7="1" -Dactuate="1.8.7" -Dajax="1.1.0" -Dandroid="1" -Dhaxe3="1" -Dhaxe_ver="3.402" -Dhaxeui-core="0.0.0" -Dhaxeui-nme="0.0.0" -Dhaxeui_core="0.0.0" -Dhaxeui_nme="0.0.0" -Dhscript="2.0.7" -Dhxcpp_api_level="331" -Dlime_legacy="1" -Dmobile="1" -Dnme="6.0.47" -Dnme6="1" -Dnme_install_tool="1" -Dnme_ver="6.0.47" -Dopenfl="3.5.0" -Dopenfl_legacy="1" -Dpromhx="1.1.0" -Dsource-header="Generated by Haxe 3.4.2 (git build master @ 890f8c7)" -Dtoolkit="1" -I"bin/nme/android/haxe/" -I"C:\\sdks\\haxe3\\haxe\\lib\\nme/6,0,47/src/haxe/compat/" -I"C:\\sdks\\haxe3\\haxe\\lib\\nme/6,0,47/src/" -I"../API_calls/src/" -I"../NodeTree/src/" -I"../RC_UI/src/" -I"../Squid/src/" -I"src/" -I"C:\\sdks\\haxe3\\haxe\\lib\\hscript/2,0,7/" -I"C:\\sdks\\haxe3\\haxe\\lib\\nme/6,0,47/" -I"C:\\sdks\\haxe3\\haxe\\lib\\haxeui-nme/git/" -I"C:\\sdks\\haxe3\\haxe\\lib\\haxeui-core/git/" -I"C:\\sdks\\haxe3\\haxe\\lib\\hscript/2,0,7/" -I"C:\\sdks\\haxe3\\haxe\\lib\\promhx/1,1,0/src/main/" -I"C:\\sdks\\haxe3\\haxe\\lib\\ajax/git/" -I"C:\\sdks\\haxe3\\haxe\\lib\\actuate/1,8,7/" -I"C:\\sdks\\haxe3\\haxe\\extraLibs/" -I"" -I"C:\\sdks\\haxe3\\haxe\\std/cpp/_std/" -I"C:\\sdks\\haxe3\\haxe\\std/"
Called from neko.vm.Thread::$statics line 1
Called from RunMain::main line 99
Called from RunMain::executeHxcpp line 93
Called from neko.vm.Loader::loadModule line 132
Called from sys.io.Process::$statics line 1
Called from BuildTool::main line 1578
Called from BuildTool::$init line 35
Called from BuildTool::new line 257
Called from BuildTool::buildTarget line 389
Called from Compiler::createCompilerVersion line 332
Called from ProcessManager::readStdout line 175
Called from sys.io.Process::$init line 88
Called from sys.io.Process::new line 99
Uncaught exception - Process creation failure : arm-linux-androideabi-g++
Error: Build failed
Error: IsNewer - source path "bin/nme/android/haxe/cpp/libApplicationMain-v7.so" does not exist

Any idea what I am missing

**Comment by thomasuster** [comment]
neko.vm.Loader::loadModule

**Comment by thomasuster** [comment]
Do you need to build NME for android?

**Comment by hoseyjoe** [comment]
well I could use openfl.  I used to use nme but I have never released an app.  Why do you ask?

**Comment by hoseyjoe** [comment]
Oh you mean "build nme for android".  I was using the nmehost release so much I never considered it was a requirement. I will look into that

**Comment by thomasuster** [comment]
@hoseyjoe Ah yes, I just meant if you were using the dev version you would have to build the android platform if you hadn't. Did you try opening samples/DisplayingABitmap and building that for android?

**Comment by hoseyjoe** [comment]
No, I still need to "build nme for android".  I no longer know how to do that. I think it is with nme-dev but I am getting the tar error since I dont have an application installed, for the command line, that does the tar request as written.  So...Do I use nme-dev to create the android version?

**Comment by hoseyjoe** [comment]
Well here is what I was missing.  Install ndk to C:\sdks\Android\android-ndk-r15b and point hxcpp_config.xml ANDROID_NDK_DIR variableto C:\sdks\Android\.  Otherwise it couldnt find it.  I think it checks the path name.

Then compile with nme test android -toolkit

I guess I dont have to prebuild for android?

**Comment by thomasuster** [comment]
@hoseyjoe If you use -toolkit you no longer need to build the library for android. It compiles the CPP stuff as part of your project. Side note, to cut down on compile times if you have multiple NME projects you can turn on HXCPP_COMPILE_CACHE, some info here. http://snowkit.org/2016/02/15/snow-alpha-2-0-changelog/
