### ISSUE TITLE
DisplayObjectContainer mDirtyFlags not set for childrens with dynamyc update

### ISSUE THREAD

**Issue by codeservice** [haxenme/nme#486]
Below code not working. Rectangle alpha not 0.5 after mouse click on it. I think missing mDirtyFlags set for children in Display.cpp. Same with cacheAsBitmap = true. Maybe because I have  older nme version. 

        var lv1: Sprite = new Sprite();
        //lv1.cacheAsBitmap = true;
        var lv2: Sprite = new Sprite();
        //lv2.cacheAsBitmap = true;

        lv2.addChild(lv1);

        var lv0: Sprite = new Sprite();
        lv0.cacheAsBitmap = true;
        lv0.graphics.beginFill(0);
        lv0.graphics.lineStyle(2, 0, 1);
        lv0.graphics.drawRect(0,0,20,20);
        lv0.graphics.endFill();
        lv1.addChild(lv0);

        addChild(lv2);

        lv0.addEventListener(MouseEvent.MOUSE_DOWN, function(_){
            trace("->");
            lv2.alpha = 0.5;
        });

**Comment by thomasuster** [comment]
Hey there, I think you might be right? I forgot if this is intended or not for cacheAsBitmap. If you remove the `lv0.cacheAsBitmap = true;` then it will work. But I *think* it's intended to work with it on. 🤷‍♂️ , maybe submit a PR if you know the fix?

**Comment by thomasuster** [comment]
He @codeservice , had an issue trying to test your changes. Would you merge https://github.com/haxenme/nme/pull/547 and https://github.com/haxenme/nme/pull/546 in the same diff so I can easily test?

**Comment by codeservice** [comment]
I merged changes into one. Compiler still don’t see changes in Display.h file, trying to compile Display.cpp first. Have no idea why it works this way.
