### ISSUE TITLE
Project default template is trying to find a template

### ISSUE THREAD

**Issue by leocavalcante** [haxenme/nme#488]
```terminal
λ nme create --help
You must specify 'project' or a sample name when using the 'create' command.

Usage:

 nme create project "com.package.name" "Company Name"
 nme create extension "ExtensionName"
 nme create SampleName
```

But

```terminal
λ nme create project "com.leocavalcante.hellonme" "Leo Cavalcante"
Error: Could not find any source directory "project" in [C:\HaxeToolkit\haxe\lib\nme/5,7,1/templates/default]
```

| | |
| --- | --- |
| Windows | 10.0.16251.0 |
| NME CLI | 5.7.1 |

**Comment by thomasuster** [comment]
Try looking in the templates folder for acceptable template to clone. Try this... 'nme create DisplayingABitmap', then try the same thing with a different package. I also just do the first command I sent, and then manually change the package.

**Comment by thomasuster** [comment]
For more help try asking in gitter before heading to bed(we can be a bit slow to respond)

**Comment by leocavalcante** [comment]
Yes, I could create from a sample, but not a "clean slate" project. This isn't a big deal, but I thought on creating a issue since NME CLI isn't doing what it says. Maybe just a `project` template solve this.

**Comment by madrazo** [comment]
Yes, it seems that the only issue is that the template was missing. I have added one based on DisplayingABitmap. By the way, does anybody know which version of FlashDevelop works with NME? 
Thanks
