### ISSUE TITLE
Avoid GL_RGB ?

### ISSUE THREAD

**Issue by madrazo** [haxenme/nme#494]
There are no 24-bit texture format on DirectX and Angle actually expands the data to 32-bit bgrx (https://github.com/google/angle/blob/390208b523ba477f8d6aa6c2b08459169a94c1ae/src/image_util/loadimage.cpp#L434).  PC cards seem to not accept 24bit and maybe it's true for mobile.  

Would be better to actually work with 32 bit textures on software or would be better just to let OGL/Angle expand the data automatically?

Thanks!

EDIT this might be irrelevant if using compressed texture formats instead?

**Comment by hughsando** [comment]
I think your original idea of keeping it 24 bits in software and expanding on transfer if the best idea.  This keeps the memory footprint slightly smaller, and the transfer usually only needs to be done once.  Nme 
 already has code for doing the conversion.
This also solves the issue with an odd number of pixels.
