### ISSUE TITLE
Android black screen app

### ISSUE THREAD

**Issue by codeservice** [haxenme/nme#505]
Successfully compiled app using haxe 3.4.3 hxcpp 3.4.188 on mac and now can see only black screen on android device when app started.
Rollback to haxe 3.2.1 and hxcpp 3.4.34 and the same app started normally.
Maybe something in hxcpp 188 android toolchain wrong. Did any body have the same issue?

**Comment by codeservice** [comment]
To be more specific:
09-25 22:01:20.064 9607-9607/? E/Exception: Could not load module std@base_encode__2

**Comment by hughsando** [comment]
It should not be trying to load module std - it should be statically
linked.  Something must of gone wrong here.

**Comment by codeservice** [comment]
Where to look? I have this issue only with android. Win and Mac work well so far.
I installed official haxe release 3.4.3 on Mac with hxcpp 3.4.188. I recompiled hxcpp all targets.

**Comment by hughsando** [comment]
I'm trying to track down where that is coming from.
There are references to that name from neko.  It used to be implemented in
hxcpp std.so, but should not be needed.
Maybe if you clean the export/android directory and compile again?
If this still a problem, I need to work out what source file contains
"base_encode"
when cpp is compiled.

**Comment by codeservice** [comment]
I wiped all before compile.
My steps:
1. Download and install official haxe 3.4.3 dmg file on mac
2. run haxelib setup to set libraries path (on mac for some reason it was
issue was asking for few libraries, I dont remember all, one was pcre. I
installed it with brew)
3. haxe install hxcpp 3,4,188
4. recompile all hxcpp tools with haxe compile.hxml
5. open hxcpp project folder and clean with: neko build clean
6. compile hxcpp with: neko build android
7. recompile nme tools and after: 'neko build clean' project folder compile
again with: neko build android
8. delete bin folder with all previous compiled files for my project
9. compile: haxelib run nme build /myproject..../build.nmml android
10. Install and run apk.
11. black screen with std issue.

Next I did rollback option:
1. Install haxe 3.2.1 and hxcpp 3,4,34
2. repeat all steps from previous attempt
....
no black screen, all works

Doesn't look I did something wrong

Interesting if someone can replicate this or it unique for me.

**Comment by codeservice** [comment]
I think I found problem. I am using SQLite library: https://github.com/jgranick/sqlite/blob/master/cpp/db/Sqlite.hx (line 98)

This lib has line: static var _encode = cpp.Lib.load("std", "base_encode",2);
There is no other place with base_encode usage.

Could it be reason why project not loading on android and why it works well on Mac and Win targets?

**Comment by codeservice** [comment]
Yes issue was in SQLite library not in NME. I am closing it here.
