### ISSUE TITLE
11-ColorTransform sample, bitmap transparency issue

### ISSUE THREAD

**Issue by codeservice** [haxenme/nme#510]
Image transparency looks different on nme and flash. Tested on Windows 7 (No angle)

FLASH:
![image](https://user-images.githubusercontent.com/1771547/31142946-c2b341a4-a849-11e7-918b-6fca85c965e0.png)

NME:
![image](https://user-images.githubusercontent.com/1771547/31143014-f0a2c256-a849-11e7-9853-aa76e35b44f9.png)

**Comment by hughsando** [comment]
Fixed by https://github.com/haxenme/nme/commit/8476161c0f00a568da9e2ad247b2336006c919b7
