### ISSUE TITLE
NME appears to be leaking

### ISSUE THREAD

**Issue by thomasuster** [haxenme/nme#513]
High level problem is my application is running out of memory. After some more analysis it appears that various NME objects are leaking. I'm unsure wether the problem is with them specifically or with  something more general.

<img width="1255" alt="screen shot 2017-10-07 at 10 33 18 am" src="https://user-images.githubusercontent.com/220965/31310370-f6579046-ab4b-11e7-9989-2275de0e40d7.png">

Some of the suspects...

1. nme::bare::Surface_obj::__construct(int, int, int, Dynamic) ./src/nme/bare/Surface.cpp:155

1. nme::display::BitmapData_obj::load(String, hx::Null<int>) ./src/nme/display/BitmapData.cpp:650

**Comment by thomasuster** [comment]
SimpleSurface::~SimpleSurface() never gets called, will try to make a test in NME as a next step

**Comment by hughsando** [comment]
Looks like there was some pretty bad debug left in the code.  Should be an easy fix.

**Comment by thomasuster** [comment]
Thanks! I found the line last night, had a chuckle, was trying to mkae a test. Thanks for patching :-)
