### ISSUE TITLE
Build without NME.ndll requirement?

### ISSUE THREAD

**Issue by hoseyjoe** [haxenme/nme#534]
I thought it had been building a standalone exe.  Is that possible?

**Comment by hughsando** [comment]
Yes, this is "static_nme" option.  I need to work out exactly what the specification is.  I have an example
```
<set name="static_nme" value="1" />
<haxedef name="STATIC_NME" value="1" />
<ndll name="nme" static="true" />
```
But i'm not sure what is correct.
