### ISSUE TITLE
ByteArray.hx:97: characters 12-18 : Unexpected extern

### ISSUE THREAD

**Issue by thomasuster** [haxenme/nme#548]
Repro steps:

```
cd nme/samples/DisplayingABitmap
nme test
```

Expected: Should build
Result: nme/src/nme/utils/ByteArray.hx:97: characters 12-18 : Unexpected extern

**Comment by hughsando** [comment]
Yes - we can just remove the 'extern'  until I work out what condition (haxe4?) I need here.

**Comment by thomasuster** [comment]
Fixed, thanks @hughsando
