### ISSUE TITLE
Error : nme_bitmap_data_get_floats32 does not have signature ooiiiiiov

### ISSUE THREAD

**Issue by thomasuster** [haxenme/nme#558]
`Error : nme_bitmap_data_get_floats32 does not have signature ooiiiiiov`

**Comment by thomasuster** [comment]
Maybe change in https://github.com/haxenme/nme/commit/2a03ce49e1efc240fdae0347deea5b18dbeea5ac ?

**Comment by hughsando** [comment]
Do you need a rebuild of the dll?
