### ISSUE TITLE
I'd like to be compatible with openFL / lime 

### ISSUE THREAD

**Issue by jaimedominguez** [haxenme/nme#563]
Would it be very hard to implement this ?

**Comment by thomasuster** [comment]
@jaimedominguez Short answer. Yes

Long answer: We are compatible already in many ways. (At least last time I checked a year ago or so)

The problem with this is that it cuts across the entire stack, and would require good syncing up with OpenFL org. My perspective is I think we should have conversations, and even refer to old as3 docs on occasional, to avoid diverging to much, and allow some compatibility when possible. But I think we're already passed the point of configuration differences, they shouldn't be to hard to convert though to be honest. If you have an OpenFL / Lime project that you're trying to convert, please start conversations with other NME users to help out with any NME specific problems . (Any other NME contributors please feel free to reopen or add to this thread.)
