### ISSUE TITLE
Android prime function regression?

### ISSUE THREAD

**Issue by thomasuster** [haxenme/nme#581]
```
cd tools/nme
haxe compile.hxml
cd ../../project
neko build.n android
cd ../../samples/DisplayingABitmap
haxelib run nme test android -gradle
```

Result: Compiler error in `nme/src/nme/app/Window.hx`.

This can be resolved by editing these lines...

`renderRequest = PrimeLoader.load("nme_stage_request_render", "b");`
to
`renderRequest = PrimeLoader.load("nme_stage_request_render", "v");`

and 
`public var renderRequest:Void->Bool;`
to
`public var renderRequest:Dynamic;`

That will build and run, but will show a black screen.

**Comment by hughsando** [comment]
This one is a bit trickier because PrimeLoader returns c++ function pointers, so I think it woulf be best to wrap it in a closure, like:
```haxe
var nme_stage_request_render = PrimeLoader.load("nme_stage_request_render", "v");
 renderRequest = function() { nme_stage_request_render(); return false; }
```
