### ISSUE TITLE
can't build for jsprime

### ISSUE THREAD

**Issue by nulld** [haxenme/nme#583]
Hello, trying to play with jsprime, but have a trouble with building first sample - `01-Simple`, using nme from git (commit 428ece39ab7c37ca77aac10a4820e7e3936dacc1).
Compile failed with following error:

```
Called from Sys::$statics line 1
Called from RunMain::main line 107
Called from RunMain::executeNme line 93
Called from neko.Lib::rethrow line 65
Called from RunMain::executeNme line 84
Called from neko.vm.Loader::loadModule line 134
Called from sys.net.Socket::$statics line 1
Called from CommandLineTools::main line 1476
Called from CommandLineTools::buildProject line 164
Called from platforms.Platform::init line 100
Called from platforms.JsPrimePlatform::generateContext line 275
Called from sys.io.File::getContent line 30
Uncaught exception - [file_contents,D:/devel/haxelib-dev/nme/ndll/Emscripten/parsenme.js]
```

Looks like something necessery is missing - I haven't `D:/devel/haxelib-dev/nme/ndll/Emscripten/` folder at all.

**Comment by nulld** [comment]
Finally, make it working (Download packaged nme from here `http://nmehost.com/nme/` and copy `Emscripten` folder from it). Maybe will be useful, to write some instructions - how to build nme from source?

**Comment by hughsando** [comment]
Hi,
the command is:
```
neko build.n jsprime
```
from the "project" directory
