### ISSUE TITLE
Add mouse checks for tiles

### ISSUE THREAD

**Issue by Beeblerox** [haxenme/nme#622]
Hello!
Actually this is not an issue, but a question. I've found that mouse checks in NME are not considering tiles (which are rendered with drawTiles() method). But in old OpenFL versions there were such checks. And the project i'm currently porting to NME is also expects that these checks should work, so i had to enable these checks in my fork of NME.
My questions is: would you consider the possibility of adding this functionality to NME (maybe make it switchable with some sort of additional compilation flag)? 
If yes, then i would be glad to make pull request for it

**Comment by thomasuster** [comment]
@Beeblerox IMO I think this is better to stay application side and keep the complexity out of NME.

**Comment by hughsando** [comment]
Yes, I think it would be good to add a flag 'TILE_MOUSE_ENABLE' to the drawTiles call.

**Comment by Beeblerox** [comment]
@hughsando Great! i'll prepare PR next week then

**Comment by Beeblerox** [comment]
Sorry for the delay. Here is promised PR for this feature: https://github.com/haxenme/nme/pull/629
