### ISSUE TITLE
Tilesheet decodeStream access violation on Win64

### ISSUE THREAD

**Issue by codeservice** [haxenme/nme#626]
Strange issue on big project. Not sure how can I recreate this in small example.
Project works on windows32 and other platforms except Win64 bit in some places.

Silent crash on inStream access violation: 
Tilesheet.cpp
...
void Tilesheet::decodeStream(ObjectStreamIn &inStream)
{
   inStream.get(mCurrentX);  <--- issue here

**Comment by hughsando** [comment]
It could well be a 64-bit issue.  This was originally designed to run on emscripten, which is 32 bits.
How are you using it - do you have a small test case?

**Comment by codeservice** [comment]
It works when I tried to do similar in small code chunk. In big project hard to find what exactly triggers that. If this designed to run in emscripten, why this code included in cpp target? I don’t have this issue on Mac 64 bit, maybe decode stream included only for win64 cpp and not other cpp targets. Wandering if it’s possible exclude unused code.

**Comment by hughsando** [comment]
I don't think it should be run, unless it is explicitly called.  It is
called automatically on emscripten, but unless you are doing something like
deliberately moving objects between processors, it should not be called.
If you have a call-stack then that should tell us what why it is getting
called.  My guess is memory corruption is causing a jump to random code,
which happens to be decodeStream, but maybe there is a bug calling this
unnecessarily.

**Comment by codeservice** [comment]
Yes, its what I am trying to find out. Origin of decodeStream call. For debugging I am using: HXCPP_DEBUG,HXCPP_DEBUG_LINK,HXCPP_STACK_TRACE,HXCPP_STACK_LINE and I dont see previous calls from stack trace. I think you are right its some kind of memory corruption.
