### ISSUE TITLE
Compile error: URLRequest.hx:78 : Cannot use abstract as value

### ISSUE THREAD

**Issue by cambiata** [haxenme/nme#639]
Hi!

When trying to compile a simple example, I get the following error:
c:\Users\jonas\haxe-lib\nme/git/src/nme/net/URLRequest.hx:78: characters 29-41 : Cannot use abstract as value

I'm using 
Win 10
HaxeToolkit-4-rc.3+348192fff
latest hxccp git version
latest nme git version

Any ideas?

**Comment by thomasuster** [comment]
Maybe try `4.0.0-rc.3+e3df7a4`
