### ISSUE TITLE
Proposal: Make Gradle the default android build chain

### ISSUE THREAD

**Issue by thomasuster** [haxenme/nme#655]
Gradle has been in NME for about a year now, and I was surprised to learn how easy it was to migrate old extensions from ANT to Gradle.

Proposal:
Let's make it such that `haxelib run nme android` by default uses gradle, and for legacy projects force authors to update commands to `haxelib run nme android -ant`.

Please response with a 👍 or 👎 or comment / question if you're unsure.

**Comment by codeservice** [comment]
I think starting from 2021 it will be possible submit only 64 bit apps. Using ant and NDK 15 it will be  challenging to continue support latest play store requirements, eventually only gradle option left.

**Comment by hughsando** [comment]
Yes, lets just do it.
