### ISSUE TITLE
Timer issue on haxe 4.x.x

### ISSUE THREAD

**Issue by codeservice** [haxenme/nme#657]
This code doesn't work on haxe 4.0.2

    var timer1: nme.utils.Timer = new nme.utils.Timer(300,1);
    timer1.addEventListener(nme.events.TimerEvent.TIMER, function(_){
        timer1.stop();
        trace("timer1");
        var timer2: nme.utils.Timer = new nme.utils.Timer(100,2);
        timer2.addEventListener(nme.events.TimerEvent.TIMER, function(_)trace("timer2"));
        timer2.start();
    });
    timer1.start();

This commit breaks timer2: https://github.com/haxenme/nme/commit/b4e6e2067f3af83ca0419f50c4fa4f8ef2e54aac#diff-46ff30624b29f0c64171e1014fc61bc3

**Comment by hughsando** [comment]
I think we can just remove the haxe4 resize part - it was only supposed to be an optimization but if it does not work, then no point! (or maybe check to see if it is the last entry in the array)

**Comment by codeservice** [comment]
One more option, is to try remove not active timers from array directly in “while” cycle, without reordering it and making final array cut. Doesn’t look like performance optimized but making logic more simple. I’ll try this tomorrow if nothing else better than this.

**Comment by hughsando** [comment]
Good idea - one thing to watch out for is a timer being added inside a timer callback.

**Comment by nulld** [comment]
Is it correct? Doesn't it be `splice` instead?
```
sRunningTimers.slice(timerCount, origTimerCount-timerCount);
```

**Comment by codeservice** [comment]
Yes, splice
https://github.com/haxenme/nme/pull/658/files#diff-46ff30624b29f0c64171e1014fc61bc3R196

**Comment by nulld** [comment]
@codeservice
Please check is it works now with this pull request merged
 https://github.com/haxenme/nme/pull/679/

**Comment by codeservice** [comment]
Looks ok, only can’t check on haxe 4, I had to switch back to haxe 3.4
