### ISSUE TITLE
Latest Windows tool chain (10.0.18362.0, VS2019) cannot compile SDL for m32

### ISSUE THREAD

**Issue by madrazo** [haxenme/nme#662]
Got this error wher rebuilding NME

```
Error: SDL2Stage.cpp
C:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\um\winnt.h(2482): error C2338: Windows headers require the default packing option. Changing this can lead to memory corruption. This diagnostic can be disabled by building with WINDOWS_IGNORE_PACKING_MISMATCH defined.
```

I have seen that it can be solved by setting the WINDOWS_IGNORE_PACKING_MISMATCH preprocess as follows in ToolkitBuild.xml

```
      <section if="windows">
         ...
         <compilerflag value="-DWINDOWS_IGNORE_PACKING_MISMATCH" unless="HXCPP_M64" />
      </section>
```

but then got
```
Error: SDL_dynapi.c
C:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\um\winnt.h(2487): error C2118: negative subscript
```

**Comment by cambiata** [comment]
Exactly the same error for me!

**Comment by cambiata** [comment]
Also on a second computer.

**Comment by madrazo** [comment]
So, the options are to update SDL or to skip m32 (or both)

To skip windows m32 build, added the following into Builder.hx and recompiled with "haxe compile.hxml" in tools/build

```
   override public function runBuild(target:String, isStatic:Bool, arch:String, buildFlags:Array<String>)
   {
      if(target == "windows" && arch=="m32")
         return;

      super.runBuild(target, isStatic, arch, buildFlags);
   }
```
I can use it normally except for building with **-32** which is something I am not planning to do anymore... It can be built later manually

Furthermore, a check can be added to make sure it is building from a 64 bit Windows before skipping 32 bit build:
```
   override public function runBuild(target:String, isStatic:Bool, arch:String, buildFlags:Array<String>)
   {
      if(target == "windows")
      {
         var architecture = Sys.getEnv ("PROCESSOR_ARCHITEW6432");
         var is64 = (architecture != null && architecture.indexOf ("64") > -1);
         if(arch=="m32" && is64)
            return;
      }

      super.runBuild(target, isStatic, arch, buildFlags);
   }
```

**Comment by madrazo** [comment]
Just noticed SDL is updated in git

```
git clone --recurse https://github.com/haxenme/nme-toolkit.git
haxelib dev nme-toolkit C:\git\nme-toolkit
```

solves the issue. However the option to skip m32 is desired ;)

**Comment by madrazo** [comment]
Does
`neko build.n ndll-windows-m64`
and
`neko build.n ndll-windows-m64 -debug`

should save the ndll in the same place? (ndll\Windows64)

**Comment by madrazo** [comment]
After setting my physical RAM properly and clearing the hxcpp cache it compiles normally.  The crash I got with the newer nme-toolkit was because of an angle call to __popcnt which is not implemented on my old CPU. So the issue is actually solved by updating nme-toolkit. Anyway I am thinking on adding an option to skip 32 bit build on installer
