### ISSUE TITLE
adding same event function multiple times issue

### ISSUE THREAD

**Issue by codeservice** [haxenme/nme#663]
Haxe code: 

        var startTime = nme.Lib.getTimer();

        var i = 1;
        var timer = new nme.utils.Timer(500,10);
        var func = function(e) {
            trace("timer: " + i + " Finished: " + (nme.Lib.getTimer() - startTime));
            i++;
        }
        timer.addEventListener(nme.events.TimerEvent.TIMER, func);
        timer.addEventListener(nme.events.TimerEvent.TIMER, func);
        timer.start();

Output:
timer: 1 Finished: 500
timer: 2 Finished: 500
timer: 3 Finished: 1000
timer: 4 Finished: 1000
timer: 5 Finished: 1500
timer: 6 Finished: 1500
timer: 7 Finished: 2000
timer: 8 Finished: 2000
timer: 9 Finished: 2500
timer: 10 Finished: 2500
timer: 11 Finished: 3000
timer: 12 Finished: 3000
timer: 13 Finished: 3500
timer: 14 Finished: 3500
timer: 15 Finished: 4000
timer: 16 Finished: 4000
timer: 17 Finished: 4500
timer: 18 Finished: 4500
timer: 19 Finished: 5000
timer: 20 Finished: 5000

Similar actionscript code:
var startTime = getTimer();
var i = 1;
var timer = new flash.utils.Timer(500,10);
var func = function(e) {
  trace("timer: " + i + " Finished: " + (getTimer() - startTime));
  i++;
}
timer.addEventListener(flash.events.TimerEvent.TIMER, func);
timer.addEventListener(flash.events.TimerEvent.TIMER, func);
timer.start();

Output:
timer: 1 Finished: 536
timer: 2 Finished: 1064
timer: 3 Finished: 1592
timer: 4 Finished: 2120
timer: 5 Finished: 2648
timer: 6 Finished: 3176
timer: 7 Finished: 3704
timer: 8 Finished: 4233
timer: 9 Finished: 4760
timer: 10 Finished: 5289

Twice less numbers 10<20. Which means flash doesn't add same event same function twice, even if your code has it.
Its easy to fix with Haxe, question only do we need to follow how actionscript works? I think yes. Thoughts?

**Comment by hughsando** [comment]
The flash behaviour seems a little odd to me.  I guess its so you don't "accidentally" add it twice - or so you can just add it without needing to check if you have already?
I don't think we need to strictly follow flash anymore, but as I think more about it, I can't think of a legitimate reason why you would add it twice.  Did you come across this in real life?
Other possibilities would be to throw an error so the developer can check, or add a function "forceAddEventListener" that always pushes the function if that is what you want.
All that said, I don't really mind so maybe doing the flash thing is the simplest answer.

**Comment by codeservice** [comment]
>Did you come across this in real life?

In Adobe documentation examples I can see it as "normal" and expected behavior.
https://help.adobe.com/en_US/FlashPlatform/reference/actionscript/3/flash/sensors/Geolocation.html
Check example at the bottom of this page.

Code can add update event as many times as changing status event triggered.
geo.addEventListener(GeolocationEvent.UPDATE, geoUpdateHandler);

I agree with "doing the flash thing is the simplest answer". I am using lots of exported actionscript code like Away3D and maybe deep inside of this, developer adding same function to the same event over and over because this "ok" from Adobe perspective.

**Comment by thomasuster** [comment]
I don't think this is the right behavior to add. To me it is quite unexpected the way AS handles it.

**Comment by codeservice** [comment]
I agree this add behavior strange, for actionscript it means not add but replace for the same function. It can only be useful if you want change event priority by adding the same function with different priority level. In NME you need to remove and add same function again with different level for this purpose, in actionscript only add event again. My only concern, old converted actionscript code with chance to contain this type of AS code.
