### ISSUE TITLE
Accessing Firebase

### ISSUE THREAD

**Issue by slabgames** [haxenme/nme#670]
I can see that there is now Firebase extension built in inside NME with conditional ::if NME_FIREBASE::

How can we access that conditional from NMML file?

I tried with 
```
<set name="NME_FIREBASE"> 
<setenv name="NME_FIREBASE"> 
```
both failed

**Comment by hughsando** [comment]
The lower-case version gets converted to the upper-case version in the nme tool (src/platforms/AndroidPlatform.hx).  The 'haxedef' means that the define is available in the haxe to code for making certain decisions.
So you use:
```xml
  <haxedef name="firebase" value="1" />
  <haxedef name="crashlytics" value="1" />
```

You may need to recompile the nme tool if you have been working off the git version for a while, with `haxe compile.hxml` in the 'tools/nme' directory.

**Comment by slabgames** [comment]
Thanks it works..
