### ISSUE TITLE
Issue with "Cancel the click event if the mouse-up event is cancelled"

### ISSUE THREAD

**Issue by codeservice** [haxenme/nme#677]
Regarding commit https://github.com/haxenme/nme/commit/7606977f9312c0ee96f4f9ba90bd8db7835d8eb3 (Cancel the click event if the mouse-up event is cancelled )

This breaks my old converted from actionscript to haxe code.

I tested this in actionscript:
stage.addEventListener(MouseEvent.MOUSE_UP, function(e){
												    trace("UP");
												    e.stopPropagation();
													e.stopImmediatePropagation();
													//e.preventDefault();
												   });
stage.addEventListener(MouseEvent.CLICK, function(e){
												   trace("CLICK");
												   });

Output still: 
UP
CLICK

**Comment by hughsando** [comment]
Ok, so you are saying flash does not cancel the click if you cancel the up?
Do you know if there is anything that is supposed to do this?  I can always make a new "cancelClick" or similar.

**Comment by codeservice** [comment]
It’s expected behavior https://stackoverflow.com/questions/7030072/cancelling-mouseevent-click-after-mouseevent-mouse-down but for some reason stopPropagation works only for the same event type where it was triggered. Probably best way is to remove click handler in mouse UP event and restore it again when needed

**Comment by hughsando** [comment]
I would be tempted to leave it how it is, because I think it make more sense and we are now only "guided" by AS behaviour, not married to it, but since your code actually breaks (sorry), I will change it back.  I will add a non-AS way of cancelling the follow-up events too.

**Comment by codeservice** [comment]
Thanks! I am  following actionscript logic because of old converted code
and because I am using Adobe help documents for NME. I don’t see any other
advantage of keep using this logic, maybe in case if NME need to support
Adobe Air target instead of Flash later.
