### ISSUE TITLE
fix continues integration

### ISSUE THREAD

**Issue by nulld** [haxenme/nme#685]
Atm, all travis checks fails with something like this:
```
The command "brew install neko --HEAD" failed. Retrying, 2 of 3.
```

```
Error: Your Xcode (9.4.1) is outdated.
Please update to Xcode 10.1 (or delete it).
Xcode can be updated from the App Store.
```

Btw, what do you think about porting CI to github actions?

**Comment by hughsando** [comment]
I fixed the travis a couple of days ago.  Installing neko binaries makes it more robust -once I worked out the mac rpath crap. I'm not against github actions - should be quite similar?  I'm happy to entertain suggestions.

**Comment by nulld** [comment]
> I fixed the travis a couple of days ago

Great, thanks!

> I'm not against github actions - should be quite similar?

Yes, I'm sure that it not leads to big testing code changes. Will send you pull request with staring point. Btw, is the any reason to run tests in xcode environment? Why not linux (it's more natural for using with docker, which all ci engines uses).

And do you mind if I'll port tests from deprecated haxe.unit to utest for e.g.?

**Comment by hughsando** [comment]
@thomasuster set this up - maybe he has an opinion?  I guess it gives options of testing ios, but really I think everything could be tested from linux.
utest would be fine.  I hacked the tests to work without haxe.test since I'm running the tests against 4.1 now.  But this was not a great solution.
