### ISSUE TITLE
addEventListener() and hasEventListener() not working as expected (HTML5)

### ISSUE THREAD

**Issue by glantucan** [haxenme/nme#88]
When targeting HTML5 using addEventListener to add an already registered listener to the same event on the same dispatcher as it was registered to,  duplicates the listener.

Somehow related, once a listener has been registered hasEventListener() always returns true even if you removed the listener.

Using haxe 2.10 with NME 3.5.5 through flashdevelop 4.4.2

**Comment by thomasuster** [comment]
@glantucan Is this still an issue?

**Comment by thomasuster** [comment]
stale
