### ISSUE TITLE
glUniform4fv in cpp targets doesn't work as expected

### ISSUE THREAD

**Issue by forwolk** [haxenme/nme#92]
The function in case of 32-bit float Array uploads only one element, when it should be all the elements inside array. 
http://www.opengl.org/sdk/docs/man/xhtml/glUniform.xml

glUniform4fv(val_int(inLocation),1,f); ->
glUniform4fv(val_int(inLocation), sizeof(f) / 4,f);
Or 
glUniform4fv(val_int(inLocation), sizeof(f) / 16,f);

Because I don't know whether the "sizeof" counts bytes of floats.
Without this fix "Vertex constant batching" is impossible to implement in OpenFL.

**Comment by thomasuster** [comment]
stale
