### ISSUE TITLE
Error: Library nme version dev is not installed

### ISSUE THREAD

**Issue by MetaChrome** [haxenme/nme#97]
Attempting to run run.n with neko2 (ie haxelib run nme) results in:

Error: Library nme version dev is not installed

I am also very confused by the tags of this repository. There are no tags for the releases past 3.5.4 which was 6 months ago, though the latest release on haxelib is 4.0.2 (which btw needs to be updated as it is broken from the flash.Vector)

**Comment by thomasuster** [comment]
Hey Meta, this should be working now. I even think this might get auto detected in the source development detector (I have no idea what to call it).

**Comment by thomasuster** [comment]
Hey @MetaChrome , didn't hear back so I'm going to assume your issue is fixed. If you're still having trouble let me know and I'll re-open.
